---
title: "«Adieu mariage, adieu statut de couple…»"
author: "Muriel"
date: "2021-03-31"
categories: [choix de vie, fardeau, indépendance, renoncement]
---

Je vous apporte mon témoignage, car je suis actuellement en invalidité et je touche l’AAH.

> Je suis obligée de mentir dans mes déclarations en disant à toutes les administrations que je suis célibataire. Je suis pourtant bien en couple, nous voulions nous marier, mais nous avons reculé. Pourquoi ? Car je refuse d’être une femme dépendante de son conjoint !

L’invalidité est déjà assez difficile à vivre dans d’autres domaines (banque, logement…) et maintenant le couple !  Sommes nous des rebuts de la société ?  Je vis avec moins de 1000 euros, je n’y arrive même pas seule. En plus même en couple, nous sommes deux portefeuilles totalement différents ! Adieu mariage, adieu statut de couple…

> Je me cache, même sur la boîte aux lettres !

Je désespère que la loi change, je veux garder ma dignité de femme ! Certes handicapée, mais indépendante financièrement, je ne veux pas être un boulet pour mon compagnon !