---
title: "«Si je travaille, mon épouse n’aura plus de revenu et sera totalement dépendante de mon salaire pour vivre ou plutôt survivre»"
author: "Gabriel"
date: "2021-03-23"
categories: [compréhension, dépendance financière, désir, travail]
---

Je suis en couple avec ma femme depuis l’âge de 19 ans et nous sommes mariés depuis 2018 (nous en avons 33). Nous sommes tous les deux bénéficiaires de l’AAH. Je suis sourd et elle est atteinte de mucoviscidose ainsi que d’autres pathologies.

> J’ai toujours eu le désir de travailler car j’estime le pouvoir et avoir cette chance.

Mon épouse a la vocation d’être enseignante en anglais mais sait qu’elle ne pourra jamais épouser sa destinée avec sa santé précaire. Après des études en comptabilité qui n’étaient pas faites pour moi, je me suis lancé dans les pas de ma femme et j’ai commencé une licence d’histoire et par la suite, obtenu un master MEEF sans réussir à le concours. Depuis 3 ans, je pourrais être enseignant contractuel et ainsi travailler à temps plein mais je ne l’ai jamais fait.

> Si je travaille, mon épouse n’aura plus de revenu et sera totalement dépendante de mon salaire pour vivre ou plutôt survivre.

Ses maladies sont déjà un poids conséquent pour elle et le sentiment de « ne servir à rien » est déjà fort. Elle ne veut pas me demander d’argent pour aller acheter ce dont elle a besoin ou pour se faire un « achat plaisir » ! Je comprends totalement sa situation.
Cependant, mon envie de travailler, m’épanouir, de me responsabiliser et d’entrer dans la vie active est très forte également et elle comprend également très bien ma situation. Nous nous aimons et il n’est pas question de se séparer. Cependant le sujet alimente parfois nos disputes et créer des situations de conflits et d’inquiétudes pour notre avenir.

> En 2021, il est temps de permettre aux handis d’aimer et de pouvoir vivre cette amour sans vivre dans la pauvreté.