---
title: "«Cela restreint aussi ma vie et ce qui pourrait la rendre agréable par des à-côtés»"
author: "Marie"
date: "2021-06-03"
categories: [fardeau, humiliation, infantilisation, sacrifices]
---

J’ai une maladie de la moelle osseuse depuis 7 ans. Maman d’un enfant de 10  ans et en couple, j’ai droit à l’AAH mais mon compagnon et moi travaillant , nos ressources ne nous y donnent pas accès. 
La maladie évoluant avec les années et le traitement  me fatiguant de plus en plus,

> j’aurais voulu payer de temps en temps une baby sitter qui prenne en charge un peu les trajets d’école, les devoirs, les rendez-vous médicaux (orthoptiste, orthophonie) de mon enfant. Cela m’aurait soulagé. 


Il y a une double peine à subir la maladie et à subir le poids et la lenteur des démarches administratives. La maladie évolue plus vite que le traitement des dossiers… De plus, on fait des sacrifices car être malade n’est pas un choix mais on choisit de renoncer à des aides car notre compagnon travaille.

> Cela restreint aussi ma vie et ce qui pourrait la rendre agréable par des à-côtés. Je garde mes revenus que pour le minimum. Il y a quelque chose d’infantilisant et d’humiliant de quémander de l’argent à son compagnon pour le quotidien.

La maladie a des conséquences aussi sur mon autonomie financière. Je ne peux pas travailler à temps plein comme avant à cause de la baisse de mes capacités physiques, la fatigue due au traitement et le temps des soins. 
C’est comme pour la carte mobilité inclusion que j’utilise rarement. Avec la pandémie, les files d’attente se sont allongées et la seule fois où je l’ai utilisée car je souffrais de rester debout, la caissière m’a dit sèchement que je m’étais trompée de file. Lorsque je lui ai montré la carte, elle s’est excusée en disant « ça ne se voit pas ». Et non ! La maladie et la souffrance ne se voient pas toujours ! Juste avant moi, il y  avait une personne en fauteuil. Son handicap était visible. Personne ne lui a dit qu’elle était dans la mauvaise file. Mon handicap ne se voit pas, je ne me plains pas. J’essaie de garder la tête haute même si la maladie parfois me plie de douleur.

> Cette charge finit par peser sur moi et sur ma famille alors que j’aimerai en être allégée…Que je ne me sente pas comme un fardeau pour ses proches. 


La loi d’individualiser l’AAH permettrait de rendre de l’autonomie à  la personne en situation d’handicap, de la protéger de maltraitance, de la rendre actrice de ses projets.