---
title: "«Mon conjoint et moi on a failli se quitter plusieurs fois, on en est même venu à se battre»"
author: "Émilie"
date: "2021-03-29"
categories: [dettes, séparation, violences conjugales]
---

Bonjour, je m’appelle Christian et mon conjoint Olivier. En décembre 2019 j’ai déclaré mon conjoint, conséquence début janvier la CAF m’a coupé mes droits pendant 5 mois. J’ai fait 3 tentatives de suicide car j’ai failli perdre mon appartement et j’ai été convoqué devant le juge. J’ai fait un dossier de surendettement car trop de dettes. J’ai vendu ma télévision.

> Je ne touche plus que 324€ et la CAF me prend 631€ pour payer la dette d’être en couple…

Je suis malade depuis l’âge de 15 ans, je fais de la psychose qui s’aggrave. À ce jour la CAF continue de me prendre 631€ bien que je sois à la banque de France.

> Mon conjoint et moi on a failli se quitter plusieurs fois, on en est même venu à se battre car c’est très compliqué. Pendant le confinement il fallait que l’on vole des légumes pour survivre. C’était très dur, sans compter les courriers des dettes qui n’en finissaient plus…

à ce jour c’est toujours compliqué.