---
title: "«Il devrait s’agir d’un droit propre comme pour la pension d’invalidité»"
author: "Veronique"
date: "2021-03-26"
categories: [dépendance financière, humiliation]
---

Bonjour, mon mari a perdu la vue suite à une maladie des yeux. Initialement, l’AAH est censée compenser la perte financière liée au handicap, ou faire complément pour les personnes travaillant en ESAT*. Il n’est donc ni logique, ni cohérent que le calcul soit lié aux revenus du conjoint. Il devrait s’agir d’un  « droit propre » comme pour la pension d’invalidité versée par la sécurité sociale. Ce mode de calcul est injuste et humiliant pour la personne en situation de handicap.

> Non seulement, il y a la souffrance physique et psychique, le besoin d’aide, le regard des autres, le mépris parfois, la perte de lien social, et de surcroît une dépendance financière : cela fait beaucoup.

Au sujet de l’AAH, nous sommes très mal informés : je vais donc vous donner trois petits tuyaux.

Si vous avez une PCH pour aide humaine, pour aidant familial, (environ 200 € par mois), vous n’avez pas à le déclarer ni aux impôts, ni sur votre déclaration trimestrielle AAH. Il s’agit d’un dédommagement, même si l’aidant est votre conjoint, non imposable.
Si vous percevez une rente invalidité d’un organisme de prévoyance, si ce contrat a été souscrit par un tiers (par exemple votre employeur) en votre faveur, et uniquement dans ce cas, vous ne devez pas déclarer. Par contre cette rente est imposable.
Si votre handicap ne peut évoluer favorablement, avec certificats médicaux, et que la MDPH a rejeté votre dossier après demande de recours gracieux, vous pouvez prendre rendez-vous auprès d’un médiateur de la république de votre région. C’est totalement gratuit, si votre demande est fondée, les choses vont vite.

> Au sujet des violences au sein du couple, pour nous cela n’a pas été le cas. Mais je comprends tout à fait que dans une maison où l’argent manque, cela provoque des tensions.

Tout dépend de la personnalité du conjoint, mais en aucun cas la personne handicapée n’a à accepter de la violence, même verbale.

*Etablissement et Service d’Aide par le Travail, mais cela vaut aussi pour le travail en milieu ordinaire