---
title: "«Mon ex s’impatiente et souhaite me voir partir au plus vite !»"
author: "Davy"
date: "2022-02-01"
categories: [détresse, fardeau, précarité]
---

Je suis considéré comme handicapé car je suis sujet à des crises psychotiques depuis 17 ans maintenant.
Reconnu handi par la mdph de l’Eure, je suis suivi à l’hôpital de jour.

Je suis séparé récemment, je dois trouver un nouveau logement car je vis chez mon ex.
Là où tout se complique, c’est que la CAF prends en considération ma situation d’il y a deux ans pour le calcul de la AAH. Hors, il y a deux ans j’étais pacsé et mes impôts étaient calculés conjointement avec mon ex. Donc à ce jour, je touche 300 euros au lieu des 902 euros de AAH alors que je suis isolé et que je dois rapidement trouver un logement. Bien sûr j’ai effectué une demande de logement social mais je sais que je ne peux pas compter sur cette solution avant de nombreuses années car je ne suis pas prioritaire. Ma seule solution est de trouver un logement dans le privé mais c’est complètement impossible car on me demande une attestation CAF avec une AAH complète, avec mes 300 petits euros, je ne peux donc pas me loger !

Mon ex s’impatiente et souhaite me voir partir au plus vite !
Comment puis-je m’en sortir ?
Je ne peux donc pas me loger et mes 300 euros couvrent à peine mes dépenses mensuelles.
Je ne vais pas pouvoir attendre et si mon ex me demande de partir, je me retrouve à la rue avec un traitement anti-psychotique qui me fatigue, sans toit et sans solution en espérant que je ne fasse pas une crise supplémentaire !

Voilà ma situation, j’ai recherché une solution dans tous les sens, même avec une assistante sociale mais elle n’existe pas cette solution !

> Seule la déconjugalisation me sortirait de cette situation.