---
title: "«Nous nous sommes pacsés en 2013 sans en connaître les conséquences...»"
author: "Maryline"
date: "2021-06-14"
categories: [dépendance financière, impossibilité de travailler]
---

Je vis avec mon conjoint (valide) depuis 11 ans.  Nous nous sommes pacsés en 2013 sans en connaitre les conséquences… 
De 2014 à 2017 mon conjoint était embauché en CDI, à l’époque mon AAH était diminuée à 750 euros car il touchait 1100€ de paye. 
Depuis, il a eu un licenciement économique fin 2017, a dû s’arrêter de travailler car il a eu une leucémie en avril 2018 (il est en rémission jusqu’en 2028) et depuis 2019, il travaille désormais en intérim. 
En avril 2021, il a eu une proposition d’embauche en CDI dans une entreprise,

> mais il a dû refuser car on m’aurait supprimé où diminué fortement mon AAH.

 Je suis dans l’incapacité de travailler, donc pour occuper mon temps, je fais du bénévolat à l’APF de ma région .
Pour résumer notre situation:  » si mon conjoint travaille en CDI, je risque de perdre tout ou une partie de mon AAH, donc il est obligé de rester en intérim et n’a pas la sécurité de l’emploi. Je suis dépendante de lui financièrement et voudrais bien rester autonome » 