---
title: "«Je suis salariée de la Caisse d’Allocations Familiales…»"
author: "Sarah"
date: "2021-06-05"
categories: [demployé CAF, incompréhension]
---

Je suis salariée de la Caisse d’Allocations Familiale , gestionnaire de prestations familiales.

Je tiens à vous témoigner des situations des personnes bénéficiaires de l’AAH du fait d’un handicap majeur. Lorsqu’ils déclarent vivre en couple et que leur conjoint ou  conjointe a des revenus salariés modestes, la personne bénéficiaire de l’AAH voit disparaitre ce droit.

> Bien souvent, c’est la détresse absolue quand ils le découvrent : pleurs, cris, colère. C’est la double peine et un sentiment d’exclusion, d’incompréhension. 

Pire encore  lorsque nous régularisons la situation familiale tardivement, imaginez bien que nous réclamons tous les droits versés dit « à tort »… Les montants des créances multipliés par le nombres de mois versés met à genoux le budget du nouveau couple.
Certains, plus avertis restent alors seuls dans leur logement et vivent  leur relation amoureuse  à distance, et de fait, continuent de payer seuls, leurs charges liées au logement, impliquant de fait, automatiquement des droits à l’aide au logement puisqu’ils n’ont aucun autre revenu imposable.

N’auraient ils pas le droit de vivre dignement pour  construire une famille ?

> J’ai honte quand je dois expliquer aux allocataires  un non droit ou une créance.