---
title: "«Ma copine a commencé à faire pression sur moi pour me donner de l’argent»"
author: "Antoine"
date: "2021-03-24"
categories: [abus, célibat, curatelle, dépendance financière, dignité, liberté, perte du domicile]
---

J'étais en couple et j’avais mon appartement. Quand on a voulu se marier, on a appelé la CAF pour savoir si on avait le droit à une « aide pour le mariage » . Et c’est comme ça que la CAF a été au courant de ma situation conjugale. La CAF a sucré mon AAH et mes APL, du jour au lendemain. Je me suis retrouvé sans rien ! La CAF a ouvert une enquête et mes droits ont été bloqués. Après avoir demandé de l’aide à ma mère, tout le monde m’a lâché !

> Je ne pouvais plus payer mon loyer, je n’avais même plus de quoi manger !

Ma copine a commencé à me donner de l’argent pour les courses, pour qu’on continue à se voir… Mais je ne pouvais pas payer mon loyer. Et puis au fil des mois, je ne savais plus où dormir : car tant que je n’avais pas un « chez moi » je ne pouvais pas prouver que j’étais célibataire ! La CAF m’a demandé de rembourser l’argent perçu tout le temps que j’ai vécu en couple. Je ne savais même pas qu’on ne pouvait pas aller voir sa copine dans un couple. C’est important de vivre sous le même toit, une femme qui veut vivre en couple a besoin de son homme !

> À la maison, on a commencé à avoir des tensions entre les allers-retours entre ma famille et l’appartement de ma copine. Celle-ci a commencé à
faire pression sur moi pour me donner de l’argent, c’était en contrepartie ou sous « conditions ». Je m’explique : elle dictait la façon dont je devais me conduire au quotidien.

Je ne pouvais plus vivre comme ça, dépendre d’elle complètement. J’ai perdu ma dignité, ma fierté d’homme. J’ai donc décidé de partir. Je me suis retrouvé à vivre dans une chambre à Paris puis finalement vivre dans la rue. Je n’ai cessé d’appeler la CAF, qui me répondait que ma situation était bloquée puisque j’ai été en faute.

Sans argent, sans mutuelle, sans mes médicaments, j’ai donc été
hospitalisé et une demande de curatelle a été lancée par un médecin. Dans mon dossier de demande de curatelle, il est inscrit que j’étais sans argent malgré mon droit à l’AAH. Grâce à son rapport d’expertise, j’ai pu retoucher mon AAH 8 longs mois plus tard. Mais l’expert m’a reproché de n’avoir pas bien géré mon argent que je n’avais pas et c’est ce qui a justifié la mise sous curatelle.

J’ai renoncé à habiter avec ma copine, on ne s’est jamais mariés, j’ai
dû retrouver un appartement. Ces deux années de ma vie m’ont brisé, j’ai eu une décompensation psychotique.

> Aujourd’hui cela fait 10 ans que je vis seul, du moins pas en concubinage. C’est une cruelle injustice, je le sais et en mesure les conséquences.

Je pensais que mon témoignage pourrait être intéressant alors je suis heureux qu’il vous convienne et que vous le trouviez pertinent. Vous comprenez que lorsque j’ai appris la possibilité de cette loi ça m’a fait un choc, ça aurait pu changer ma vie. En tout cas je suis gêné lorsqu’une fille parle ou propose d’habiter chez moi, ou de se mettre en couple avec moi et faire des projets. Je suis obligé de la laisser partir ou de lui dire non.

Au final on ne construit pas de relation, ça peut avoir des conséquences sur notre relation, des conséquences de rupture et c’est dommage quand même vous en conviendrez de vivre seul, ça manque de charme de pas se réveiller le matin à deux en souriant. Si cette loi passe je pourrais envisager les choses différemment.