---
title: "«Impossible pour moi de redevenir dépendante financièrement de quiconque»"
author: "Carla"
date: "2021-03-23"
categories: [dépendance financière, dignité, reconstruction, violences conjugales]
---

Témoigner… revenir et écrire sur sa vie d’avant, d’aujourd’hui… mais surtout celle que l’on ne veut plus demain ! Exercice synonyme de douleurs (encore) mais aussi porteur d’espoir. J’ai 53 ans, j’ai 4 enfants, 2 encore à la maison qui ont 15 et 20 ans. Divorcée depuis 3 ans, séparée depuis 5 ans. Je touche l’AAH à taux plein depuis 4 ans et 6 mois.

> Avant de trouver cette force vitale de pouvoir quitter notre maison, il m’a fallu presque 5 années… 5 longues années de piques… de réflexions, d’allusions à mon handicap qui ne se voyait pas… 

Au début je travaillais encore, puis j’ai réduit… »Tu travailles pour rien… », « Tes frais d’essence ne sont même pas couverts par ton salaire »… »Tu as vu ce qu’on paye de cantine pour que tu ailles bosser », etc… Énumérer est trop difficile pour moi. Et puis un jour malgré un énième « Mais ma pauvre… regarde-toi, tu as 4 enfants, tu as mal partout, tu n’es plus toute jeune, pas un centime, sans moi t’as rien… » je lui ai dit STOP. FINI.

> Il s’est vengé, à sa façon. Il a pris ma carte bleue, mon chéquier, m’a insultée, craché au visage, etc.

Il ne mettait de la nourriture dans le frigo que pour nos enfants. J’ai tenu, à aucun moment je n’ai cédé, comme je l’avais si souvent fait auparavant, par peur… La peur m’avait définitivement quittée.

> J’ai fait toutes les démarches nécessaires pour débloquer mon AAH, j’ai eu la chance de rencontrer des personnes à la CAF qui ont accéléré les choses.

Mais trouver un logement ! « Mais, Madame vous n’avez qu’une allocation, ce n’est pas pérenne… ça peut s’arrêter du jour au lendemain… ». Et oui, parce qu’en plus de la souffrance, du manque de vie sociale, du deuil de celle que vous étiez avant, de la nouvelle vie qu’il faut apprivoiser, accepter, il faut aussi que tous les 2 ans, 3 ans – ou plus c’est selon – que vous justifiez auprès de la MDPH de votre handicap, que vous leur VENDIEZ votre handicap et vos douleurs…

> Mais je l’ai obtenu mon petit nid de réconfort ! Au bout de 6 mois je l’ai obtenu ! Les combats, ces combats, plus ceux que nous infligent à tous la vie, je les ai menés, je les mène encore. 

Mon dernier fils a besoin de soins psy, que je paye, seule… Je quémande tous les mois une pension alimentaire, leur père ne les prend jamais. Les soins de mon fils restent la priorité. Donc les miens passent en second voir troisième plan. Adieu sophro, ostéo, yoga… juste kiné deux fois par semaine…

Je me suis reconstruite, un peu, je suis abîmée, à vie, je le sais. Même si je suis capable de bonheur. J’ai un amoureux depuis 3 ans, j’ai cette chance, un homme d’une intelligence, d’une patience, d’une écoute sans pareille…. mais nous ne sommes pas un couple « normal ». 

> Impossible pour moi de redevenir dépendante financièrement de quiconque. Impossible pour nous de nous marier, nous pacser, acheter une maison…. juste voir nos deux noms ensemble sur un quelconque projet…

Aucun d’entre nous ne mérite cette double peine… il est temps que les choses changent, évoluent ! Quelle image donnons nous à nos enfants, futurs citoyens de ce qu’est la loi, l’acceptation de la différence ?

**Force et courage, nous en avons, physiquement souvent moins que les autres mais notre cerveau et notre volonté est intacte ! Ensemble, on y arrivera !**
