---
title: "«Une vie en mode pause»"
author: "Anne"
date: "2021-04-09"
categories: [20 ans enfant, divorce, mendier]
---

Je suis tétraplégique de naissance et j’ai une élocution difficile. Dés qu’on m’a octroyé l’AAH, à mes 20 ans, contre l’avis de mon entourage, j’ai décidé de louer un appartement et de vivre comme tout le monde dans la société. J’ai obtenu une licence de psychologie puis je me suis mariée. Nous avons eu un enfant.

> Tous les ans on faisait attention de ne pas dépasser le plafond de l’AAH : mon mari prenait ses heures supplémentaires en repos compensateur. Les fins de mois étaient un peu compliquées mais nous y arrivions…

Je pensais avoir réussie ma vie en parfaite inclusion dans ma ville car j’étais très active associativement et politiquement pour l’accessibilité de ma commune, même si je n’ai jamais eu d’emploi. Je suis aussi connue pour avoir été « gilet jaune ».

Mais ma vie a basculé le 30 janvier 2020 lorsque mon fils est parti vivre en cité U pour poursuivre ses études car dans ce mois-là la CAF m’a diminué mon AAH et mon mari a travaillé à temps partiel, car pourquoi travailler pour avoir le même pouvoir d’achat ? 

> Sauf qu’en ayant un mari valide la CAF a refusé de recalculer mon AAH sur l’année en cours donc dans un premier temps j’ai eu peur de ne pas pouvoir payer notre crédit immobilier et de nous retrouver SDF.

À 50 ans, après une petite dépression, nous nous sommes pratiquement désociabilisés pour pouvoir survivre, nous n’avons pratiquement plus aucun loisirs, nous n’invitons que très rarement nos rares amis qui sont restés. Fini aussi de se sentir femme en allant chez l’esthéticienne et le coiffeur !

Mais personnellement ce qui a été le plus dur à vivre c’est cette ségrégation que j’avais occulté entre handicapés et valides, ça a été vraiment traumatisant de m’entendre dire « mais madame il fallait épouser un handicapé et pas un valide qui travaille »  ! 

Depuis 1 an et demi, j’essaie de trouver une solution pour vivre et non survivre mais ayant acheté un appartement à crédit (d’ailleurs les banques comptent l’AAH pour le crédit), nous ne pouvons pas divorcer et nous devons attendre pour vendre !

> Depuis 1 an nos parents nous ont aidé surtout lorsque mon fauteuil est tombé en panne car nous n’avions plus les moyens de le faire réparer et pour l’instant la solution provisoire est la banque alimentaire donc nous sommes devenus des mendiants ! Ce qui n’est pas évident à vivre !

Nous voudrions pour notre couple que la loi passe car ce calcul de l’AAH est un frein à la carrière professionnelle de mon mari et nous attendons pour faire des projets d’avenir…