---
title: "«Je ne veux pas vivre une triple peine»"
author: "Jeanne"
date: "2021-03-27"
categories: [difficulté à travailler, stress]
---

J’ai 24 ans. Je suis une jeune femme autiste allocataire de l’AAH qui vit entre chez son père et sa mère car mes parents sont divorcés. Je suis une jeune diplômée en Master en Histoire des Arts de la Sorbonne. Je recherche donc actuellement un emploi dans le domaine des musées. Je cumule plusieurs handicaps, l’autisme, qui entraîne une discrimination à l’embauche surtout en France et le fait d’avoir choisi une voie, l’histoire des arts qui est un secteur sinistré et ce bien avant la COVID.  J’ai posé un pied à la fac, on m’a dit tout de suite qu’il n’y avait pas de travail. Seulement des petits boulots de vacataire sous-payés sans aucun droit à congés. Il est très dur de trouver des postes de contractuelle ou de fonctionnaire, même si on est valide. Mais comme ces postes de fonctionnaire sont des postes à responsabilité, ils me seront plus difficilement confiés.

La meilleure chose que je puisse obtenir en France, c’est l’AAH en plus de petits boulots ça et là.  Mais seulement si je vis seule. 

> Si l’amour parvenait à frapper à ma porte et que j’avais un petit boulot, je ne pourrais toujours pas m’installer avec un homme. En effet, dans ce cas, si je perdais mon petit travail de vacataire, je vivrais aux crochets de mon conjoint, qui aurait probablement un salaire moyen, « trop élevé » pour que je touche l’AAH.

Je n’aurai sans doute pas assez cotisé pour avoir un complément de libre choix d’activité car je n’aurai peut-être pas assez travaillé.  Je pourrais peut-être toucher le RSA, mais il risque d’être supprimé car je serai obligée de refuser des emplois ou les équipes ne voudraient pas s’adapter à mon handicap, ou des emplois ou le permis est obligatoire, ou en province où je n’aurais personne dans ma famille pour m’aider (sauf si on m’accorde une PCH). Donc si j’ai un emploi de vacataire et que je le perds, je ne pourrais plus redemander mon AAH, car les revenus de mon conjoint seront pris en compte.

J’aimerai aussi écrire des livres, faire des vidéos sur YouTube mais si ça marche trop peu ou plus, je me retrouverai de longues années sans revenus. Donc je souhaiterais recevoir l’AAH quoi qu’il arrive si je ne parviens pas à trouver un emploi stable, qui est mon objectif premier.

Je lutte pour un monde du travail accessible aux personnes handicapées, afin de réduire les demandes d’AAH, et pour la déconjugalisation de cette allocation. Je milite pour que l’État cesse de financer des institutions privant les personnes handicapées de libertés et qui coûtent des milliards d’euros au contribuable, ce qui pourrait servir à financer les 560 millions d’euros que coûte la déconjugalisation de l’AAH. Pour que le reste de cet argent serve aussi à financer de plus en plus d’aménagements des entreprises et des logements. Je milite aussi pour que les travailleurs en ESAT puissent se syndiquer et avoir le droit de faire grève et de disposer de leur propre salaire et puissent être redirigés vers le milieu ordinaire avec de bons aménagements. Je voudrais que les personnes autistes aient plus de facilités à accéder à une PCH , afin de payer leur thérapie ou de payer des auxiliaires de vies pour ceux qui ont les problèmes de coordinations les plus grands, dont je fais partie.