---
title: "«Que mon conjoint gagne 10€, 1000€, 2000€, je serai toujours autant malade»"
author: "Hélène"
date: "2021-03-31"
categories: [impossibilité de travailler, perte de revenus]
---
Aujourd’hui je suis malade, hier j’étais malade et demain je serai malade. Dans 2 ans, je serai toujours malade. J’ai eu un travail. Et à ce niveau, c’était : pas d’augmentation car, je cite : « tu es trop souvent absente ». Pourtant je ne passais pas ma journée à me reposer ! Quand j’étais absente, c’était pour passer cette même journée à l’hôpital !

> J’aurais préféré aller bosser ! Puis finalement, j’ai perdu mon boulot. Le harcèlement, c’était dur !

Entendre qu’on ne peut pas compter sur moi par exemple, et j’en passe…

> Que mon conjoint gagne 10€, 1000€, 2000€, je serai toujours autant malade. Aujourd’hui, mon AAH est de 0€ , car mon conjoint a eu son 13ème mois en décembre. Pourtant, si la MDPH m’a accordé l’AAH à vie, c’est parce que car je ne guérirai pas. 

Je vais donc refaire ma déclaration trimestrielle dans quelques jours, j’espère pouvoir retoucher une partie de mon AAH. Aujourd’hui je dois tout demander à mon conjoint !

**Être malade c’est vraiment être inégal par rapport aux autres. Pourtant, on a rien demandé.**