---
title: "«Je vis dans le péché...»"
author: "Angélique"
date: "2022-02-01"
categories: [dépendance financière, dignité, impossibilité de travailler]
---

J’ai 45 ans et je vis dans le péché avec Didier. Par péché, je veux dire tout ce qui englobe les mots qui désignent un couple. Je vis donc AUX CROCHETS DE MONSIEUR.

Eh oui, je savais que ça allait encore arriver ! Une amputation de ma liberté financière après le départ de ma fille pour ses études. Mais autant !

> Je ne pensais pas que je passerai de 520 € à 68€ ! C’est vraiment incroyable !

Parce que j’ai oublié de vous dire, je suis handicapée dans l’incapacité de travailler ! Je suis dans le cercle vicieux de l’AAH, ce système soit disant pour aider les personnes en situation d’handicap. Alors déjà vivre avec un handicap, c’est un combat de tous les jours et en plus, il faut se justifier régulièrement auprès de la MDPH. Presque pleurer pour pouvoir être reconnu comme telle !

Aujourd’hui 22 septembre 2021, après consultation sur mon compte CAF pour la prestation AAH, mon amour-propre prend un coup . Je me sens comme un déchet de la société. Maintenant vais je devoir quémander à Didier le droit de prendre une douche ou même de manger ? Puisque je vis à ses crochets.

**On prend en compte les revenus de mon compagnon pour le versement de l’AAH alors que l’on est même pas mariés ! Dur dur de comprendre la société...**

Je vous remercie de m’avoir lue même si je suis une goutte d’eau dans l’immense océan de la politique.
