---
title: "«Parfois je me demande si c’est vraiment avantageux de continuer à travailler...»"
author: "Yohan"
date: "2021-06-05"
categories: [dépendance financière, double peine, impossibilité de travailler, infantilisation]
---

Dans le cas de mon couple, ma compagne ne pourra plus travailler suite à sa rupture d’anévrisme, et elle sera bientôt en invalidité. À partir de ce moment, elle n’aura plus aucun revenu, donc elle sera complètement dépendante de moi, financièrement.

> Je pense que c’est un double poids : le handicap et la dépendance financière. 

La personne handicapée sans revenu doit toujours demander l’accord du conjoint.e pour faire une dépense. Et la personne qui travaille doit assumer la totalité des dépenses mensuelles. Je me demande si les couples dans ce cas peuvent avoir des loisirs et des projets.

Je pense que c’est de l’infantilisation, et malheureusement ceci est fréquent dans le domaine du handicap. De plus, j’ai l’impression que cette situation ressemble à l’époque où les femmes ne pouvaient pas ouvrir un compte banques, sans l’accord de leur mari.

De plus, je suis moi-même handicapé, donc j’ai des dépenses supplémentaires liées à cela, surtout pour mon fauteuil électrique.

> Parfois je me demande si c’est vraiment avantageux de continuer à travailler, une fois que ma compagne sera en invalidité.

Évidemment je continuerai par amour de mon métier, mais il faudra faire attention à nos dépenses. Et je souviendrai aux besoins de ma compagne, avec plaisir. Mais ce n’est pas normal de ne pas pouvoir vivre comme un couple valide.

