---
title: "«Je vis sous la coupe de mon compagnon qui manifeste une violence verbale journalière envers moi»"
author: "Catherine"
date: "2021-06-03"
categories: [dépression, suicide, violences conjugales]
---

Je suis reconnue « travailleur handicapé » par la MDPH depuis 1999.
Je vis sous le même toit que mon compagnon depuis 3 ans, faisant suite à la naissance de ma fille en septembre 2017. Mon AAH a été presque suspendue par la CAF en 2018, je ne percevais alors moins de 250€. On m’a même demandé de rembourser plus de 16 000€ , alors que j’avais signalé mon changement de « statut » et que je savais ne plus avoir le droit de toucher cette fameuse AAH. Mon AAH a donc été considérablement réduite et à l’époque pour se rembourser, la CAF ne me versait plus la PAJE…

> Je vis sous la coupe de mon compagnon qui manifeste une violence verbale journalière envers moi.

Pour le moindre achat, visite chez le médecin  etc. , j’ai le droit d’entendre : « je ne suis pas Rothschild ou bien le Président », » espèce de connasse « , « sale pute », « je vais te faire enfermer », « je vais appeler les pompiers »…
Je précise qu’en plus de ma spondylarthrite ankylosante, je suis soignée pour une maladie bipolaire;

> je n’en peux plus de devoir « faire la manche » et d’être à la merci de cet être qui se montrait totalement sous un autre jour du temps où ne nous vivions pas encore sous le même toit…


Cet homme me fait me sentir inutile aux yeux de la société et me pousse vers le bas et si je n’avais pas une once de volontarisme et surtout si je n’avais pas mon traitement en « tuteur », je me serais je pense, déjà suicidée…
La violence verbale fait partie de mon quotidien et je ne la supporte plus, j’ai demandé un appartement afin de me séparer et depuis peu ai donc retrouvé mes droits… Mais je me bats pour que les couples ne se séparent plus à cause de cette loi imbécile qui veut que dès lors que vous vivez sous un même toit même sans être mariés et donc à pas l’abri des aléas de la vie, décès du conjoint, ( pas de réversion), et etc. , (aucune reconnaissance), ne soit plus d’actualité et donc que les revenus du conjoint ne soit plus pris en compte. 
Mon « futur » ex,  puisque je vie encore sous le même toit que lui, gagne 2200 net je crois car je n’ai pas accès à ses fiches de paie. Nous vivons sur Paris avec un loyer de 960€ par mois, une petite fille en bas âge, la mutuelle, les assurances, les courses, le coût des réparations voiture et sa consommation d’essence, et etc. Je précise que j’ai ma fille à charge pour tout ce qui est vestimentaire depuis sa naissance et que mon « compagnon » n’a jamais acheté quoi que ce soit pour elle d’autre que le lait et les couches… J’achète donc ses vêtements sur des plateformes de vente d’occasion car je ne peux faire autrement mais ma fille est toujours très joliment habillée et on ne peut rien déceler de l’extérieur…
Ma demande de logement est en cours mais je n’ai plus d’appartement à échanger comme j’aurais pu le faire autrefois. Aujourd’hui et je dois me rendre à l’évidence,

> il me faudra courber le dos pour contrer les harcèlements de mon « colocataire » et surtout ne plus rétorquer à sa violence verbale devant ma fille qui est comme « prise en sandwich » entre nous deux, car les dégâts engendrés sur sa personne en devenir et son enfance sont néfastes.


Voilà mon récit est terminé, c’est ma triste réalité.

