---
title: "«Pourquoi autant de mépris ?»"
author: "Elise"
date: "2022-02-01"
categories: [dépendance financière, fardeau, isolement, mépris, prisonnière]
---

J’ai un handicap psychique, dit invisible à plus de 80 %. Ne pouvant donc pas travailler, je dépends complètement de mon conjoint financièrement. Et il me le fait ressentir.

J’ai honte, je me sens inutile, dépendante, et prisonnière. Je suis donc isolée et ne trouve en aucun cas ma place dans cette société soit disant inclusive (…).

> Je sais pertinemment que je ne suis pas la seule dans ce cas. Pourquoi tant d’incompréhension de la part du gouvernement de Macron ? Pourquoi autant de mépris ? Je n’ai pas choisi mon handicap.

C’est douloureux de se sentir rejetée et il est très difficile de voir le bout du tunnel. Mon mari est loin d’être riche, juste au dessus du plafond. Mon fils de 18 ans qui a choisi des études spécifiques à l’étranger se retrouve dans une école privée ne peut percevoir une bourse. Je suis triste de ne pas pouvoir lui venir en aide financièrement et également triste de savoir qu’il est déjà endetté parce qu’il a été obligé de contracter un prêt étudiant.

> Le monde de Macron est loin des préoccupations des femmes en situation d’handicap.

Il n’est pas concerné par la misère des personnes qu’il est censé représenter. Ce témoignage est loin de dire mon mal être et mon désarroi.