---
title: "«On me conseille de frauder»"
author: "Andréa"
date: "2022-02-01"
categories: [choix de vie, colère, dépendance financière]
---

J’ai 25 ans, autiste asperger diagnostiquée à mes 17 ans. J’ai reçu l’AAH depuis mon diagnostic, et vu que cette allocation est faible pour avoir un logement, je vis encore actuellement chez mes parents. 

Je suis en recherche d’emploi depuis 2016, malheureusement mon autisme ne fait qu’effrayer ou laisser les préjugés envahir les employés que j’ai tentée de convaincre dans ma recherche d’emploi. Je fais du coup partie des 95%  d’autiste au chômage en France. 

J’ai fini par découvrir la loi de l’AAH en couple via mon assistante sociale, car je suis en couple depuis quelques mois. On essaye avec mon petit ami également autiste, de quitter nos logements parentaux, et on nous annonce que mon AHH sera réduite ou risque de disparaitre dû au travail de catégorie B de mon petit copain. 

> Je ne peux m’imaginer vivre soumise et dépendante de mon petit copain, lui demander de l’argent pour payer ma psychologue et psychiatre , ainsi que mes envies de sorties ! Psychologiquement, je peux pas ! Je refuse ! 

Furieuse, injuste, je suis depuis en conflit avec moi-même car on me conseille de frauder pour ne pas à choisir entre mon couple et mes ressources pour vivre !

**Est-ce comme cela que la société imagine les personnes handicapés ? Vivre célibataire à vie pour manger et avoir un toit ? ou être dépendant du conjoint sans aucune autonomie financière ? Le gouvernement me force t-il à vraiment choisir entre ces deux choix ? SEULE ou SOUMISE ?!**

Nos arrières grands-mères se sont battues pour que leurs compte en banque ne soit plus contrôlé par leur maris et maintenant ce sont les femmes et hommes handicapé.e.s qui demandent à ne plus être soumis au salaire de leur conjoint(e) ! Nous sommes au XXI e siècle ! Il est temps d’abolir cette loi qui ne devrait même pas exister !  Mon AAH, Mon handicap !