---
title: "«Nous avons fini par rompre, une rupture douloureuse et subie»"
author: "Susie"
date: "2021-04-26"
categories: [20 ans enfant, dignité, indépendance, redevable, rejet, renoncement au couple, rupture]
---

Je suis titulaire de l’AAH, et j’ai deux filles.
Par le passé, j’ai rencontré un homme.  Il est devenu mon compagnon. Nous voulions faire notre vie ensemble et vivre ensemble sous le même toit avec mes enfants et ses deux enfants. 

> Mais quand j’ai su que mon AAH serait supprimée totalement si nous nous installions ensemble, nous avons renoncé.  Nous avons fini par rompre, une rupture douloureuse et subie.

Il travaillait pour un salaire de  2500 euros. Imaginez vous vivre à  6 avec 2500 euros ? Impossible.  

Voilà le prix de l’amour… Je ne veux être redevable de personne !

**C’est comme si pour un foyer normal, le salaire d’une personne ne devrait pas dépasser un plafond en fonction du salaire de l’autre !**

Pour moi aujourd’hui, être handicapée signifie d’être  rejetée par la société :

Pas le droit de vivre en couple avec dignité et indépendance,
Difficile de trouver du travail, 
Impossible d’investir, 
Difficile de trouver un logement.  
Aujourd’hui je vis seule avec ma fille majeure, la plus grande fait sa vie… Que se passera-t-il quand elle aura 20 ans ? Que se passera-t-il si elle travaille et reste avec moi pour m’aider ? Je ne le sais même pas…