---
title: "«Cette allocation qui me permet de survivre est aussi celle qui me fait mourir de tristesse et de solitude à petit feu»"
author: "Annie"
date: "2021-03-23"
categories: [décohabitation, dignité, liberté, renoncement, violences conjugales]
---

J’ai 28 ans et je suis amoureuse. Amoureuse et aimée en retour. Malgré la maladie qui me ronge petit à petit. C’est une myopathie, mon corps entier est atteint. J’ai également été atteinte d’un cancer à l’adolescence. Je suis handicapée à plus de 80%.

Je suis amoureuse mais je touche l’AAH. Et aujourd’hui cette même allocation qui me permet de survivre est aussi celle qui me fait mourir de tristesse et de solitude à petit feu. L’homme de ma vie touche 1700 € nets tous les mois, il a changé de travail pour passer plus de temps avec moi et pour me soutenir au quotidien. Nous ne nous voyons que les week-ends et parfois en semaine depuis 3 ans.

> Ma valise n’est jamais posée. C’est comme un amour interdit, clandestin, et pourtant, il me demande de devenir sa femme.

J’ai répondu OUI et NON. Les larmes aux yeux, larmes sucrées de bonheur, larmes salées de malheur.

Car voyez-vous, par le passé, j’ai atrocement souffert d’une autre relation, avec une AAH diminuée, me privant d’amour propre, de liberté et de dignité. Mais comme cela ne suffisait pas en plus de la maladie, j’ai souffert de maltraitance, violences psychologiques ! Humiliée, manipulée, insultée par une famille entière. Je suis marquée à vie.

> Aujourd’hui je ne veux pas être une charge pour l’homme de ma vie, il n’a pas à devoir m’acheter des protections hygiéniques, des vêtements, des chaussures, du matériel de confort médical, le crédit de mon auto adaptée.

Je vis chez mes parents, non, je vis dans ma chambre chez mes parents. Je ne supporte pas la solitude.

> Le temps passe, mon autonomie physique s’amenuise, je rêve de pouvoir danser un jour en robe de mariée, dans les bras de mon aimé.

Si l’AAH n’est pas prochainement déconjugalisée des revenus du conjoint, je ne sais plus quoi faire de ma vie. Aimer sans vivre l’amour, c’est trop dur. Vivre sans aimer et être aimé, à quoi bon ?