---
title: "«Je suis une ex victime de violences conjugales»"
author: "Claire"
date: "2021-03-30"
categories: [isolement, solitude, soumission, tutelle, violences conjugales]
---

Je suis une ex victime de violences conjugales. Et pour ne plus en subir, je vis seule depuis plus de 15 ans, sans attache. Parce que ma perte d’autonomie financière est un risque réel de me trouver de nouveau en état de soumission totale ! Perdre ses droits, perdre son identité, perdre ses repères… Puis vivre dans l’isolément avec le handicap. Ces situations sont toujours plus difficile à dénoncer, à faire comprendre à son entourage.

Alors le choix est simple, la solitude totale ! Ma perte d’autonomie financière est un risque réel de me trouver de nouveau en état de soumission totale ! Il coûte cher en terme d’accompagnement, de logements à adapter. Notre maladie ne doit pas être une double peine !

> Être handicapé-e, ce n’est pas un choix, c’est un état limitant nos choix  ! Alors nous condamner à  vivre seuls-es c’est une discrimination sociale et une mise « sous tutelle » de notre citoyenneté.

Nous sommes suffisamment dépendants-tes de notre corps pour ne plus subir les recherches d’économie de l’État à tout va. Être malade, handicapé-e ce n’est pas un choix c’est notre réalité. 