---
title: "«Certains jours, j’ai vraiment envie de partir !»"
author: "Nathalia"
date: "2021-03-31"
categories: [dépendance financière, perte de revenus]
---

J’ai 55 ans, j’ai toujours travaillé, depuis mes 16 ans. J’étais peintre en bâtiment. Suite à une opération du dos et à une autre pathologie auto-immune, je suis en invalidité depuis 2016.

> Je touchais 320 € d’AAH par mois. Mon fils a trouvé du travail, n’étant plus à « charge », mon AAH est maintenant de 0 € !

Ce manque de revenu m’oblige à demander à mon conjoint qui paye déjà tout (maison, factures, courses) de m’aider pour ne pas finir les mois dans le rouge.

> Je veux pouvoir vivre correctement sans rien lui demander ! Je perds ma dignité. Franchement, certains jours, j’ai vraiment envie de partir ! Ce n’est pas à lui de se priver comme il le fait pour subvenir à mes besoins !

Je n’ai pas demandé à me retrouver dans cette situation, je préfèrerais travailler mais je ne peux plus. J’ai vraiment l’impression d’être démunie de tout.