---
title: "«Nous sommes condamnés à vivre au jour le jour»"
author: "Sophie"
date: "2021-04-15"
categories: [choix de vie, dépendance financière, endettement, précarité, privation, projets]
---

J’ai 44 ans et j’ai un taux d’invalidité à 80%. Je souffre d’une maladie orpheline appelée myosite ossifiante progressive musculaire. Pour me déplacer j’ai un fauteuil roulant. Je vie en couple depuis 17 ans. Mon mari est ambulancier et son salaire joue beaucoup sur mon AAH du fait de ses heures supplémentaire. Avant que nous nous mettions en ménage, j’habitais chez mes parents et percevais 600€.

Mon compagnon (divorcé et une pension alimentaire pour son fils) était alors cadre dans son entreprise et touchait un salaire confortable mais en rapport avec les heures qu’il effectuait. Nous n’étions ni mariés, ni pacsés. Quand nous avons décidé de nous installer ensemble, nous avons signalé mon changement d’adresse et de situation familiale. Je m’attendais bien évidemment à une baisse de mes revenus mais pas à ce point là. Ma première alerte a été une lettre recommandée de ma mutuelle santé pour me dire que mon prélèvement n’était pas passé.

> J’ai eu la surprise de constater qu’au lieu des 600€ mensuels habituels, mon allocation était tombée à 64€ ! Oui, oui, vous lisez bien ! Et tout ça sans aucun courrier préalable pour vous avertir. 

Je ne pouvais plus payer ma part de courses, mes factures, les médicaments non remboursés (entre autres ceux pour mes yeux touchés par ma pathologie et pourtant une partie du traitement n’est pas remboursée). Du coup je devais faire des choix pour ne pas dépendre entièrement de mon ami et parfois au détriment de ma santé.

Depuis que nous sommes ensemble ça a toujours été compliqué. Mon mari doit gérer ses heures pour ne pas avoir un salaire trop élevé pour ne pas me pénaliser. Dans le même temps cela nous empêche de cumuler un « bas de laine » pour faire face à d’éventuels imprévus. En clair, nous sommes condamnés à vivre au jour le jour.

> Cette situation agit non seulement sur notre qualité de vie mais aussi au sein même de notre couple. Parfois quand la tension est trop forte, je me demande ce qui adviendrait de moi si on en arrivait à se séparer.

En 2019 nous avons hélas dû faire face à un de ces imprévus. Mon mari est tombé malade et est resté arrêté cinq mois et demi. Plus le temps passait et plus les indemnités diminuaient, mais pas les charges. Nous avions commencé à prévenir notre propriétaire d’éventuelles difficultés pour payer notre loyer. Fort heureusement cette personne est très compréhensive et nous a dit de faire comme on pouvait et que l’on régulariserait plus tard.

Nous avons pris contact avec une assistante sociale pour pouvoir nous donner un peu d’air et permettre à mon mari d’être réellement remis pour reprendre son travail. Le rendez-vous c’est soldé par un « désolé on ne peut rien pour vous ». Nous nous sommes alors tournés vers un crédit à la consommation et mon mari a repris son travail plus tôt qu’il n’aurait fallu. A ce jour nous continuons à payer ce crédit en espérant ne pas à avoir à faire face à un autre gros problème.Quand nous avons un projet, ne serait-ce que partir en vacances, nous devons le budgétiser en économisant sur autre chose. 

Si la personne handicapée n’a pas ou peu d’allocation, elle doit demander de l’argent ou justifier ses dépenses sur le compte familial et même oublier la possibilité de faire une surprise à son conjoint.
Pour notre propre situation, mon mari a un projet professionnel mais, il doit le brider afin de ne pas dépasser le sacro-saint plafond et, de part le fait, se retrouver dans une situation financière plus difficile en gagnant davantage d’argent. Un paradoxe s’il en est !

> Il est plus que temps que nos dirigeants prennent pleine conscience de la vie des personnes en situation de handicape. Déjà, une bonne partie de la société se charge de nous le renvoyer au visage . Cette allocation est là pour pouvoir soit disant vivre dignement.

Pouvez vous me rappeler le montant du seuil de pauvreté ? Pour une personne seule il est de 1228€ mensuel et de 1550€ pour un couple (chiffres 2020). L’AAH à taux plein pour une personne seule s’élève à 902,70€.

Que doit on en déduire ? Pourquoi indexer cette allocation sur le salaire du deuxième membre du couple ? Ce montant dépend bien de notre invalidité ? Est-ce qu’elle diminue quand le salaire du conjoint augmente ? Personnellement je ne m’en suis jamais rendue compte.

En ce qui me concerne, j’ai déjà beaucoup de mal à non seulement accepter mon handicap, mais aussi qu’il évolue. Alors oui, oui, oui je demande à ce que l’on désolidarise le revenu du conjoint de l’AAH de la personne handicapée.

> J’interpelle Madame Sophie Cluzel.

Cette allocation est censée nous permettre de vivre dignement. Actuellement elle nous permet au mieux de survivre en oubliant tout espoir de pouvoir améliorer sa situation. Pourquoi nous condamner de la sorte ? Une personne en situation de handicape n’a-t-elle pas le droit d’aspirer au bonheur ?