---
title: "«Je voudrais témoigner en tant que conjointe»"
author: "Anne"
date: "2021-03-23"
categories: [conjoint, divorce, pauvreté, renoncement, stress]
---

Mon mari perçoit l’AAH depuis plusieurs années et son handicap n’est pas réversible. Je perçois de petits revenus. C’est-à-dire généralement moins que le SMIC mensuel temps complet.

Notre stress, au-delà du fait de vivre en dessous du seuil de pauvreté français, c’est qu’à la moindre variation de mes revenus, nous perdons de notre revenu global.

> Depuis des années, je refuse des opportunités de travail et d’évolution dans ma carrière, car le salaire proposé même s’il est intéressant, ne suffirait pas à compenser la perte d’AAH et d’allocation logement de mon mari.

En gros, je ne peux prendre aucun risque qui nous ferait perdre ne serait-ce que 50 € ou 100€ sur un revenu mensuel global d’un budget plus que serré. En plus de cela, depuis des années, je n’ai droit à aucune aide par ailleurs. Pas de prime d’activité pour moi, pas d’allocation logement, rien. Je gagne moins que le SMIC mensuel, mais vu que mon mari perçoit l’AAH, je n’ai droit à aucune prime d’activité depuis sa création.

> En plus depuis janvier 2021, l’AAH et les allocations logements de mon mari ont baissé.

Le calcul était censé être à l’avantage des bénéficiaires mais il n’en est rien.

> De mon côté, je veux bien travailler plus mais la moindre variation de salaire pour moi nous coûte plus qu’elle ne nous rapporte.

Et le calcul de l’AAH et des allocation logements est tellement obscure qu’il est quasi impossible de prévoir et de calculer par nous-même.

Donc en résumé, ma carrière est en sourdine, je n’ai pas droit à la prime d’activité qui devrait en moyenne être de 300€ mensuel pour moi, je n’ai pas droit à une aide au logement et il m’est impossible de connaitre à l’avance l’incidence précise de mon activité sur les aides de mon mari.

> Donc concrètement aimer et vivre avec mon mari me coûte cher, très cher même. Est-ce que c’est une source de stress ? Oui, pour nous deux. Évidemment on a pensé à divorcer. Mais c’est hors de question. Autrement ça voudrait dire qu’ils ont gagné, or il n’y a jamais rien à gagner à renier ceux que l’on aime. 