---
title: "«Je dois donc payer le prix de ce projet, prendre tous les risques pour me retrouver en situation de dépendance financière totale»"
author: "Fanie"
date: "2021-03-24"
categories: [conflits, dépendance financière, projets, risques, violences conjugales]
---

Il y a 15 ans, je vivais ma première véritable histoire d’amour. 
Lui, âgé de 3 ans de plus que moi, a eu un passé bien difficile, de chantiers d’insertion en logements précaires. Moi, j’ai tout juste 18 ans, une maladie génétique qui m’handicape à 80% et me rend entièrement dépendante à certains moments de ma vie.

Tous les deux, on décide d’écrire une nouvelle page ensemble, pour s’en sortir.

C’est mon premier logement car je vis encore chez mes parents. J’effectue les démarches de mon côté, je fais mes études et travaille dès que j’en ai l’occasion, l’AAH me permet de payer un loyer et quelques factures. Lui enchaîne sur quelques missions d’intérim, puis plus rien. Il n’a pas de quoi payer les factures, puis il n’a plus aucun revenu. On se renseigne pour qu’il puisse faire une demande de RSA. Refusée tout net…

> Pas de cumul AAH & RSA…

C’est injuste, on est déjà en situation précaire à tenter de joindre les deux bouts, et ça s’empire… On vit à deux sur mon AAH, soit 900 euros, et la situation entre nous se dégrade largement.

> Des disputes, des insultes, et parfois même, de la violence physique. Il me met en tête que je suis incapable de gérer le logement, qu’il en fait trop, que s’il part je ne m’en sortirai pas… Et insidieusement il arrive à me le faire croire. La situation m’échappe…

Je lui demande de partir, il part quelques jours… Je me déclare seule à la CAF, imaginant que cette situation va prendre fin, mais je n’arrive pas à m’en sortir. De son côté, il effectue une demande de RSA alors qu’il est hébergé à titre gratuit. Mais il revient… Il ne participe pas financièrement à mon logement, et étant au bord du gouffre, dans les périodes où il revient à la maison, on sait qu’on a une épée de Damoclès au dessus de la tête.

C’est une grande source de stress pour moi qui mène la barque comme je le peux. On vit de cette manière durant 3 ans… Puis contrôle de la CAF, c’est la descente aux enfers, toute ma vie est épluchée, nous sommes humiliés car traités comme des resquilleurs… Je démontre pourtant que j’assume seule mon logement et que la notion de couple ne peut être retenue, mais ce n’est pas le point de vue de la CAF puisque il lui arrive de donner mon adresse comme lieu de domicile… Nous sommes condamnés à devoir rembourser plus de 2 500 euros…

> Je me retrouve à devoir justifier de ce « couple » que je subis tellement.

Cette épreuve me met plus bas que terre. Et désormais il ne veut plus partir. Pourtant je le mets au pied du mur, je ne veux plus de cette vie là, mais il revient toujours chez moi, dès que les personnes qui l’accueillent souhaitent le mettre dehors. Je vis un enfer, et ma maladie me rend vulnérable, et dans ces moments, c’est la seule personne sur qui je peux compter. Je me dis qu’il va trouver un emploi et que cela lui permettra de trouver un logement mais les mois s’écoulent et on se cache, on se dissimule, la honte et la peur d’un nouveau contrôle. Je suis sous emprise, dans une spirale infernale, je fais des crises d’angoisse quotidiennement. L’année suivante il retrouve un emploi en intérim, l’espoir renaît. Je trouve le courage de partir de mon logement en lui mettant un ultimatum : je ne rentrerai que quand il sera parti… Il part, je me retrouve seule, c’est très difficile mais je suis libérée.

> Cette expérience de la vie de couple m’a traumatisée. Car au delà des aléas propres au handicap, à la vie à deux, les règles de l’ AAH m’ont conduite à être dans une situation de dépendance, et même si je n’étais pas dépendante de lui, il l’était de moi, l’effet est le même. 

Aujourd’hui je me suis remise de cette histoire, autant qu’on puisse l’être. J’ai rencontré quelqu’un de bien depuis quelques mois, et on aimerait vivre ensemble, sauf qu’il travaille sur Paris, et que si on souhaite mener notre projet à bien, je vais devoir quitter tout ce que j’ai pour le rejoindre, retour à la case départ, et en prime, mon AAH sera supprimée, puisque il touche un salaire moyen pour la région parisienne mais qui, pour la CAF, est trop élevé (1600 euros).

> Je dois donc payer le prix de ce projet, prendre tous les risques pour me retrouver en situation de dépendance financière totale en plus de la lourdeur de la maladie à gérer.

Pour lui, c’est déjà pas un cadeau mais là, c’est carrément du masochisme ! Cette loi nous pousse à vivre seul, à rester chez nos parents ou à aller en institution spécialisée, ça ne va pas dans le sens de l’épanouissement de la personne. Je m’estime chanceuse d’être dans un pays qui me permette de pouvoir « m’autoriser » à vivre en prenant en compte que je ne peux pas travailler autant que quelqu’un de valide.

> Mais allons plus loin, le désir de tout un chacun est de pouvoir construire un foyer, être autonome, pouvoir travailler, construire un projet, et croyez nous, nous nous battons chaque jour dans ce sens ! 

