---
title: "«AAH : Amour Argent et Hérésie»"
author: "Mathieu"
date: "2021-05-08"
categories: [aidant, amour]
---

Voilà bientôt vingt deux ans que ma femme souffre d’une scoliose multi opérée et est reconnue handicapée à plus de 80 %. Elle est sous morphiniques et antidépresseurs, et je n’ai cessé d’avoir des aumônes car je suis peut être trop riche avec un revenu de 20 000€  par an.

Je ne me plains pas car nous fréquentons beaucoup plus les hôpitaux et médecins en tout genre plutôt que les restos et les hôtels ! Les seuls voyages au long court se font en ambulance pour rejoindre un service plus pointu, dans un hôpital éloigné de chez nous.

> Personnes en bonne santé, je vous souhaite de ne jamais avoir besoin de l’AAH pour satisfaire vos besoins essentiels.

 Ma femme aimerait pouvoir disposer d’un revenu en propre. L’amour que l’on se porte mutuellement nous permet de vivre sans se plaindre, et je suis et resterai à ses côtés tant que la vie me portera et me donnera ce rôle d’aidant.