---
title: "«Mon handicap est individuel, alors pourquoi l’allocation ne l’est pas ?»"
author: "Marie"
date: "2021-05-22"
categories: [dépression, impossibilité de travailler, injustice, peur]
---

Âgée de 54 ans, je suis atteinte de polyarthrite psoriasique depuis une trentaine d’année. J’ai travaillé en m’adaptant et en diminuant peu à peu mon temps de travail. J’ai finalement renoncé, et j’ai cessé mon activité à cause de ma maladie qui progresse.

On m’a donc attribué l’AAH, mais je ne peux pas en bénéficier, je suis mariée et mon époux travaille ! Je ne comprends pas cette injustice, je ne comprends pas qu’il faille prendre en compte son salaire !

> Je ne comprends pas : mon handicap est individuel, alors pourquoi l’allocation ne l’est pas ? Je ne comprends pas qu’il faille choisir de ne pas mener une vie de couple lorsque on est en situation de handicap. Pourquoi aucune solution ? Pourquoi sommes-nous les oubliés, livrés à nous-mêmes ? 

Je me sens totalement abandonnée, inutile, déprimée, vulnérable, si seule. Je subis la maladie tous les jours, toutes les nuits, je perds jour après jour de la mobilité. Mon mari est le seul à m’aider dans la vie quotidienne et maintenant, il doit prendre en charge toutes les dépenses du foyer. Je dois établir un budget strict, je m’angoisse, j’ai peur que l’on n’arrive pas à boucler la fin du mois, je m’inquiète…

**Et si une dépense imprévue survenait ?**