---
title: "«Mon plan de carrière est en pause à cause de cette conjugalisation…»"
author: "Maxime"
date: "2021-06-14"
categories: [créance, endettement, enfants, stand-by carrière]
---

En 2003, je fais la rencontre via internet de celle qui deviendra mon épouse, elle est atteinte d’ostéogenèse imparfaite et est donc à ce titre, handicapée à plus de 90% et le restera à vie.

 Je suis Belge, elle est Française et nous vivons pendant plusieurs années une vie de couple à distance, avec des moments de retrouvailles plus ou moins long. En 2010, arrive la naissance de notre fille qui, pour chance, n’est pas atteinte du handicap de mon épouse. Nous continuerons de vivre à distance pendant 4 ans. Vu que cela devient de plus en plus compliqué, nous décidons en 2014 que je quitterai mon pays et que je viendrai m’installer en France avec elle. 

> C’est là que les problèmes ont commencé. 

Rapidement, des problèmes familiaux entre ses parents et moi font que mon épouse fait un épisode de dépression et se trompe dans le formulaire de changement de situation adressé à la CAF en datant notre installation ensemble à 6 mois en arrière. 

> La CAF nous tombe bien évidemment dessus, coupant immédiatement toutes prestations et réclamant les avis d’impositions N-2 et tout le tralala habituel sauf que pas de chance, il s’agit d’avis d’imposition belge et que la CAF n’y comprend rien…

Ils décident donc d’utiliser mon revenu brut afin d’effectuer le calcul. Et là, le couperet tombe, AAH a 0€ et indu à rembourser de 2000€, nous sommes dévastés, nos projets sont anéantis. La procédure durera plusieurs mois, durant lesquels nous habiterons à trois dans un studio de 23m², faute de pouvoir se payer plus. Durant la procédure, la CAF ne veut RIEN entendre malgré les diverses preuves apportées,  par exemple à la date indiquée par mon épouse, je ne résidais pas en France ou le fait que le traitement pris par mon épouse suite à sa dépression provoque une confusion des idées…Jamais nous n’avons été reçus, malgré nos sollicitations.La commission de recours amiable nous est refusée, sans aucun argumentaire autre que « c’est comme ça, c’est les règles ».

Le défenseur des droits, traitera notre dossier avec dédain. Un avocat sera même pris afin de contester la décision en justice, mais celui-ci nous fera faire n’importe quoi, amenant à une reconnaissance de dette, notre sort est donc scellé et un échelonnement de la créance est mis en place par la CAF.
Recevoir un courrier avec le logo de la CAF nous angoissait, mon épouse a d’ailleurs durant cette période refait des épisodes dépressifs, avec hospitalisations à la clef. Nous passerons presque deux ans dans ce studio de 23m² afin de rembourser la créance. 

> A l’heure actuelle, mon épouse a récupéré son AAH à taux plein mais au prix de plusieurs concessions et grâce à l’abattement amené par notre enfant.


Afin de faire baisser mon revenu fiscal, je suis contraint de travailler à 40km de notre domicile afin d’avoir des frais réels conséquents, ainsi que de refuser toutes heures supplémentaires.
Mon plan de carrière est en pause à cause de cette conjugalisation des revenus, heureusement mon employeur est compréhensif.
Mais que va-t-il advenir lorsque notre fille quittera le foyer ou si elle gagne sa vie en restant chez nous ?
Je crains le pire malheureusement.