---
title: "«C’est elle qui me demande de lui acheter ce dont elle a besoin, et j’ai l’impression d’être son tuteur légal»"
author: "Patricia"
date: "2021-03-23"
categories: [dépendance financière, liberté]
---

Je m’appelle Patrice, et j’ai rencontré Nathalie sur internet. Nathalie est handicapée à 80%, elle avait un travail aménagé dans un ESAT à Créteil. Elle percevait l’AAH à taux plein. Même si c’était compliqué, elle était relativement autonome. Elle allait en bus à son travail et faisait les courses pour ses enfants.

J’habite Aix en Provence, et au bout de quelques mois, on décide de vivre ensemble. Nathalie quitte tout pour s’installer avec moi. Suite à cela, comme je gagne ma vie correctement, Nathalie perd l’intégralité de son AAH et se retrouve sans ressource, complètement à ma charge.

Notre couple n’est pas à plaindre, mais…

> j’ai la désagréable sensation d’être une sorte de despote éclairé. Je dois gérer tout ce qui la concerne, les achats de ses produits essentiels (vêtements, savon, dentifrice, serviettes hygiéniques…) C’est elle qui me demande de lui acheter ce dont elle a besoin, et j’ai l’impression d’être son tuteur légal, libre d’accepter ou de refuser selon mon bon plaisir.

Des fois, sa famille lui fait des cadeaux, et elle voudrait m’inviter au restau, et je refuse qu’elle dépense le peu d’argent qu’elle a, pour moi. Mais, je déteste ce rôle. Elle devrait pouvoir faire ce qu’elle veut.

> Cela biaise notre relation, elle n’a plus aucune liberté. Ce qu’elle peut faire ou non dépend totalement de moi.

Tout cela induit une vraie relation de dépendance qui ne devrait pas exister. Et je trouve que cela impacte sa condition personnelle.

> Elle ne sort quasiment plus, elle doit me demander pour aller quelque part.  Elle a perdu toute liberté.

C’est très bien que l’État aide les personnes qui ne peuvent pas travailler. Mais ça me révolte que ce même État ajoute une condition : «vivre seul».