---
title: "«S'unir à une personne handicapée serait donc une forme de sacrifice ?»"
author: "Frédéric"
date: "2021-06-03"
categories: [20 ans enfant, compensation, divorce, impossibilité de travailler, privation, solidarité familiale]
---

Ma femme souffre d’un double handicap : une maladie rare neuromusculaire et une surdité très sévère. En comptant les 240 € d’AAH qu’elle touche, nous avons à peu près les moyens de deux personnes touchant chacune le SMIC, avec une fille qui rentre au lycée l’an prochain. Nous n’avons aucun patrimoine. Nous mangeons à notre faim, sommes locataires dans un logement chauffé, avec une petite cour. Mais ma femme vit une existence éprouvante, sans autonomie à l’extérieur (je dois prendre la voiture pour aller travailler et en avoir une 2ème nous coûtait trop cher).

> Nous n’avons pas les moyens de compenser son handicap par des aménagements vraiment confortables pour elle. Il nous faut faire très attention : presque aucun « extra ».

Le quotidien est fatiguant et stressant car elle ne sait jamais vraiment à l’avance si elle va être assez « en forme » pour aller quelque part et ses rapports sociaux sont devenus aussi rares que difficiles. Elle a du mal à faire des trajets en voiture de plus de 20 km et a dû renoncer à des choses qui lui faisaient du bien, comme des séances de piscine et de massage chez un kiné.

Les études de notre fille approchent et la situation l’inquiète beaucoup. 

> Lorsque ma fille aura 20 ans, ses études ne seront sûrement pas terminées (elle a envie d’étudier et il me semble que c’est son droit dans un pays comme la France se vante d’être) et l’AAH que touche ma compagne s’envolera, moins de 4 ans après y avoir eu droit… 

Ma femme est tellement éprouvée et inquiète qu’elle envisage de divorcer. Si cela se produit, mes revenus actuels auront un peu augmenté lorsque ma fille aura 20 ans et, avec un enfant majeur à ma charge, je payerai très peu d’impôts. Nous aurions à peu près pour deux les mêmes moyens que si nous étions toujours trois, sans parler des frais de santé en moins Mon ex-femme touchera l’AAH complète, bénéficiera de la CMU pour ses frais de santé, et pourra peut-être même participer financièrement aux études de notre fille (très peu mais c’est important symboliquement et donc psychologiquement). 

> Sinon, avoir voulu s’aimer et vivre comme une famille normale va nous plonger dans une période sûrement très incertaine, qui va peser lourd sur ma femme déjà épuisée, et sur notre fille qui montre déjà des signes d’anxiété, et qui n’avait rien demandé…

Les disputes qui éclatent souvent entre nous à cause de cette situation n’arrangent rien. Pour l’instant, le quotidien est dur pour ma femme qui, en plus des souffrances liées à ses pathologies, se sent responsable de nos difficultés, se dévalorise et n’a pas de reconnaissance sociale. Ironie du sort, sa maladie lui interdit en plus les médicaments contre la dépression et l’anxiété. La première commence à la menacer, et la seconde la ronge depuis bien longtemps… 

Une personne qui perçoit l’AAH est reconnue comme ne pouvant pas s’insérer normalement dans le monde du travail, et ce malgré sa volonté.

Doit-elle pour autant se considérer comme un poids lorsqu’elle envisage de mener une vie sentimentale et/ou familiale ? C’est ce à quoi la loi actuelle la condamne. Cette dernière fait pour l’instant fonctionner l’AAH comme un minimum social, qui condamne une personne handicapée sans ressources à la précarité (même en couple un conjoint n’est pas une valeur forcément stable) et à la dépendance. 

La seule alternative à cette précarité est de rester célibataire… Mais le handicap peut toucher à tout moment !

Lorsque j’ai rencontré ma future femme, elle n’était pas atteinte de surdité et avait un emploi en CDD. Elle ne touchait pas l’AAH car son taux d’invalidité était insuffisant. Elle avait tout fait pour continuer à travailler. Même accepté une place qui l’avait faite rechuter après une période de rémission. Nous avons eu le bonheur d’avoir une merveilleuse petite fille bien portante. Ma compagne comptait retrouver du travail lorsque notre fille entrerait à la maternelle. Mais avant que notre fille marche, on diagnostiqua à sa mère un début de surdité appelé à s’aggraver, avec nécessité de s’appareiller immédiatement des deux oreilles…

Rencontre avec une représentante de la MDPH : informations très lacunaires sur les aides financières (qu’il faut aller chercher aux forceps tous les quatre ans, durée de vie d’appareils auditifs à plus de 2000 € l’un) et tendance à minimiser les choses : « Si vous n’avez pas les moyens de vous appareiller les deux oreilles, commencez au moins par une… ». Dans le même entretien, proposition pour un emploi physique alors que la maladie de ma compagne lui interdit tout effort prolongé ou répétitif, et tout port de charge, comme l’avait spécifié un médecin du travail lors de son licenciement pour non aptitude physique… Ma femme n’a pas voulu s’appareiller et sa surdité s’est aggravée.

> Côté professionnel, malgré une reconnaissance de travailleur handicapé et un taux réévalué (mais encore inférieur à 80 %), ma compagne ne parvient pas à trouver un emploi qu’il lui est possible d’assumer.

Sa surdité complique les choses et interagit avec son autre pathologie. Nous découvrons l’existence de la pension d’invalidité mais, encore une fois mal conseillés, nous aurions dû faire une demande plus tôt après son dernier emploi pour qu’elle la touche. Plus de dix ans plus tard, nouvelle révision du taux d’invalidité, et obtention du droit à l’AAH à l’automne 2019. 

**Que dire de l’argument qui évoque une priorité de la solidarité familiale sur la solidarité nationale ? S’unir à une personne handicapée serait donc une forme de sacrifice ? Ou de charité ? Peut-être faut-il être riche pour se permettre de vivre et d’avoir des enfants avec la personne que l’on aime ? Être handicapé voudrait donc dire être un poids, être relégué aux statuts d’infirme ou d’invalide d’un autre temps ? Peut-être ne peut-on vivre et avoir des enfants avec la personne que l’on aime que si elle a les moyens de nous prendre en charge ?**

Evidemment une refonte de l’AAH représenterait une hausse des dépenses publiques alors que, selon certains, elle ne répondrait pas à un besoin urgent. Mais les allocations familiales versées sans conditions de ressources sont-elles alors une dépense vraiment nécessaire ? Si la solidarité familiale doit prendre le relais de la solidarité nationale lorsque c’est possible, est-ce que donner de l’argent à une famille ayant plusieurs enfants et quels que soient ses revenus, est une dépense juste et répondant forcément à une situation critique ? Pourquoi l’AAH de ma femme disparaîtrait-elle aux 20 ans de notre fille alors que les familles imposables (et donc en particulier celles ayant quelques moyens…) peuvent bénéficier de réductions d’impôts lorsqu’elles ont des enfants étudiants, et ce jusqu’aux 26 ans de ces derniers ?

