---
title: "«Sous le règne...»"
author: "Ghislaine"
date: "2021-05-02"
categories: [culpabilité, dépendance financière, violences conjugales]
---

Je suis atteinte d’une maladie génétique dégénérative, orpheline ne me permettant pas d’envisager une vie professionnelle. Cela fait plus de vingt ans que je suis classée dans la catégorie des 80 % et plus.

Quand j’étais célibataire, l’AAH me permettait de subvenir à mes besoins « primaires » me nourrir, me loger, payer mes factures, me soigner quelques fois, prendre soin de moi de temps en temps. 
Il y a dix-sept ans j’ai rencontré l’amour. Nous avons fait le choix de vivre ensemble car nous voulions l’un l’autre profiter des fruits de ce dernier (2 filles) ensemble. Malheureusement, j’ai très vite été rattrapée par « les lois » conditionnant l’octroie de cette allocation de subsistance qu’est l’AAH. En effet, j’ai vu mon AAH réduite à 0,00 €/mois car mon conjoint avait bénéficié d’une légère augmentation de ressources.  

> À partir de ce moment l’amour a été vaincu par les difficultés financières engendrées par la perte de cette allocation.

Aussi, ma vie n’est pas à envier. Je suis confinée depuis des années de par ma perte d’autonomie. Je n’ai pas de revenus,

> je subis des violences psychologiques et mes enfants ont honte de moi car je ne suis pas « productive ». 

**SOUS LE RÈGNE DE LA « CONJUGALISATION » DES REVENUS POUR LE CALCUL DE L’AAH, ÊTRE HANDICAPÉ(E) C’EST :**

- Une vie de couple qui vole en éclat ;
- Être dépendant physiquement et financièrement ; 
- Ne pas pouvoir subvenir à ses besoins, faire l’acquisition de matériels de compensation de handicap, adapter son logement
- Et de ce fait, subir des violences psychologiques (humiliations, reproches…) voire physiques ;
- Ne pas avoir de vie sociale ; 
- Culpabiliser.

**POURTANT :**


- Être handicapé (e) n’est pas un choix ; 
- Souffrir d’une maladie incurable, non plus ; 
- Ne pas pouvoir travailler n’est pas un choix ; 
- Perdre son autonomie et sa dignité non plus. 

**SOUS LE RÈGNE D’UNE « DÉCONJUGALISATION » DES REVENUS POUR LE CACUL DE L’AAH, ÊTRE HANDICAPÉ(E) CE SERAIT :**
      

- Pouvoir vivre dans des conditions un peu plus sereines ;
- Réduire un peu la précarité financière à défaut de la précarité physique ; 
- Redonner les moyens aux handicapés de prendre soin d’eux, de se soigner ; 
- Pouvoir sortir d’un quotidien de violences, d’isolement ; 
- Retrouver le sourire, s’extirper d’une vie de souffrances…
