---
title: "«Ce calcul [...] fait également des morts»"
author: "Arthur"
date: "2021-06-05"
categories: [décohabitation, injustice, séparation, suicide]
---

Avec mon ancienne compagne titulaire de l’AAH, nous étions ensemble depuis deux ans. Elle était atteinte de sclérose en plaques. Maladie qui ne guérit pas et qui est dégénérative.Elle est tombée enceinte en 2010 alors que nous venions d’emménager ensemble. Nous avons alors déclaré la grossesse à la CAF. 
CAF qui nous a alors demandé depuis combien de temps nous étions ensemble.

> Nous n’étions pas au courant de leur calcul et n’avions d’ailleurs aucune velléité de frauder. Nous avons donc répondu à leur demandes en toute transparence.

C’est alors que nous est tombée la nouvelle. Avec mes revenus de plus de 1500€ par mois, nous avions un trop perçu de plus de 4000€ sur seulement deux ans. Somme qui a été reportée à 2500€ suite à un courrier à la commission de recours amiable de la CAF où nous avons expliqué ne pas être au courant de ce calcul même si nous n’habitions pas à la même adresse et que notre intention n’était absolument pas de frauder. 
Quoi qu’il en soit, le calcul de l’AAH de ma compagne a été révisé de 700€ à 420€ auxquels on devait enlever 100€ par mois pour remboursement du trop perçu. Avec notre nouveau logement et la naissance de notre fille, cela faisait un trou de près de 400€ dans notre budget. Nous n’arrivions plus à payer un loyer de 800€ par mois. 
En plus, et il est important de le savoir, lorsque ma compagne était hospitalisée pendant plus d’un mois, en rapport avec sa pathologie, l’AAH ne lui était plus du tout versée.

> C’est la règle, lorsque l’on est hospitalisé, on ne touche plus l’AAH.

D’ailleurs, ayant moi même fréquenté les hôpitaux psychiatriques, j’en ai connu plus d’un qui me disait que lorsqu’il allait sortir, il se retrouverait SDF. C’est malheureusement le cas de beaucoup de patients psychiatriques qui généralement ont des longues hospitalisations. L’AAH n’est plus versée, le loyer n’est plus payé pendant plusieurs mois et le patient se retrouve expulsé. 
Je n’arrivais plus à payer le loyer et nous nous sommes finalement séparés car entre temps notre fille a été placée, vu que les services sociaux estimaient que nous n’avions pas l’équilibre moral et financier pour assumer notre enfant. 
En nous séparant, ma compagne récupérait la totalité de son AAH et pouvait désormais toucher les APL, dont nous étions privés jusqu’alors en raison de mes revenus. J’ai donc déménagé et nous avions des visites à domicile alternées avec ma fille.
Ma compagne, qui était déjà fragile psychologiquement, a été hospitalisée en psychiatrie pour une longue durée et a perdu l’appartement. Elle a mis fin à ses jours le 29 aout 2017 dans l’unité psychiatrique où elle était hospitalisée.

> Ce calcul est injuste et des plus inégalitaires ! Il ne produit pas que des pauvres ou des SDF. Il fait également des morts.

Il est temps que l’Assemblée Nationale vote pour la déconjugalisation de l’AAH pour que le peu de dignité qu’il reste aux personnes handicapées soit maintenu. Les handicapés sont suffisamment dévalorisés et, trop souvent, des pathologies somatiques débouchent sur des pathologies psychiatriques. Mésestime de soi, l’impression d’être un poids pour la société. Quels que soient les revenus du conjoint, le handicap reste le même.Pour ma part, ayant fortement pâti psychologiquement de ces évènements, je me suis retrouvé dans l’incapacité de travailler et me suis mis en invalidité catégorie II et touche désormais une pension d’invalidité qui, je tiens à le préciser, provient des caisses de la CPAM et non des caisses de l’état comme c’est le cas pour la CAF.
Je suis maintenant en couple avec une personne touchant également l’AAH et nous avons décidé d’un commun accord que nous ne pouvions pas vivre ensemble dans le même foyer. Nous avons donc chacun notre logement où nous élevons nos enfants respectifs.

> Nous aimerions bien un jour officialiser cette union par un mariage ou un PACS. Chose actuellement  non envisageable. Ma compagne ne souhaite pas perdre son AAH. 

Pour ma pension d’invalidité, c’est un droit propre, elle n’est pas soumise aux revenus du conjoint. Il serait grand temps que ce soit de même pour l’AAH.