---
title: "«Cela instaure un climat malsain au sein du couple, et prive chacun d’une grande part de liberté»"
author: "Géraldine"
date: "2021-06-03"
categories: [autonomie, dépendance financière, estime de soi]
---

Mon mari a 54 ans et perçoit l’AAH depuis quelques années.Quelle ne fut pas notre surprise en janvier quand celle-ci lui a été réduite de 220 euros par mois parce que j’ai perçu 420 euros de trop en 2019, donc 35 euros/mois ! Le calcul de la baisse de son allocation est complètement discordant.  

> Le fait de tenir compte des revenus du conjoint enlève toute reconnaissance sociale à la personne handicapée.

Alors elle ne peut même plus participer aux achats du foyer, aux vacances, à l’achat des fournitures scolaires par exemple…  Elle est réduite à néant et perd toute considération de la part du système. De plus ces personnes consomment (bien peu), payent néanmoins des taxes, achètent (péniblement) leur essence et payent leur pain et tout autre produits de consommation courante comme tout le monde et participent ainsi à l’économie du pays.

> L'estime de soi est déjà bien problématique quand on assume un handicap au quotidien, alors qu’en est-il lorsque la personne se retrouve totalement dépendante des revenus de son conjoint ?

Cela instaure un climat malsain au sein du couple, et prive chacun d’une grande part de liberté. L’autonomie des personnes atteintes d’un handicap passe par l’autonomie financière !!!
Je suis infirmière, je vois tout autour de moi des situations bien difficiles, je m’évertue à voir le bon côté des choses.

> Mais cette injustice que nous subissons au sein de mon foyer me rend très triste, et ajoute de l’aigreur là où il ne devrait y avoir que de l’amour et de la bienveillance.
