---
title: "«Mon amie et moi avons prévu de mettre fin à notre vie commune cet été"
author: "Vincent"
date: "2021-03-28"
categories: [ choix de vie, renoncement]
---

Si je n’ai pas pour habitude de parler ouvertement de mon handicap dans la vie quotidienne, en raison d’une forme de honte qui est pourtant difficilement explicable, n’en ayant pas fait le choix, j’aimerais aujourd’hui apporter ma maigre pierre à l’édifice, dans l’espoir que finisse par tomber un système injuste ayant brisé de nombreux couples.

Après une enfance « normale », j’ai été hospitalisé à l’âge de 17 ans, sans grand signe avant-coureur, alors que je poursuivais tranquillement mon chemin vers le baccalauréat. Je ne pus sortir du milieu hospitalier que 6 ans plus tard. Durant ces années, le dépôt d’un dossier à la MDPH m’a souvent été proposé, voire conseillé par les médecins. Plongé dans une sorte de déni, j’ai toujours refusé :

> qu’importe le handicap, la vie suivra son cours malgré ce « détail », sans besoin d’être étiqueté.

Bien que suivi de près, j’ai repris une vie « normale » au sortir de l’hôpital. À défaut de baccalauréat, j’ai préparé et obtenu un DAEU, me permettant par la suite de m’inscrire à la faculté. Si les efforts à fournir étaient parfois plus importants, cela ne m’a jamais empêché de réussir d’un point de vue scolaire.

Début 2020, ne bénéficiant plus d’aide financière extérieure concernant ma reprise d’étude, et ma famille n’ayant pas les moyens d’y contribuer durablement, j’ai dû, comme tant d’autres étudiants, trouver un emploi alimentaire. Toujours plein de motivation, j’ai très rapidement signé un contrat pour travailler dans une chaîne de restauration rapide bien connue. Ce fût malheureusement un échec, sur tous les plans. C’est à ce moment-là que les recommandations médicales des années précédentes ont pris tout leur sens : Non, je ne pourrai jamais mener une vie « classique » et mettre totalement de côté le handicap. Oui, j’allais avoir besoin d’aide.
À contrecœur, après des années de refus, je me suis alors résolu à déposer un dossier auprès de la MDPH. À ce moment-là, c’était ça ou abandonner l’idée de poursuivre mes études.

> Quelques mois plus tard, la MDPH a rendu un avis positif, et m’a notamment attribué l’AAH.


Si j’étais heureux de me voir proposer une solution me permettant de poursuivre mon projet scolaire, j’avais tout de même des doutes. Les pétitions concernant la désolidarisation des revenus du conjoint pour le calcul de l’AAH circulaient déjà depuis plusieurs mois, et j’ai rarement confiance dans les modes de calculs des administrations.
De plus, j’étais alors en couple depuis quelques mois, et cela m’avait déjà joué des tours devant différents organismes.
Contactée par téléphone, la CAF m’annonce que « normalement », mon amie et moi étant tous les deux étudiants, tous les revenus pris généralement en compte dans le calcul de l’AAH devraient être gelés. Je prends néanmoins rendez-vous physiquement pour quelques semaines plus tard. Entre-temps, le nouvelle tombe : la CAF m’attribue environ la moitié du montant maximal pour l’AAH. Ce montant étant, à quelques centimes près, le même que celui de ma bourse scolaire actuelle, ma situation financière ne changera donc pas. Lors de mon rendez-vous, on m’explique alors la situation :

– Le montant de votre AAH a été calculé en fonction des revenus de votre couple.
– Nous sommes deux étudiants, nous n’avons pas de revenu.
– Oui, mais le calcul s’effectue sur l’année N-2.
– D’accord. Il y a deux ans, j’étais célibataire, étudiant, et toujours sans revenu.
– Oui mais votre compagne actuelle était alors salariée, et même si vous ne la connaissiez pas, cela rentre dans le calcul.

S’en est suivi un dialogue lunaire, où l’on a tenté de m’expliquer que le système n’était pas parfait, surtout dans certains cas particulier, mais que la CAF n’y pouvait rien, que tout dépendait de la loi.

> Au final, j’ignore si j’arriverai à valider cette année scolaire, tant la situation financière génère une angoisse au quotidien. Cette demande auprès de la MDPH que j’avais tant hésité à effectuer, n’aura au final, bien qu’acceptée, rien changé à ma situation.

La conseillère de la CAF, bien qu’impuissante, est restée très sympathique et semblait aussi dégoûtée que moi par ce système qui ne tourne pas. Elle m’a confié que les seules options qui s’offraient à moi pour espérer une réévaluation à la hausse du montant de l’AAH étaient de redevenir célibataire, ou de me mettre en couple avec quelqu’un n’ayant pas travaillé ces dernières années…

> Si je n’ai pas choisi mon handicap, celui-ci m’impose aujourd’hui un choix simple : mes études, ou mon couple. Mon amie et moi avons prévu de mettre fin à notre vie commune cet été.