---
title: "«Pour le même confort de vie, le logement, la mutuelle […] me coûtent plus cher»"
author: "Fanny"
date: "2021-03-27"
categories: [confort, précarité, projets, travail]
---

Je suis fiancée à un américain. Moi handicapée neurologique (epilepsie et autre problème de santé complexe), lui psychiatrique (autisme asperger). Il travaille aux US, a un emploi adapté mais très peu qualifié, et moi à temps partiel en France.

Mon travail fait que je ne perçois que la moitié de l’AAH alors que j’aurais besoin de l’AAH complète, plus en tant que complément de salaire qu’en tant que compensation. En effet, pour le même confort de vie, le logement, la mutuelle et les problèmes de mobilité liés mon handicap me coûtent plus cher que pour une personne non malade. Le SMIC que je gagne et l’AAH sont donc insuffisants. Toute seule, je ne peux pas payer le loyer et la nourriture.

> Par conséquent, je suis hébergée en foyer, loin de mon fiancé et les règles de ce foyer m’interdisent de le voir plus d’un mois par an…

Il me manque alors que nous sommes ensemble depuis 8 ans. Mais une fois mariée avec lui, je ne sais pas ce que ce qu’il pourrait se passer. Est-ce que nos AAH pourraient se cumuler? Si nous vivons ensemble, je crains que cela soit très précaire et que cela crée des tensions.

> De plus, nos deux maladies nous demandent plus de temps pour nous adapter à la société.

Par exemple, nous rêvons de vivre à la campagne. Mais nos maladies respectives nous empêchent de conduire, donc se déplacer prend plus de temps et les logements à proximité des transports en ville coûtent plus cher.