---
title: "«Une vie bloquée sur pause»"
author: "Marie"
date: "2021-03-23"
categories: [dépendance financière, dignité, renoncement]
---

Je touche l’AAH depuis 2008, après avoir été reconnue handicapée à plus de 80% par la MDPH à la suite d’un grave accident de voiture. Je ne peux plus travailler qu’un quart de temps, je suis donc bien consciente de la chance que j’ai d’être en France et de pouvoir bénéficier de cette aide sans laquelle je ne pourrais pas vivre.
Mais au niveau vie sentimentale c’est une autre histoire :

> Je n’ai jamais pu m’installer officiellement avec un homme puisqu’à partir du moment où je vivrais sous le même toit qu’une personne du sexe
opposé gagnant 1800€ nets par mois, la CAF considérerait que c’est à cette personne de subvenir à mes besoins.

Pratique pour débuter une relation ! Tu m’aimes ? Tu es capable de voir au-delà de mon handicap et de vivre avec ? Ok, je vais vivre à tes crochets alors ! Adieu à ma dignité…

À 37 ans je n’ai donc toujours pas construit de foyer par peur de devenir complètement dépendante de mon conjoint. Je me sentirais redevable de cette personne et notre relation ne serait ni équilibrée ni heureuse.

Il est déjà difficile d’accepter d’avoir un handicap mais quand la société nous rappelle quasi-quotidiennement qu’on n’est finalement qu’un poids, c’est mission impossible. Bonne chance pour trouver le bonheur et avoir un minimum d’estime de soi !

Je rêve que l’AAH soit enfin déconjugalisée !

> Depuis que j’en dépends, j’ai l’impression que ma vie a été mise sur pause : je ne peux pas construire de famille, je ne peux pas avancer « normalement » avec un partenaire. Alors que les années, elles, défilent !