---
title: "«Je ne veux pas finir ma vie déjà écourtée par la maladie comme une mendiante»"
author: "Michèle"
date: "2021-04-09"
categories: [concubinage, contribution, dépendance financière, enfant adulte, mendier]
---

Si je témoigne c’est que depuis quelques années je suis atteinte d’un cancer du sein d’emblée métastatique, donc pas guérissable, juste soignable, ensuite j’ai développé un autre cancer, du poumon cette fois. J’étais déjà atteinte d’un lupus pour lequel on a du arrêter le traitement durant 4 ans pour des raisons d’incompatibilité avec la chimio et du coup il est en train de s’aggraver…

Depuis le début je touchais l’AAH et le complément de ressources soit un peu plus de 1100 €. Je suis en couple, mon conjoint a un salaire moyen et moi aucun revenu. Cet équilibre a changé en juillet quand mon fils a quitté la maison : on m’a supprimé le complément de ressources et une partie de l’AAH. Je ne perçois plus que 590€ et on a plus le droit à l’APL donc on doit payer notre loyer intégralement.

> Cela m’oblige à avoir recours à mon conjoint pour compléter mes revenus. Je trouve tout à fait injuste de tenir compte des revenus d’un concubin puisque dans la logique les concubins ne sont pas obligés l’un envers l’autre contrairement aux gens mariés

Il est une chose, lors du départ d’un enfant du foyer, de retirer le CR ou l’APL si l’on dépasse, mais toucher à l’AAH c’est incompréhensible ! D’autant que l’on est pas moins handicapé ou empêché de travailler du jour ou l’on se retrouve à deux.

> J’espère vivement que nos députés sauront rétablir les choses afin que nous ne terminions pas notre vie déjà écourtée par la maladie ou les handicaps comme des mendiants à la charge des autres surtout quand on a travaillé et cotisé depuis l’âge de 16 ans comme c’est mon cas.