---
title: "«Vous croyez qu’on le fait exprès de ne pas trouver de travail…?»"
author: "Hélène"
date: "2021-06-14"
categories: [accessibilité, décohabitation]
---

Je suis femme en situation de handicap, j’ai 34 ans, j’habite dans la région parisienne. Je suis atteinte d’une maladie rare depuis la naissance qui fait que je me déplace en fauteuil électrique.

> Ce que j’ai constaté depuis que je suis adolescente, c’est que la place du handicap (en tout cas en France) est la dernière roue du carrosse.

Pourtant, d’après les statistiques, on est 12 millions de personnes handicapées. 
Pourtant on est plombés encore aujourd’hui en 2021 par les problèmes d’accessibilité aux lieux publics, au logement, à l’emploi et bien sûr les problèmes de transports.
Et comme si ce n’est pas assez, il faut rajouter la prise en compte des revenus du conjoint dans le calcul de l’AAH.
Résultat : j’ai eu des occasions au cours de ma vie de me mettre en couple, mais en partie à cause de cette règle de la CAF,  je n’ai jamais pu franchir cette étape de la vie à deux.

Pourquoi je dis en partie?


Parce que  se mettre à deux, c’est habiter sous le même toit à deux. Mais quand on sait que les logements adaptés au handicap se comptent sur les doigts de la main et que ça a été renforcé par cette fichue loi ELAN; bah ça va être encore plus dur de trouver un toit accessible à nos handicaps et donc de se créer un nid douillet à deux. 
Pour être plus claire, la loi ELAN a complètement réduit mes chances moi qui habite la région parisienne de trouver un T3 accessible PMR avec 2 chambres. 
Du coup, sans trop rentrer dans les détails comme l’appartement de mon copain n’était pas accessible, j’ai alors proposé à mon amoureux de l’époque de vivre dans mon appartement accessible PMR. C’est un T2 pour commencer une vie de couple, même sans enfant on pouvait faire un essai. Mais il m’a dit que l’appartement était trop loin de son boulot, donc on s’est mis en recherche d’un appartement en vain. 
Bien sûr qu’on a trouvé des logements plus près de son boulot mais…. tous inaccessibles PMR !Aussi, je lui ai parlé de la règle de la CAF il m’a dit qu’avec son SMIC mensuel ça allait être très compliqué de vivre à deux dessus.
On a continué de se voir comme ça une fois de temps en temps et la relation s’est effilochée et ça a cassé.
J’ai rencontré d’autres hommes qui bien avant qu’on se rencontre, avait fait l’achat d’un appartement ou d’une maison. Ils m’ont montré des photos, c’était beau, c’était grand mais….. aucune d’entre elle était accessible aux PMR. Ces personnes étaient engagées dans un crédit immobilier sur plusieurs années et n’avaient aucune intention de revendre leur bien pour acheter un autre logement accessible aux PMR. Quelque part c’est normal, avant qu’on se rencontre ils vivaient leur vie comme tout le monde et ils ne s’attendaient pas forcément à sortir avec une personne handicapée. Et ils ne s’attendaient pas non plus aux contraintes qui en découlent. Et moi de mon côté je me sens mal à l’aise de leur demander de revendre le logement de leur rêve. Il faut le dire aussi, je n’ai pas les moyens de faire un quelconque achat immobilier et je n’ai pas du tout d’apport familial qui pourrait m’aider pour un achat.
Voilà la vraie vie ! Je ne sais pas sur quelle planète vivent les membres de notre gouvernement opposés à la PPL … Ils doivent vivre dans les beaux quartiers de Paris, le milieu social de haute bourgeoisie. Dans ce genre de milieu social, il est bien vu d’avoir fait les grandes écoles et de gagner un salaire mirobolant pour se payer un appartement très cossu dans les arrondissements les plus chics de Paris. 

> Et bien sûr ce genre de personne veut s’octroyer le droit de décider pour des personnes handicapées qui vivent de l’aide sociale dont l’AAH et par le même coup de nous expliquer comment il faut vivre notre vie de couple.


Les opposants semblent être complètement à côté de la plaque, ils veulent absolument calquer leur propre grille de salaire de parlementaire plus les primes qui vont avec sur celui des travailleurs dit du « peuple ». Quelqu’un qui débute sa carrière elle gagne au maximum 1400-1500€.

**Vous croyez qu’un conjoint valide peut entretenir sa femme handicapée avec un tel salaire en région parisienne ? Vous pensez vraiment que c’est le but de la femme handicapée de se faire entretenir par son conjoint comme c’était le cas pour les femmes dans les années 40-50 et même bien avant ? Vous croyez qu’on le fait exprès de ne pas trouver de travail et que ça nous fait plaisir de toucher que l’AAH ?**  