---
title: "«C’est terrible de devoir faire le choix de la dépendance financière»"
author: "Marion"
date: "2021-03-29"
categories: [choix de vie, dépendance financière, droits]
---

J’ai 33 ans, atteinte de multiples pathologies rares, avec handicap moteur des jambes, reconnue à 80% de handicap depuis peu. Je vis seule à Paris. Mon copain et ma famille vivant à Nantes. 

Je viens d’arriver à bout de 3 ans d’arrêt maladie, 3 ans acharnés médicalement, un parcours pas encore fini et si rude, 3 ans de survie à Paris, 3 ans également de bataille pour être reconnue et gagner

> mes droits qui, à peine obtenus, seront bientôt bafoués à nouveau. 

Parce qu’après 3 ans, mes droits à l’arrêt maladie épuisés, je suis désormais en invalidité et sous AAH, et vais pouvoir enfin retrouver la liberté de quitter mon logement parisien inadapté à mon handicap lourd, et déménager en province chez mon copain pour espérer vivre mieux dans un cadre plus adapté à ma santé, mais cela a un prix fort… 

> C’est terrible de devoir faire le choix de la dépendance financière envers son partenaire pour simplement avoir le droit d’avancer à deux et vivre sous le même toit (pas besoin d’être mariés ou pacsés, il suffit de partager le même logement) ! 

Concrètement, les chiffres parlent plus que les mots : 
Le plafond de revenus à DEUX à partir duquel l’AAH est amputée, est de 1600 euros nets par mois seulement ! Dans mon cas, dès que je vivrai avec mon copain sous le même toit, ce sera une perte minimale de 500 euros par mois sur les 900 de l’Allocation Adulte Handicapée (droit à peine obtenu et unique ressource)… Imaginez vous vivre avec 400 euros (dans lesquels il faut inclure des frais médicaux conséquents) simplement parce que vous avez une incapacité de travailler et un désir d’enfin pouvoir vivre mieux à deux… 

> C’est ça le prix de l’amour ? Quand on est en situation de handicap lourd aujourd’hui en France ? Il est vital que ça change ! 