---
title: "«Merci de détruire nos rêves, merci de détruire nos vies, merci de détruire notre amour !»"
author: "Rémi"
date: "2021-05-08"
categories: [impossibilité de travailler, perte de revenus, rêves]
---

Je touche  l’AAH suite à un accident grave de parapente, des douleurs quotidiennes m’empêchant de tenir une position statique assise/debout/couché plus d’une heure et beaucoup d’antidouleur de palier 3 m’empêchant de me concentrer, donc impossible de travailler dans ces conditions. Avant de décider de nous mettre en couple, j’ai appelé la CAF pour savoir combien je perdrais d’AAH, ils n’ont JAMAIS VOULU ME DONNER CETTE INFORMATION ! 

> Leur réponse : « Ce n’est pas le montant de vos aides qui doit décider de votre situation familiale ».

Durant 2 mois j’ai téléphoné, fait des mails, des courriers y compris à la CNAF (Caisse nationale des allocations familiales) et je n’ai jamais eu de réponse !

Nous avons alors décidé d’avancer malgré tout, par amour et à cause de mon état de santé qui se dégrade… La suite vous la connaissez, la CAF supprime totalement mon AAH car mon amie touche 200€ de trop par rapport au plafond annuel ridiculement bas de 19 650€ pour 2. Nous nous étions pacsés, avons signé chez le notaire pour l’achat d’une maison en commun, revendu nos 2 maisons, et tout cela doit être annulé à cause de la CAF, c’est réellement la descente aux enfers !

> Nous perdons tout, mais nous n’avons pas le choix. Soit nous perdons tout, soit on nous supprime tout… C’est ça le système de l’AAH…

Je n’ai pas de mots assez forts pour exprimer ma tristesse, mon dégout…
Résumé d’échanges avec la CAF au sujet de l’AAH :    

– Moi : « Bonjour, je suis titulaire de l’AAH, mais mon état de santé s’aggravant, les taches de la vie quotidienne sont très difficiles, mon amie étant infirmière, pour m’aider et bien sûr, par amour, nous avons pris la décision de vivre ensemble à partir d’aout 2021, nous vendons nos 2 maisons pour en acheter une en commun à cette adresse : *****. »
– Réponse de la CAF : « Nous avons bien pris note de votre changement de situation et aux vues des revenus de votre compagne,

> nous vous supprimons immédiatement et totalement votre AAH

et comme vous êtes pacsés le mois dernier, vous nous devez 1804€ (AAH Mai/juin) »
– Moi : « Merci de ne pas avoir voulu me le dire dit quand j’ai téléphoné pour avoir cette précieuse information ! Ne pouvant pas travailler, je ne peux donc plus payer mes médicaments, mes consultations au médecin (car je n’ai pas de mutuelle et pas les moyens d’en avoir une, (car étant à l’AAH visiblement je gagne « TROP » pour avoir la CMU), plus payer ma nourriture, donc à part aller faire la manche dans la rue, nous sommes donc dans l’obligation de revendre notre maison alors que nous n’avons même pas encore emménagé pour vivre à nouveau séparément ! (et avoir perdu beaucoup d’argent entre temps !)

Merci de détruire nos rêves, merci de détruire nos vies, merci de détruire notre amour ! Et ça dit être un organisme « SOCIAL » ?! Je ne vois aucune humanité dans cela… Quelle honte…