---
title: "«Handicap donc dépendance et dépendance financière»"
author: "Sylvie"
date: "2021-06-03"
categories: [colère, dépendance financière, double peine, ESAT, injustice]
---

Le système aujourd’hui est très mal construit et mon mari en fait les frais depuis des années maintenant. 


J’ai rencontré mon mari il y a 18 ans, nous nous sommes rencontrés jeunes, il était déjà bénéficiaire de l’AAH. Il est atteint d’une maladie psychique dont il ne guérira jamais, mais qui est stabilisée grâce à la prise de médicaments et d’un bon suivi psychiatrique. A l’époque, il travaillait dans un CAT. 
Nous n’avons jamais triché dans nos déclarations, nous nous sommes toujours déclarés vivre ensemble. Bien sûr nous avons rapidement pris conscience que mon salaire qui augmentait faisait progressivement diminuer son AAH. Nous avons depuis eu 2 enfants. Mon mari est rentré dans le milieu ordinaire, puis après plusieurs rechutes, il est finalement retourné travailler en ESAT en 2013. De mon côté j’ai une bonne place en tant que salariée. 

> L'année prochaine, nous dépasserons le plafond de revenus en couple avec enfants et mon mari ne touchera plus aucune AAH. Mon salaire a évolué.


Il y a plusieurs injustices :     

Notre niveau de revenu ne bouge quasiment pas puisque quasiment tout ce que je gagne en plus, il le perd 2 ans plus tard sur son AAH. 
En fournissant le même travail que ses collègues en ESAT, sur 35 heures par semaine et 25 jours de congé par an comme tout salarié du privé, il ne touche que 715€ net par mois!  Et l’année prochaine 0€ d’AAH en complément pour la simple et bonne ou mauvaise raison qu’il est amoureux et marié ! Ses collègues touchent jusqu’à 1300€ salaire de l’Esat et AAH cumulés puisqu’ils sont eux pour la plupart célibataires. Ils font le même travail !!! 
715€ net pour 35h : nos élus trouvent ça normal ? Quelle raison valable donne le droit à l’Etat de décider qu’un salaire d’un travail fourni doit dépendre de la rémunération du conjoint ? Aucune !!! 
Je finis ce témoignage un peu, voire très en colère ! Cela fait des années que je me bats pour cette cause et rien n’avance. Enfin, en 2020 nous avons eu une lueur d’espoir : une loi pourrait enfin permettre aux bénéficiaires de l’ AAH de retrouver un peu de dignité.

> Je suis convaincue que ce vote du mois de juin pourrait être décisif et rendrait enfin justice à cette double peine : handicap donc dépendance et dépendance financière. S’il vous plaît mesdames et messieurs les députés, je vous en conjure, votez pour la déconjugalisation de l’AAH. 

Bravo à toutes et tous pour ce combat si évident à mes yeux. 