---
title: "«Comment vivre avec 271 € par mois ?»"
author: "Marie"
date: "2021-05-02"
categories: [20 ans enfant, déshumanisation, fardeau]
---

J’ai 40 ans et je souffre d’une maladie auto-immune depuis plus de 10 ans, la spondylarthrite ankylosante. Je vis avec mon compagnon, fonctionnaire qui gagne 1540€ par mois et sa fille de tout juste 20 ans. Mon AAH est renouvelée tous les deux ans et calculée à hauteur du salaire de mon compagnon soit 722€ par mois depuis 5 ans.

Il y a quelques jours, j’ai consulté mon compte CAF pour vérifier que mon renouvellement était bien pris en compte.

> Quelle déconvenue ! Mon AAH a eu une baisse et perte sèche de 450€ par mois.

**Motif : les 20 ans de la fille de mon compagnon**, alors qu’elle s’apprête à rentrer dans les grandes écoles (Sciences Po). Cette nouvelle est une hécatombe et nous remuons ciel et terre pour qu’elle puisse continuer ses études après ses 2 ans de Khâgne !

Comment puis-je vivre décemment avec une allocation très, très, en dessous du seuil de pauvreté ? Comment vivre avec 271€ par mois ?

> Déjà que j’ai l’impression d’être un poids pour la société mais en plus maintenant pour ma propre famille !

Déjà le handicap, la maladie, les traitements lourds, les méthodes alternatives non remboursées par la sécu et maintenant l’argent…

**L’État semble déshumaniser les plus pauvres d’entre nous mais surtout les plus faibles.**