---
title: "«Je ne veux pas que ma fille handicapée vive la même dépendance que moi»"
author: "Martine"
date: "2021-03-23"
categories: [courage, dépendance financière, fierté, impossibilité de travailler, liberté, prisonnière, renoncement, souffrance]
---

Bonjour, je m’appelle Martine. J’ai 59 ans, je suis reconnue travailleur handicapé entre 50 et 80 %. Je suis éligible à l’AAH, mais, mariée, mon mari a une retraire de 2300 euros donc je ne touche absolument rien. Sachant que si l’on regarde bien cela fait 1150 euros chacun en divisant par deux sa retraite, donc même pas un SMIC. Mais je ne peux pas calculer comme ça, car cet argent c’est le sien et pas le mien. Il doit donc m’entretenir et subvenir à mes besoins qui ne sont pas forcément les mêmes pour lui et moi.

> Je n’ai pas la possibilité d’être indépendante et autonome dans ma vie et je me sens comme les femmes des années 50 et 60 qui n’avaient aucun droit sans leurs maris !

Il y a certainement des gens que ça ne gêne pas. Pour moi c’est une souffrance. Je me sens prisonnière de mes maladies et de mon handicap et prisonnière de ma dépendance financière, double peine.

Faute d’avoir mon propre argent je n’ai qu’un forfait téléphone à 2 euros et une carte de retrait seulement à ma banque, pas de carte de payement par dignité de ne pas demander. J’ai tout pris au moins cher, voilà ce que ça donne d’être dépendante. Demander pour ci, demander pour ça, je ne supporte pas et je préfère ne pas demander c’est pour moi une fierté et une liberté. Heureusement que je ne suis pas une femme battue ou soumise, elles doivent vivre un calvaire encore plus que moi.

J’ai commencé à travailler à 16 ans après mon BEPC dans la boulangerie familiale, mon parcours de travail s’est achevé par la naissance de mes trois enfants et je n’ai donc pas assez de trimestres pour prétendre à la retraite anticipée. Si je pouvais travailler comme avant, je ne demande que ça et donne volontiers mon handicap. Je suis courageuse. J’ai fait des ménages et j’ai été ASH en maison de retraite, des métiers physiques qui ont été le déclenchement d’une opération de hernie discale, fibromyalgie, centre anti-douleur, opération du cœur il y a trois ans et je suis encore sous traitement, hypertension, et les médocs qui me détruisent les intestins.

> J’ai tenté de reprendre le travail à temps plein après mes opérations du dos, mais c’était impossible. Je n’ai pas d’autre choix que d’avoir l’AAH.

Ma dernière fille est elle aussi handicapée, une maladie de naissance génétique et orpheline. Assumer le handicap de son enfant est un parcours qui n’est pas du tout facile : la paperasse, les RDV médicaux, quand on espère enfin trouver le bon médecin et on doit répéter les mêmes choses des centaines de fois avec son enfant à ses côtés, qui aussi les vit et revit ces moments. La mise en place des besoins spéciaux à l’école, et l’administration… la bataille avec la MDPH quand l’enfant passe à l’âge adulte et comme si cela faisait disparaître sa maladie… une hérésie… une bataille de tous les jours.

> Finalement ma fille travaille en tant qu’handicapée, avec des adaptations, elle vit seule et la réflexion de sa vie amoureuse et de couple est marquée par cette non individualisation de l’AAH.

Je me bats donc aussi pour elle et toutes et tous ces jeunes qui j’espère verront les choses changer dès maintenant !