---
title: "«Renoncer à l’amour pour continuer à élever ses enfants»"
author: "Carole"
date: "2021-03-23"
categories: [décohabitation, renoncement]
---

Je suis comme ils disent : une handicapée invisible. Ma fille de 19 ans est mon aidante quand elle n’est pas à son service civique. Deux fois par semaine, une personne vient pour aider au ménage. J’ai aussi un fils de 12 ans, en situation de handicap, qui est scolarisé en classe ULIS. La semaine, mon fils vit en famille d’accueil, et le week-end avec moi. Aujourd’hui, l’homme avec qui j’aimerais partager ma vie vit à 600 km de chez moi. Je renonce à vivre en couple avec lui car je ne toucherai plus d’AAH et d’AEH pour mon fils, ainsi que les pensions alimentaires pour mes enfants données par la CAF.

> Je refuse donc de vivre avec lui pour ne pas avoir à quémander telle une mendiante de l’argent pour continuer d’élever mes enfants.

Souffrant de cette injustice, j’aimerai pourtant vivre l’amour ! Dieu sait que j’aurais besoin de quelqu’un au quotidien.