---
title: "«Je veux pouvoir vivre avec le père de mon enfant !»"
author: "Alexia"
date: "2021-05-22"
categories: [fardeau, peur, projets]
---

Aujourd’hui je vous ouvre mon cœur, je n’ai jamais témoigné jusque là. Je suis une personne handicapée et ça n’a jamais été facile, mon physique ne le montre pas forcément. Il n’y a que quand on commence à discuter avec moi qu’on se rend compte qu’il y a quelque chose… J’ai plusieurs handicaps, ça n’a jamais été facile pour moi d’être différente. J’en souffre au quotidien. J’ai des douleurs régulières, il est très rare que j’aille bien. Je n’avais jamais spécialement pensé à me mettre en couple, ma vie me suffisait.

> Mais il y a quelques mois, je suis tombée enceinte, et là tout a changé !

Je me suis rendue compte qu’en m’installant avec Monsieur, j’allais perdre pratiquement toute mon AAH. Je veux pouvoir vivre avec le père de mon enfant ! C’est prévu qu’ à la naissance du bébé on s’installe ensemble. Mais j’ai vraiment peur du futur ! Monsieur est endetté et s’en sort vraiment de justesse.Ce sera son salaire qui sera pris en compte, et pas ce qu’il lui reste réellement après avoir payer tout ce qu’il doit ! Et moi j’y perds énormément ! A 3, ça sera très très dur ! On aura très peu pour vivre, je ne sais même pas si notre couple pourra tenir avec aussi peu pour vivre avec un enfant ! Il y a une part de lui qui est embêté par ma situation, et je sais qu’il préférerait avoir une femme en bonne santé et qui travaille !

> Déjà qu’au quotidien, je ne suis pas facile à vivre à cause de mes handicaps, en plus il y a ce souci d’ AAH supprimée si on a le malheur de se mettre en couple ! J’ai honte, je souffre … Oui j’ai déjà pensé à quitter ce monde car j’ai l’impression d’être un boulet !

J’ai énormément de peine quand je vois comme les personnes handicapées sont traitées. Il faut que les lois changent ! Un peu de solidarité avec les personnes malades ! Par pitié, notre AAH ce n’est pas grand chose, laissez nous la ! Trouver l’amour n’est pas facile pour une personne handicapée. Ce n’est pas tout le monde qui veut quelqu’un de malade à ses côtés, tout le monde n’a les épaules pour et en plus, on nous coupe les vivres ! Notre destin est il de mourir seul(e) ?

> Mon Dieu, par pitié, arrêtez de comparer l’AAH avec le RSA ! C’est sincèrement douloureux pour les personnes handicapées cette comparaison ! Le RSA n’est pas une aide donnée juste durant le temps de retrouver du travail ? Pourquoi est-ce à chaque fois comparé avec nous, personnes malades ?! J’ai mal au cœur, j’espère que nous serons entendus …
