---
title: "«Nous avons donc choisi, à la trentaine, de vivre notre amour comme deux adolescents…»"
author: "Richard"
date: "2021-03-26"
categories: [choix de vie, dépendance financière, projets, SOS]
---

Je suis un homme de 31 ans, en couple depuis bientôt 4 ans avec une personne de 28 ans bénéficiaire de l’AAH atteinte d’une myopathie.

> Nous vivons notre amour de manière singulière,

et ce, même en occultant le handicap de ma compagne, j’aime dire que nous sommes des originaux ou mieux des marginaux. Ne pouvant pas travailler à cause de sa maladie,

> elle est contrainte de vivre chez ses parents,

non pas qu’ils soient mauvais, loin de là, je les adore.

Mais cette contrainte est bien présente en raison de la privation de liberté de pouvoir choisir de vivre avec moi. Pourquoi ? Parce que l’aide appelée AAH est solidaire des revenus de tout conjoint éventuel ou même de la famille.

> Le handicap est individuel mais l’allocation associée est solidaire, totalement fou.

Il paraît que je gagne trop bien ma vie ! Je ne pensais pas le dire un jour avec autant de tristesse mais mon salaire est trop élevé pour que ma chérie conserve son AAH. En effet, selon les dires, en France, lorsque vous percevez environ 1700 euros de salaire, vous ne pouvez pas prétendre à une vie normale avec une personne que vous aimez, du moment que celle-ci perçoit l’AAH. Ces mêmes 1700 euros seraient le seul et unique revenu de notre foyer, privant de nouveau la femme que j’aime de la liberté de choisir d’être indépendante.

> Je ne veux pas la faire souffrir et nous avons donc choisi, à la trentaine, de vivre notre amour comme deux adolescents…

Les weekends, lorsque c’est possible, elle fait sa valise et me rejoint dans mon petit T2. Nous passons un bon moment et le dimanche soir, elle retourne vivre dans sa chambre de 12 m², oui 12m², est-ce épanouissant de vivre seule la journée et de n’avoir comme intimité qu’une simple pièce ? Je ne crois pas.

> Nous aimerions construire notre futur et évoquer des projets, mais le couperet tombe à chaque fois qu’une « union » quelle qu’elle soit doit exister car au-delà de l’amour, c’est tout un confort de vie qui disparaîtrait et il n’en est pas question.

J’appelle le gouvernement français à comprendre un peu plus ce que vivent des milliers de couples comme le nôtre, qui n’osent pas franchir le pas à cause d’un revenu conditionné, un pays qui prône la Liberté, l’Égalité et la Fraternité doit tenir compte du

> SOS général lancé par toute cette population qui ne demande qu’à vivre comme les autres et à pouvoir aimer comme les autres.