---
title: "«Je suis un citoyen de la République Française oublié...»"
author: "Olivier"
date: "2021-05-08"
categories: [culpabilité, épuisement, impossibilité de travailler, révolte, souffrance, suicide]
---

J’ai 50 ans, en couple. Je suis handicapé à 80 % depuis 1997, je touchais l’ AAH. Mais depuis 10 ans, la CAF ne me la verse plus à cause du revenu de ma conjointe au SMIC ! (et pas 2500 € mensuels comme annoncé par la secrétaire d’Etat chargée au Handicap).

Je souffre d’une maladie génétique orpheline incurable et dégénérative. Cela fait 24 ans maintenant, plusieurs fois opéré, de nombreux médicaments pour me tenir en vie et soulager des douleurs. De nombreux examens à l’hôpital, mais pas n’importe lequel. Des heures de route pour aller à l’hôpital sur Paris (car à la campagne il n’y a pas assez de médecin, et très peu d’hôpitaux spécialisés). 

> J’ai rencontré l’amour d’une femme, qui m’accepte et qui me soutient tous les jours. Elle vit le handicap avec moi, sans peur, sans me quitter comme je l’ai vécu par le passé.

Il y a 10 ans, nous avons voulu un enfant et après de nombreux essais, bonne nouvelle, elle est enceinte. Mais tragiquement, Ilona est morte née. Je ne m’en suis jamais remis. S’en est suivie une grave dépression.

Voilà ce qu’est notre triste vie. Pour subvenir à nos besoins, ma femme valide fait des heures supplémentaires comme une acharnée. Quand je la vois à mes côtés, c’est pour dormir, j’en peux plus. Elle me comprend, mais parfois elle en a marre ! Elle est fatiguée de cette situation, elle m’en veut et je m’en veux.

> Je lui ai même proposé de divorcer afin de tricher comme beaucoup d’autres couples. Je pourrais  retoucher mon AAH dont j’ai le droit. Elle a refusé,  étant trop honnête et gentille.

 Alors je travaille, des petits boulots en intérim… J’en paye physiquement le prix ensuite.  Puis j’enchaine des CDD jusqu’à ce que l’employeur ne reconduise pas le contrat pour inaptitude au travail. Bien oui ! Je suis handicapé à 80 % . Je devrais pouvoir toucher l’AAH ! S’en suivirent d’autres boulots précaires et épuisants. Puis j’ai réussi a être titularisé pour un travail ! J’ai posé des arrêts maladie, puis un accident de voiture du à la fatigue. Maintenant je suis en arrêt.

Les collègues me reprochent que je suis différent, ne veulent pas croire que je suis handicapé.

Mais maintenant que je suis titulaire, la direction cherche une solution pour me virer. On m’envoie voir l’assistante sociale. Elle me dit que vu mon état de santé, je devrais  toucher l’AAH ! QUELLE IRONIE ! Je n’ai pas d’AAH puisque les revenus de ma femme sont trop élevés ! Au SMIC !

Conclusion : dans 9 mois je serai licencié, sans salaire, et toujours sans mon AAH, pourtant accordée par la MDPH depuis 1997.

J’espère que le 17 juin, la loi sera votée pour qu’on ne prenne plus en compte les revenus du conjoint.
J’appauvris ma femme, j’ai fait plusieurs tentatives de suicide.

Manifester ça sert à rien , les courriers au gouvernement ne servent à rien, certains ne répondent même pas. Sans parler de l’hypocrisie de ceux qui sont nommés pour nous représenter et améliorer notre situation en France. Sur les groupes Facebook, certains font la grève de la faim mettant leur vie en danger,  mais rien ne bouge . 

> Nous sommes laissés pour compte en 2021. Nous sommes le pays des droits de l’Homme. Je suis un citoyen de la République Française oublié, je suis révolté ! 