---
title: "«Je suis outrée d’entendre parler de solidarité familiale...»"
author: "Sylvie"
date: "2021-05-08"
categories: [budget, colère, dépendance financière, solidarité familiale, suicide]
---

J’ai 50 ans, handicapée depuis l’âge de 27 ans : une rupture d’anévrisme, provoquée par les coups de mon conjoint. J’étais une femme battue et un caillou s’est formé sans que je le sache. Je suis partie avec mes deux enfants, j’étais aide soignante à domicile.

Mes parents ont tout fait : les démarches pour l’AAH et la pension d’invalidité. 890€ mensuels pendant des années, avec deux enfants ! Pas le droit à d’autres aides. Aujourd’hui, je suis mariée depuis 2016.  Mon AAH est maintenant de 375€  au lieu de 690€ . Mon mari est retraité, il a 1180€. Ce n’est pas la joie, je dépends de mon mari.

Loyer 490€,
EDF 135€,
Eau 45€,
Prêt  250€,
Assurance 300€,
Mutuelle 290€,
Téléphone internet 45€,
Bracelet d’assistance SOS 63 € (que je vais devoir rendre faute d’argent).
Nous vivons chaque mois à découvert, et c’est de pire en pire.

Moi, je n’ai pas demandé à être handicapée et je suis outrée d’entendre parler de solidarité familiale : on dépend de mari, enfants, parents comme le dit la Secrétaire d’Etat en charge du Handicap.

> Je ne divorcerai jamais même si la loi ne passe pas car j’ai un mari en or. Je ne prendrai plus mon traitement, je mettrai fin à ma vie, je souffre trop et j’ai bien compris que je ne manquerai pas à l’État .

Je suis tétraplégique gauche, aphasique, j’ai perdu ma mémoire épisodique, j’ai eu un double cancer du colon de graves problèmes de thyroïde. Sans compter les AVC.  Donc la mort ne me fait pas peur !

> Aujourd’hui  je suis très en colère, je n’ai plus de dignité, je n’ai plus d’aide humaine ! C’est mon mari qui s’occupe de tout ! Malgré son âge et ses propres problèmes de santé.

Nous sommes les oubliés de la France ! J’espère que vous m’avez compris et que la loi passera. Car, sinon, cela aura des conséquences dramatiques.