---
title: "«Vivre est réservé à ceux qui travaillent !»"
author: "Aude"
date: "2021-04-13"
categories: [colère, dignité, patriarcat, renoncement au couple, souffrance]
---

Je suis en colère ce matin. Je ne comprendrai jamais pourquoi, chez un couple lambda qui travaille, on ne leur supprime pas l’un des deux salaires ! Parce qu’au fond c’est ce qu’ils font avec nous ! À moins que l’État considère que le handicap, c’est la belle vie et l’AAH de l’argent de poche…

**Je ne comprendrai jamais leurs arguments alors je vais faire une mise au point.**

Mon handicap, c’est un traitement très lourd contre la douleur qui n’est pas magique. Il ne me permet pas de marcher, de danser, de faire la fête, d’utiliser mon temps libre volé à la société pour vivre la belle vie. À cause de lui je dors 15h par jour pour une efficacité qui est loin d’être miraculeuse. La douleur est toujours là en permanence, 40/10 en période de crise neuropathiques et cela depuis 13 ans sans une journée de répit. J’ai deux heures de kiné à domicile par semaine + une heure d’activité physique adaptée par jour (ça c’est moi qui me l’impose pour ne pas me laisser rouiller par l’arthrose). Une psychologue tous les jeudis. Un infirmier tous les jours sans compter les rendez-vous à l’hôpital. 
Je ne me fais aucune illusion, je mourrai jeune. Le traitement que je prends est dangereux pour le cœur, affecte ma mémoire et mes problèmes d’équilibre peuvent entraîner un accident domestique à chaque instant. J’ai subi une sleeve pour que ma vie alitée ne me fasse pas prendre trop de poids. J’ai décidé ça le jour où je suis arrivée à 124 kg. Aujourd’hui je stagne autour de 100kg et surtout je ne grossis plus. Je dois me satisfaire de ça.

Avant l’erreur médicale qui m’a clouée au lit et parfois dans un fauteuil, j’avais une magnifique fille de 17 ans qui s’est suicidée alors que j’étais à l’hôpital. J’avais un boulot de rêve, je pesais 80 kg et j’avais un amant et des tas d’amis. Cette vie a entièrement disparue. Est-ce que c’est ce que je souhaitais ? Traîner au lit toute la journée devant la télé ? Évidemment que non. C’est à devenir folle.

> Ma chambre est au rez-de-chaussée de mon immeuble. La fenêtre de ma chambre donne directement sur un parking, dès que j’ouvre ma fenêtre je respire les gaz d’échappement. Les voitures sont comme garées dans ma chambre, je peux les toucher de ma fenêtre. Je suis devenue asthmatique. Et ils appellent ça un appartement adapté.

Il n’y a aucun moyen d’y faire entrer mon fauteuil électrique pour le charger sans condamner l’accès à la salle de bain! Les courses : 10€ par semaine de frais de livraison, parce que par temps de pandémie je ne mettrai pas les pieds dans un supermarché et moi, les petits commerçants, je n’ai pas les moyens. Petit rappel : je vis avec 903,40€ par mois. Je paye 123 € d’électricité sans chauffer même l’hiver. 165€ de loyer (Caf déduite), 121€ d’assurance voiture. Sans compter la box, l’eau, le carburant, le téléphone portable, quelques vêtements bon marché une fois par an et bien sûr l’alimentaire, les produits d’entretien, d’hygiène et la literie que je dois changer tous les ans (eh oui quand on passe sa vie alitée).
Être handicapée c’est avoir mal en permanence, toujours entourée de personnels médical, une assistante de vie tous les jours, les amis qui s’éloignent ou vous reprochent votre condition sans même s’en rendre compte (où qu’on aille il faut que ce soit accessible, c’est pénible), une vie sociale réduite à néant, l’angoisse de mourir seule chez moi, l’angoisse que la machine à laver tombe en panne, et pour couronner le tout, aucune chance de rêver à une vie commune. Pas folle la guêpe la maltraitance en couple, j’ai connu, plus jamais ! Ce seul petit espoir, on me l’a retiré des mains avec des arguments indignes, des arguments qui ont plus de 40 ans ! J’en ai marre, là je craque. 

> Si on me laissait mon AAH en couple, je serais maîtresse de ma vie comme aujourd’hui, à cette différence près que je me sentirais le droit de tomber amoureuse.

Pour le moment et jusqu’à ce que les choses changent, que les vieilles lois patriarcales de 45 ans d’âge ne m’obligent pas à accepter l’inacceptable en 2021, jamais je ne deviendrai dépendante d’un homme de toutes les façons possibles.

> Vous m’avez eu ! J’ai plus la force de me battre contre vous. De l’énergie, j’en ai juste assez pour survivre ! Vous vous êtes permis de toucher à mon espoir de vivre !

Voilà ce que le gouvernement veut que l’on comprenne ? 
*« Madame, survivez, ne vivez pas, vivre est réservé à ceux qui travaillent, à ceux qui ne souffrent pas ou pas assez pour ne plus pouvoir travailler ! Vous, vous pesez lourd sur la société, vous ne lui servez à rien, pourquoi on vous donnerait de quoi avoir le droit, la possibilité d’être heureuse ? »*

Ça coûterait si peu cher de rendre la dignité aux 200 000 handicapés en couple. Ça vous coûterait quoi de nous donner le droit au rêve au delà de la souffrance et du travail à temps plein, jour et nuit qu’est le handicap.

**Vous rendez-vous compte qu’on vous demande le droit de vivre ?**

