---
title: "«Aujourd’hui je demande que la loi passe, pour que je retrouve ma liberté, ma dignité et mon autonomie financière»"
author: "Pauline"
date: "2021-03-23"
categories: [dépendance financière, dignité, disputes, double peine, liberté]
---

Je me présente Pauline 26 ans, je suis atteinte d’un handicap moteur de naissance.

Aujourd’hui,

> malgré ma détermination et mon acharnement pour trouver un emploi dans mon domaine, rien n’y fait,

sauf quand je ne mentionne pas que j’ai une RQTH*, je ne suis pas prise en entretien. Mais voilà, mon handicap reste visible et je ne peux le cacher bien longtemps. 

Je fais face à beaucoup de préjugés et pour trouver un emploi, c’est compliqué.

Aujourd’hui, malgré mon BTS, je me suis résignée à faire une demande à la MDPH pour travailler en ESAT** : pour pouvoir avoir une chance de ne dépendre financièrement de personne. Malheureusement, le temps d’attente est très long pour avoir un poste de travail en ESAT.

Aujourd’hui, je vis en concubinage avec mon ami depuis septembre 2018. J’étais très heureuse, car la MDPH venait à cette époque, après un long combat, d’accepter ma demande d’AAH : Nous pouvions enfin vivre ensemble !

> Sauf que du jour au lendemain, j’ai vu mon AAH fondre comme neige au soleil et aujourd’hui je me retrouve quasiment dépendante de lui, ce qui entraîne de nombreuses disputes. Je trouve ça injuste car mon handicap, il ne devrait pas le subir.

Aujourd’hui je demande que la loi passe, pour que je retrouve ma liberté, ma dignité et mon autonomie financière.