---
title: "«Évitons une dépendance supplémentaire de la personne handicapée»"
author: "Melaine"
date: "2021-03-27"
categories: [dépendance, pauvreté]
---

Je partage mon expérience avec vous. Je m’appelle Mélaine et je suis mariée depuis un an à un homme formidable Romy, handicapé à 90% . À notre plus grande surprise il a perdu dans la foulée 500€ de son AAH car je perçois 1600€ de salaire ce qui est pour les organismes « trop de salaire ». Or nous n’habitions même pas sous le même toit par faute de trouver un logement adapté à sa situation de handicap.

> Du coup deux loyers et toutes les factures en doubles plus la nourriture sur un seul salaire pendant plusieurs mois, malgré des demande de recours exceptionnel mais refusé dans le cadre de la « législation « .

Ce jour nous avons enfin un toit commun avec un loyer de 860€ hors charge et malheureusement pas d’aide au logement car je perçois trop de salaire et mon mari perçois 434€ d’AAH .

> Si demain il m’arrive quoique ce soit ou si je perds mon emploi nous nous retrouverions dans l’impossibilité de payer notre loyer ainsi que de nous nourrir.

Il est nécessaire et indispensable de dissocier les revenus pour éviter une dépendance supplémentaire de la personne handicapée. Cela simplifierait les projets de vie de couples et permettrait qu’une vraie chance de vivre une vie la plus normale possible soit donnée à chaque citoyen.