---
title: "«Depuis presque 4 ans, je ne touche plus que 590 euros car mon mari touche apparemment trop»"
author: "Sonia"
date: "2021-03-23"
categories: [perte de revenus, stress]
---

Je m’appelle Sonia, je suis porteuse d’une maladie génétique rare et héréditaire nommée le syndrome de Marfan. Elle est très invalidante puisqu’à seulement 45 ans,  j’ai déjà subi 2 opérations à coeur ouvert et 11 opérations des yeux ! Ma maman m’a donné ce cadeau empoisonné bien malgré elle et j’ai donc dû grandir avec la peur de ce qui allait bien pouvoir m’arriver et surtout cette peur de mourir qui ne me quitte jamais !

L’école pour moi n’a jamais été un long fleuve tranquille car ma maladie me mettait sans cesse des bâtons dans les roues et j’avoue que ça été très dur ! J’ai grandi avec deux plus jeunes sœurs qui n’ont pas cette maladie mais qui sont là à chaque fois que j’ai besoin d’elles et qui me boostent quand j’ai le moral qui flanche.

Je suis mariée depuis presque 25 ans avec Fabrice et il y a  Pierre, notre rayon de soleil  qui va sur ses 24 ans. Il est né malgré les mises en garde et refus des docteurs soucieux pour les conséquences sur ma santé mais je ne regrette absolument rien, il est une des plus belles choses qui me soient arrivées, ce n’est pas le sujet mais je tenais à le souligner  !

Je suis invalide à  80  % et je touche l’AAH à vie. Tant que notre fils avait moins de 20 ans, il était considéré à notre charge et donc je touchais mon AAH à taux plein mais après ses 20 ans cela a changé la donne. Depuis presque 4 ans,  je ne touche plus que 590 euros car mon mari  touche apparemment trop… 1700 € ! Pire, je toucherais 0 € si on ne déclarait pas ses frais réels plus avantageux pour nous !

> Ils appellent ça la solidarité familiale… moi j’appelle ça de l’injustice ! On n’a pas choisi ce qui nous arrive… personne ne voudrait notre place… Notre handicap, nous le vivons tous les jours et personne ne peut comprendre ce que nous vivons au quotidien.

Est-ce que vous accepteriez que l’on dise à quelqu’un  qui arrive à sa retraite qu’en fait il ne touchera rien car son conjoint, toujours actif,  a 1700 € de salaire ! Personne n’accepterait cela, alors pourquoi nous nous devrions rester sans rien dire ?

> Je redoute chaque augmentation qu’a mon mari car à chaque fois je sais que moi du coup mon AAH chute et il ne peut pourtant pas les refuser car c’est ce qui lui fait sa retraite. Sa demi-prime de Noël n’est finalement pas un cadeau non plus car à la sortie je paie les pots cassés !

J’en appelle au bon sens des députés qui vont devoir voter cette loi, je leur demande de se mettre à notre place car le handicap peut aussi un jour frapper à leur porte ! Je leur demande un peu d’humanité…

