---
title: "«Il en va de la dignité d’un pays d’être solidaire de ses populations les plus fragiles»"
author: "Claudia"
date: "2022-02-01"
categories: [colère, dignité, divorce, pauvreté]
---

J’ai été dépendante financièrement de mon conjoint qui gagnait un peu plus de 2000 euros par mois, l’AAH je n’y avais donc pas droit ! Être dépendante de l’autre, c’est une vie au rabais, un contrôle économique et moral de tous les jours…

J’ai eu la force de divorcer… Et de la force il en faut quand on comprend combien LA CAF est réactive pour relancer des droits !  Une semaine d’attente entre chaque rendez-vous téléphonique, des réponses  évasives voire erronées qui me disaient de repasser par la case MDPH !!! Et combien de recherches sur la toile pour savoir si j’avais droit à une prestation compensatoire ! J’ai fini par  comprendre que la solidarité familiale brandie en étendard par LaREM ne tenait plus en cas de divorce ! Oui, la prestation compensatoire ampute l’AAH d’autant ! Etonnant , non ? Et bien même pas, quand on connaît la politique du moins disant social de ce gouvernement ! Notre cher président dirait que ça coûte « un pognon de dingue », n’est-ce pas !!! Que dire du maintien des personnes en situation de handicap sous le seuil de pauvreté… Que dire en effet d’un hypothétique salaire (c’est bien connu, il suffit de traverser la rue pour trouver un emploi de nos jours ! ) qui entre lui aussi en déduction de l’AAH au bout de six mois de travail !

> Notre handicap, nous ne l’avons pas choisi ! L’AAH n’est pas un revenu social comme les autres, il en va de la dignité d’un pays d’être solidaire de ses populations les plus fragiles dont nous faisons partie !