---
title: "«Il me reste environ 30 € par mois pour vivre»"
author: "Mathieu"
date: "2021-05-08"
categories: [dépendance financière, échec, impossibilité de travailler, injustice, précarité]
---

Je suis atteint d’une maladie génétique depuis mes 12 ans, elle est évaluée à 80%. En 1999, j’ai été opéré dans l’espoir de retrouver une « vie normale ». Celle-ci ayant échouée, on m’a opéré une dizaine de fois par la suite.

Le temps passé à l’hôpital a donc considérablement bouleversé mon parcours scolaire. Après plusieurs formations dans les métiers de l’image, j’ai été employé. Mon employeur a rompu mon contrat avant la fin de la période d’essai me jugeant insuffisamment productif aux yeux du monde du travail. Cela s’est répété d’entretien en entretien. Malgré les douleurs intenses quotidiennes et persistantes, je me suis tourné vers les associations pour rester actif et ne pas vivre isolé.  Jusqu’à juin 2015, je vivais seul dans mon appartement.

> Malgré tous les échecs accumulés, j’étais indépendant. Les aides de la CAF avec l’AAH, la majoration pour la vie autonome ainsi que l’aide au logement me permettaient de vivre et d’assumer les frais liés à ma maladie. 

Dans ma vie privée, j’ai trouvé le bonheur. Depuis juin 2015, j’ai emménagé avec mon amie. Il a fallu des mois de recherche et surmonter de nombreux obstacles pour trouver notre appartement. Le logement devait être accessible avec un ascenseur pour que je puisse y entrer en fauteuil. Un logement récent, donc plus cher par rapport à ce que j’aurai pu rechercher si je n’avais pas eu d’handicap.  Nous avions pris en compte nos revenus par rapport au montant du loyer et fait une simulation sur le site de la CAF pour évaluer le montant des aides.

> Cette simulation n’a jamais indiquée une baisse de mon AAH et la suppression de la majoration pour la vie autonôme.

Mes ressources subissent une perte de 422 € depuis le nouveau calcul de la CAF.  Maintenant, je me trouve dans une situation financière très compliquée. Sans compter mon budget alimentation et les à-côtés de la vie, il me reste environ 30 € par mois pour vivre.

> Je deviens dépendant de ma compagne alors que j’ai toujours lutté pour mon autonomie. J’avais acquis une vie presque comme les autres, ce fut un long et rude combat pour en arriver là.

Je vis cette situation actuelle comme un échec et une injustice après à tous les sacrifices que j’ai mené pendant 21 ans. Je suis révolté par le mode de calcul qu’effectue la CAF, il est injuste et totalement discriminatoire. Ma situation pourra difficilement évoluer puisque mes aides sont calculées sur les revenus de ma compagne. 

> Ma situation est bien différente à celle d’une personne percevant le RSA car je ne peux pas travailler.

Si j’avais habité chez mes parents, j’aurais perçu l’AAH à taux plein car leurs ressources ne sont pas prises en compte.  Cette situation risque de fragiliser ma vie de couple. Je constate que je suis condamné à vivre avec le minium, d’être en permanence dépendant de ma compagne. Quand le salaire de mon amie augmentera, cela entraînera une baisse de mes ressources. Elle aussi se sent freinée dans son travail, par peur que je perde mon AAH et de devoir assumer seule notre vie financière à 2, ma compagne se refuse toute évolution de carrière. Indépendamment de ma volonté, cette situation précaire risque de m’isoler socialement petit à petit. D’un point de vue fiscal, ma compagne et moi sommes également tous les deux pénalisés.

> Nous ne sommes ni mariés, ni pacsés et pour autant nous ne pouvons pas faire une déclaration commune.

Mon amie assume déjà la baisse de mes revenus et elle doit malgré tout payer ses impôts comme si elle vivait seule.  

Il est urgent que les personnes handicapées vivant en couple mariés ou non puissent conserver une autonomie financière. Cela passe par l’individualisation de l’AAH et le vote à l’assemblée du 17 juin.  