---
title: "«Je quitterai cette Terre pour que mon conjoint puisse vivre un peu...»"
author: "Mimi"
date: "2021-05-14"
categories: [dignité, renoncement au couple]
---

Je viens déposer mon témoignage, sans raconter ma vie.Tous ceux qui sont comme moi comprendront pourquoi je ne veux pas me mettre à nu dans ce témoignage.

Être handicapée et être dépendante de mon conjoint, alors qu’avant je travaillais ! Mais hélas, je n’ai pas assez travaillé pour avoir droit à une pension. Mon mari est lui-même en invalidité suite à l’usure de son travail. Non seulement il doit faire face à ses problèmes, et en plus il doit s’occuper de moi et survenir à mes besoins. 

Mes besoins coûtent cher et c’est là que le gouvernement ne veut pas comprendre. Nous avons besoin d’une mutuelle qui nous coûte cher à nous deux, au regard de nos besoins et pouvoir prétende à remboursement pour du matériel médical (celui de la sécurité sociale ne couvre pas tout).

On arrive à un moment où ma vie bouffe tout, revenus, la vie de mon conjoint etc… Les fins de mois sont très difficiles. On se sort jamais, pas de resto, pas de ciné, rien d’indispensable.

Si le gouvernement ne veut toujours pas changer sa vision (il ne veut  pas rencontrer les vraies personnes qui sont dans la galère tous les jours),

> je sais que je quitterai cette Terre pour que mon conjoint puisse vivre un peu et ne plus à payer pour moi.

Je ne serai plus un poids, un fardeau pour l’Etat, ni pour qui que ce soit, vu qu’on ne nous écoute pas et qu’on ne veut pas nous voir et encore moins entendre les problèmes qu’on rencontre quand on vit en couple. 
