---
title: "«Imaginez si je ne peux plus travailler. J’aurai l’impression de n’être qu’un boulet pour lui !»"
author: "Sandrine"
date: "2021-03-23"
categories: [dépendance financière, dépression, restes à charge]
---

J’ai une RQTH depuis peu pour un spina-bifida déclaré à ma naissance qui ne me posait jusqu’à maintenant pas de soucis dans mon travail. Il y a peu, prenant de l’âge, les symptômes se sont aggravés et m’empêchent d’assurer mon travail un certain nombre de jours par mois. Je me suis donc décidée à faire un dossier à la MDPH. Alors même que je vais sûrement perdre sous peu mon emploi car il est incompatible avec mes soucis de santé (je travaille dans la restauration et je suis incontinente) je n’ai le droit ni à la PCH (pour mes changes complets pour adultes que je dois du coup payer de ma poche) ni à l’AAH car mon mari touche 1700€ par mois.

> Cela fera donc environ 850 euros par personne et on pourrait être considéré encore comme gagnant trop ?

Je me sens dans une impasse, je travaille et participe à la vie du foyer mais plus pour très longtemps. Je vais peut-être perdre mon emploi en raison de mon état de santé qui se détériore, mon conjoint est déjà obligé de faire beaucoup d’heures supplémentaires pour combler mes arrêts de travail fréquents. Comment parviendrons-nous à boucler les fins de mois ?

> Tout ça joue beaucoup sur mon moral, je suis parfois dans un état dépressif.

Imaginez si je ne peux plus travailler. J’aurai l’impression de n’être qu’un boulet pour lui qui n’a qu’un salaire de 1700 euros ! Je pense que ce sera compliqué de garder notre maison…