---
title: "«J’ai honte de devoir dépendre de mon mari mais à cause de ma santé je ne peux plus travailler»"
author: "Sandra"
date: "2021-04-07"
categories: [dépendance financière, honte]
---

Je m’appelle Sandra. Je me suis mariée en mai 2018. J’ai 46 ans et mon mari 57 ans. J’ai été reconnue handicapée par la mdph en 2018. On m’a attribué l’AAH, la carte pour stationnement handicapé et une carte prioritaire pour posture debout pénible. Mon mari est en invalidité depuis 2010. J’ai différentes maladies auto-immunes. Depuis 2012 j’ai un lourd suivi médical.

J’ai honte de devoir dépendre de mon mari….. A cause de ma santé je ne peux plus travailler… Mon mari non plus, il a un cancer…. Nos vies ont basculé du jour au lendemain, avec mes maladies je ne peux plus faire les gestes du quotidien… mais je dois quand même m’occuper de lui, heureusement que notre amour est fort. Je prend beaucoup sur moi, et j’oublie mes maladies.

Avec la loi actuelle l’amour a un prix… le prix de subvenir à mes besoins avec sa pension d’invalidité ! La CAF me donne environ 700 euros… Nous avons 2 ados… C’est difficile pour toutes les personnes dans mon cas hommes, ou femmes. Je souhaite de tout cœur que l’assemblée nationale accepte cette loi, pour que tous les couples puissent vivre dignement.

Je voudrais dire que beaucoup de personnes ne sont pas libre de vivre ensemble par amour…. Et pourquoi ?  À cause de cette loi
Ils n’ont pas le choix de vivre ensemble, par amour, car la personne qui a un  handicap perdra son AAH……