---
title: "«La solidarité familiale est bien présente et la désolidarisation des revenus du conjoint n’y changera rien»"
author: "Amandine"
date: "2021-03-28"
categories: [avenir financier, confiance en soi, dommages collatéraux, fardeau, renoncement, solidarité familiale]
---

Maman et femme épanouie ou presque…
Handicapée depuis l’âge de 13 ans, je me suis toujours battue afin d’être au maximum « comme tout le monde ». Alors comme tout le monde je suis allée à l’école, j’ai appris un métier, tout cela en alternant école et lourdes interventions chirurgicales ainsi que rééducation. Je suis sortie diplômée. Comme tout le monde j’ai cherché du travail et je me suis vu confrontée à l’une des plus grandes injustices, la discrimination à l’embauche…
J’ai eu la chance de trouver l’amour, de fonder une famille et même d’acheter une maison… Ah non, pas vraiment puisque ne travaillant pas, ne percevant « que » l’AAH, je n’ai pas pu contribuer à l’achat de notre maison.

> Depuis quelques années mon conjoint a eu la chance d’évoluer professionnellement ainsi notre pouvoir d’achat aurait dû pouvoir augmenter mais non, plus il travaille, moins je perçois et c’est toute la famille qui en pâtit…

Je tiens à préciser que mon conjoint est réparateur en atelier, qu’il touche donc ce que l’on considère comme un salaire moyen. Et moi qui souffre dans mon corps, qui souffre de ne pas exister dans la société, de rester encore et toujours sans emploi… Je me vois diminuer d’année en d’année, de n’être que « le boulet » de tous… Je perds de l’argent, mais je perds avant tout en indépendance, en confiance en moi… Afin d’éviter d’affecter mon moral plus qu’il ne l’est, mon conjoint m’a gentiment proposé de compenser la perte d’AAH…

> Il a longtemps refusé de prendre des heures supplémentaires pour me permettre de conserver mon AAH, il a opté pour avancer dans sa carrière en me promettant de ne pas amputer mon confort de vie.

C’est cette même personne qui prend sur ses vacances pour s’occuper de nos enfants quand je suis trop mal pour le faire, qui assure le quotidien quand les douleurs sont trop intenses, qui est en première ligne quand tout devient trop dur et que mon moral flanche…

> La solidarité familiale est bien présente et la désolidarisation des revenus du conjoint n’y changera rien.

Elle nous permettra « juste » d’avoir un soucis en moins… Mon état de santé ne s’améliore pas, il risque au contraire de se dégrader.

Ce projet de loi serait pour nous l’assurance d’un avenir financier correct. En votant cette loi, de nombreux couples auront l’assurance d’un avenir où les soucis d’ordre financier ne seront pas une priorité, restera à la charge de la solidarité familiale les soucis d’ordre médicaux tels que le vieillissement des personnes handicapées, leur avenir quand le conjoint ne sera plus en mesure d’assumer ce rôle d’aidant, quand cette tâche sera celle des enfants si enfant il y a. Notre famille est là première à subir les dommages collatéraux du handicap,

> n’oublions pas que cette loi serait à la fois sécurisante pour nous personnes handicapées mais aussi pour l’ensemble de nos proches !