---
title: "«Des garçons malveillants qui ne montrent leur vrai visage que quand je perds l’AAH…»"
author: "Flora"
date: "2021-03-28"
categories: [dépendance financière, malveillance, violences conjuguales]
---

Je suis schizophrène, je perçois l’AAH avec 50% d’invalidité.
En mars 2016, je me suis mariée avec un sans-papier.
Suite à 6 mois de vie commune, la situation de mon mari a pu être régularisée auprès de la préfecture de Bobigny. Nous avions 860 euros d’AAH pour vivre. En 2 ans, malgré des problèmes de santé, j’avais réussi tout de même à travailler 6 mois. Lorsque que mon conjoint a commencé à gagner sa vie en intérim, il a gagné 1750 euros par mois.

> De mon côté, j’ai perdu l’AAH. Et mon conjoint a changé de comportement…

Alors que je l’avais aidé à obtenir ses papiers, alors que je l’avais aidé à obtenir son permis de conduire, alors que j’avais subvenu à ses besoins avec mon AAH, dès que sa situation s’est stabilisée et que j’ai perdu mon AAH, il a décidé de garder l’argent pour lui. Il s’est mis à me mépriser, il ne voulait plus mettre le préservatif pendant nos relations sexuelles, il est devenu infidèle et il ne me donnait plus d’argent pour les factures et les courses. J’ai donc choisi de faire de l’intérim mais j’avais déjà des factures en retard à cause de lui…

En 2017, Monsieur part au Sénégal avec ses économies pour des vacances de 3 mois sans soldes

> et il me laisse enceinte sans aucune ressource.

La coupe est pleine, je demande le divorce qui n’est toujours pas prononcé par un juge, à l’heure actuelle. En effet, plusieurs tentatives de divorce par consentement mutuel ont échoué. Il me fait croire qu’il est d’accord pour un divorce à l’amiable puis il change d’avis à la dernière minute, laissant les avocats en plan et moi avec. J’ai déjà déposé trois demandes d’aide juridictionnelle à cause de lui. Dans deux mois, j’aurai une nouvelle aide juridictionnelle et cette fois-ci, cela ne sera pas à l’amiable mais pour motif de séparation de corps et rupture de vie commune supérieure à deux ans… Ma seule « chance » dans cette histoire est que ma grossesse ne soit pas arrivée à son terme..

Lorsque nous touchons l’AAH, c’est que nous sommes réellement handicapé(e)s, et donc la carrière professionnelle est difficile à entretenir. Or lorsque l’on se met en couple, on perd l’AAH et notre autonomie vis-à-vis de notre conjoint. Et la relation conjugale se détériore, le conjoint travaille pour deux personnes et il finit par considérer que son ou sa conjoint(e) handicapé (e) est un(e) fainéant(e) et qu’il/elle lui mange son salaire.

> Au lieu d’encourager le couple à travailler, cela provoque une disgrâce au yeux du conjoint valide.

Il faudrait interrompre l’AAH seulement lorsque les deux personnes du couple ont un emploi mais pas lorsque seulement un des deux travaille. La plupart des conjoints ont peu d’estime face au handicap, ils s’imaginent que l’on simule notre maladie. Ils nous prennent pour des assistés et des paresseux. Sans AAH, pas moyen d’avoir son indépendance, on devient des personnes entretenues ou alors maltraitées car nous avons plus aucune autonomie. Les conjoints deviennent infidèles, irrespectueux, irrités dès lors que l’on parle d’argent.

> Personnellement, j’ai perdu beaucoup d’énergie dans mes relations amoureuses. Je suis de nature romantique et les garçons m’ont massacré, des garçons malveillants qui ne montrent leur vrai visage que quand je perds l’AAH et que nous sommes déjà lourdement engagés dans la relation.

