---
title: "«Mais là, ‘problème’ : je tombe amoureux»"
author: "Timothée"
date: "2021-05-02"
categories: [dignité, impossibilité de travailler, urgence]
---

Cela fait quelque temps que le sujet est sur la table, et cette loi doit maintenant passer de toute urgence. C’est vital pour moi et pour toutes les personnes en situation de handicap, qui sont ou seront un jour dépendants financièrement du simple fait d’être tombés amoureux.  

J’ai eu un trauma crânien grave en 2010, à l’âge de 22 ans. J’étais dans un coma si profond que j’avais 60% de chance de ne jamais me réveiller. Après des années de rééducation, j’ai essayé de retrouver un semblant de vie normale, ce qui passe par un travail, au moins à temps partiel. Mais les maux de tête, les vertiges, les problèmes cognitifs, et la bipolarité induite par mes lésions neurologiques rendaient, et rendent toujours, mon existence trop douloureuse.

> Il m’est impossible de me réinsérer professionnellement, malgré le bac +5 que je venais de finir avant mon accident. 

En 2020, après 10 ans d’incompréhension et de batailles administratives, je suis enfin reconnu comme adulte handicapé, entre 50 et 79% d’incapacité et pour une durée minimum de 5 ans. C’est un énorme soulagement. Plus besoin d’endurer une souffrance inhumaine au travail pour une paye misérable (j’en suis allé jusqu’à la tentative de suicide), ou de m’humilier auprès de mon père pour qu’il me donne de l’argent de poche : j’ai droit à une allocation qui me suffit pour vivre. Pas de manière opulente, mais c’est (tout juste) suffisant.

> Mais là, « problème » : je tombe amoureux.

C’est mon âme sœur, qui me comprend et me soutient coûte que coûte, et nous décidons, par amour, de nous installer ensemble. Mais elle a le défaut de gagner correctement sa vie (un peu moins de 2000€ nets par mois), et je découvre avec stupeur que ce concubinage va me retirer mon allocation. Allocation à travers laquelle j’avais trouvé un statut, une manière d’exister et d’enfin relever la tête.
À 33 ans, et après des brouilles familiales, il m’est impossible (et c’est non souhaitable, pour des raisons de dignité) de me tourner vers mon père.

> Il m’est aussi impossible de demander de l’« argent de poche » à ma concubine pour mes besoins personnels : elle travaille dur, pour ce payer ce dont ELLE a besoin. 

Cette situation est complètement lunaire, et c’est pourtant celle de milliers de femmes et d’hommes en couple et en situation de handicap, très souvent dans des situations bien pires que la mienne, et qui sont dans l’incapacité d’écrire un témoignage comme celui-ci. Ma détresse est totale.

> J’en suis à espérer secrètement que ma concubine perde son travail, afin que je retrouve mon allocation.

Il faut que cette loi soit votée favorablement,  je l’espère du plus profond de mon être, et avec le peu de dignité qu’il me reste.