---
title: "«Je me sens inférieure car je n’apporte aucune entrée financière»"
author: "Cécile"
date: "2021-03-27"
categories: [autonomie, dépendance financière, honte, humiliant, liberté]
---

 J’ai longtemps hésité à écrire sur ce sujet dont finalement j’ai honte, alors que j’en suis pourtant victime. Être malade et souffrir d’un handicap, je ne l’ai bien évidemment pas choisi.

Depuis toujours, j’ai appris à grandir en gardant les poings serrés. Se battre contre la souffrance, la douleur, la différence, les préjugés. Tout cela n’est pas facile. Avancer encore, garder la tête haute, et trouver sa place dans la société n’est pas toujours chose aisée lorsqu’on n’entre pas tout à fait dans les cases. Lorsqu’on ne correspond pas vraiment aux « normes ». Battante, souriante, et malgré la maladie qui me ronge année après année, un petit bout de femme plein de détermination, voilà ce que j’étais durant les 24 premières années de ma vie.

L’amour est une chance. Un formidable cadeau. Une force supplémentaire qui vous soulève et vous permet quelques fois de déplacer des montagnes. Ce bonheur, malgré le handicap, les obstacles du quotidien, le combat pour la vie quand la maladie vous étrangle, je l’ai pris comme une chance inespérée. 

> En épousant l’homme que j’aime, j’étais loin de me douter que cela représenterait d’énormes difficultés financières.

J’ai rempli les documents. J’ai signalé mon changement de situation. J’ai fourni les pièces justificatives. Et j’ai reçu ce courrier m’annonçant que l’AAH ne me serait plus accordée, car mon époux avait un salaire qui dépassait les plafonds fixés pour pouvoir prétendre à obtenir une quelconque allocation.

Du jour au lendemain, je suis devenue dépendante. C’est comme si au moment où je prenais pleinement mon envol dans cette nouvelle vie à deux, on me tirait une balle en plein ciel. La chute fut vertigineuse… Depuis que je suis mariée, je vis exclusivement grâce au salaire de mon mari. Je me sens honteuse et prisonnière de cette situation. J’ai perdu une forme de liberté et d’autonomie. J’ai le sentiment d’être financièrement un boulet aux chevilles de notre couple.

Je ne perçois pas d’AAH. Chaque dépense réalisée dans la vie de tous les jours est prélevée sur l’argent que lui seul ramène grâce à son emploi. Je me sens inférieure car je n’apporte aucune entrée financière, et j’ai davantage encore cette culpabilité d’être malade bien ancrée dans la poitrine. Je paye le prix de ne pas pouvoir travailler, de ne servir à rien. Et je fais bien malgré moi payer le prix à mon mari d’être tombé amoureux d’une jeune femme handicapée car je nous enfonce financièrement.

Quand je dois faire une dépense, même pour un simple cadeau d’anniversaire, je dois puiser sur ce que j’estime être l’argent de mon mari. Mon mari finance tout à lui tout seul puisque lui seul gagne de l’argent. Pour tout achat, j’ai la place de celle qui dépense, et qui doit systématiquement demander à son conjoint si elle a son « autorisation ».

> Je ne suis pas dépensière, mais c’est profondément humiliant de devoir toujours demander l’accord à la personne avec qui l’on vit de puiser sur ses finances. On ne peut pas partager les frais. C’est toujours mon époux qui paye. Cela peut créer des tensions par moments, et des disputes blessantes.

Au lieu d’avancer sereinement dans cette nouvelle vie, voilà bientôt onze ans que je suis devenue totalement dépendante de mon mari. C’est une situation très douloureuse et humiliante même si je l’aime de tout mon cœur.

> Je veux être son épouse, pas un boulet financier. Je ne veux plus entendre : « Je te rappelle que l’on a que mon salaire. Sans moi, on ne pourrait pas ceci, ou cela… ».

Je ne veux plus avoir honte de dire « Il faut que je demande à mon mari si je peux acheter cet article car moi je n’ai pas d’argent ».