---
title: "«À plusieurs reprises, j’ai pensé me séparer et détruire mon mariage !»"
author: "Arnaud"
date: "2021-04-13"
categories: [dépendence financière, divorce, SOS, survivre]
---

Je suis en invalidité à 80% avec une sclérose en plaques. Je suis marié, je suis dépendant de ma femme car elle travaille. Elle gagne le SMIC, et je touche une pension de la CPAM. Tout ceci ne me donne pas le droit à l’AAH, une fois le revenu du conjoint déclaré.

> Et c’est un handicap supplémentaire pour vivre. Je devrais dire plutôt survivre, car à plusieurs reprises, j’ai pensé me séparer et détruire mon mariage ! Oui c’est « le prix de l’amour ».

Aujourd’hui en 2021, j’ai l’impression de vivre en reclus dans mon coin. Mentalement et étant déjà dépendant physiquement et financièrement de ma femme, c’est un message que je lance au gouvernement de notre situation de détresse !

> Je n’ai pas demandé à tomber malade ! Avoir rencontré la femme de ma vie et lui faire subir ma dépendance financière peut tout faire basculer. 