---
title: "«J’ai l’impression d’être un poids ou un rebut pour la société»"
author: "Isabelle"
date: "2021-03-23"
categories: [culpabilité, dépendance financière, dignité]
---

J’ai 49 ans. Je suis handicapée à 80%. Je suis mariée et nous avons trois étudiantes qui touchent très peu de bourses voire pas (pour l’une des trois), qui continuent leurs études et qui sont encore à la maison. Nous devons payer les charges, la cantine, les frais de scolarités et la nourriture pour 5.

> Je touche l’AAH d’un montant de 360 euros. C’est peu pour subvenir aux besoins de la famille. Nous devons nous priver de loisirs et de sorties pour éviter de dépenser superficiellement.

Mon conjoint est obligé de me verser de l’argent afin que je puisse payer les courses alimentaires. Je n’ose pas lui demander de l’argent pour aller chez le coiffeur ou m’habiller. Je ne peux pas faire plaisir à mes filles et à mon mari. Je suis dépendante de mon mari financièrement. J’ai le moral à zéro, plus de vie sociale. Je perds peu à peu ma dignité. Ce n’est pas à lui de subvenir à mes besoins.

> J’ai l’impression d’être un poids ou un rebut pour la société. Mon handicap, je l’ai depuis la naissance. Je n’ai pas choisi ma vie et je dois vivre avec.

