---
title: "«Avec 1800 euros tout compris pour trois il faut compter chaque sous»"
author: "Benedicte"
date: "2021-03-23"
categories: [argent, compter, courage, espoir, pauvreté, résignation]
---

Voilà, je percevais jusque là une AAH à taux plein et mon mari une pension d’invalidité avec une AAH différentielle de 200 euros. Depuis que mon mari est à la retraite il dépasse le plafond de 180 euros et n’a plus d’AAH. 200 euros, c’est peu, c’est vrai, mais c’est comme si une fois à la retraite son handicap avait disparu ! Mais il est toujours handicapé ! Avec les plafonds, mon AAH à moi aussi est réduite de 200 euros. De plus, notre fils de 20 ans est revenu vivre chez nous. Nous l’aidons comme nous pouvons car jusqu’à ses 25 ans il n’a droit à rien, juste une complémentaire santé.

> Nous avons encore la chance d’être propriétaires, mais avec 1800 euros tout compris pour trois il faut compter chaque sous.

Nous n’espérons plus grand chose maintenant avec notre âge et notre handicap (moteur et visuel).

> L’argent n’est pas le plus important, nous sommes juste fatigués de nous battre pour tout.

Notre vie a été difficile, semé d’embûches et de malheurs (comme le suicide de ma fille). Nous nous n’avons plus aucun espoir concernant ce monde. Mais pour ceux qui garde l’espoir, battez vous ! Courage et relevez la tête ! Vous n’êtes pas des machines à mettre au rebus ! Le handicap n’est pas une tare dans ce monde parfait. Merci de publier tout ces témoignages en espérant que les choses bougent.