---
title: "«On s’aime, mais on est obligés de rester célibataires...»"
author: "Marie"
date: "2021-05-08"
categories: [impossibilité de travailler, perte de revenus, rêves]
---

J’ai un petit ami depuis 11 ans. Notre rêve serait de vivre ensemble et de nous marier. Mais c’est impossible  car si je vis avec lui, il sera obligé de payer toutes mes charges ! Prêt auto, assurance auto, soins dus à mon handicap, non remboursés entièrement par la sécu. Sans oublier le gasoil, les vêtements et les petits plaisirs de la vie. Je vis avec l’AAH et je peux garantir que c’est tout juste. Mon petit ami a lui aussi ses charges.

> Si nous vivons ensemble et que l’on me supprime mon allocation, notre situation financière serait catastrophique !

Alors on reste chacun chez soi. C’est triste, on a plus de 50 ans tous les deux, on s’aime, mais on est obligés de rester célibataires. C’est pas juste.

**C’est déjà difficile de vivre avec un handicap, on est condamné aussi à vivre seul. On ne l’a pas choisi. On s’aime en cachette.**

