---
title: "«Je me sens mal, honteuse…»"
author: "Melanie"
date: "2021-03-28"
categories: [dépendance financière, fardeau, honte]
---

J’ai un taux d’invalidité entre 50%et 79% et j’ai le statut de travailleuse handicapée. Je souffre d’une maladie de Verneuil (maladie orpheline) qui est très très douloureuse et handicapante.

Je touchais la AAH jusqu’à ce mois-ci. Un de mes deux enfants vient d’avoir 20 ans et j’ai eu la surprise d’apprendre, sur mon compte Caf, que mon AAH  me sera coupée pour le mois d’avril et pour toujours ! En effet, mon fils a eu 20 ans donc la Caf ne le considère plus comme enfant à charge même s’il est étudiant et vit toujours à la maison. Et donc, le salaire de 2000 euros de mon mari suffit, selon la Caf, pour vivre à 4 personnes.

Je ne touchais que 300 euros d’AAH, en prenant en compte le salaire de mon mari. Cela me permettait d’avoir un peu d’argent pour participer aux frais de la maison, mais cela était déjà compliqué. Maintenant, je vais me retrouver avec aucun revenu et je ne sais pas comment nous allons faire pour vivre à 4 personnes sur le salaire de mon homme.

Déjà que je me sentais mal de ne pas pouvoir travailler à cause de ma maladie, cela va être pire pour moi qui vais devoir dépendre entièrement de mon homme financièrement. Il m’aide avec mon handicap, il m’aide à me laver, à m’habiller, fait le ménage et à manger etc… Et maintenant il devra en plus m’entretenir financièrement, je me sens mal d’avance, honteuse et j’ai l’impression de ne servir à rien à part être un boulet pour lui.

> J’espère vraiment que les députés vont approuver cette loi. Ils devraient se mettre à notre place, personne n’est à l’abri, même pas eux.

Je préférerais aller travailler et de ne pas avoir cette maladie qui me bouffe la vie chaque jour et surtout qui abime tout mon corps et qui me fatigue. J’espère vraiment qu’ils feront le bon choix…