---
title: "«Le serpent qui se mord la queue»"
author: "Benjamin"
date: "2021-03-27"
categories: [dépendance financière, fardeau, impossibilité de travailler]
---

J’ai 39 ans, je suis en situation d’handicap depuis ma naissance : né prématurément, j’ai été opéré d’une hydrocéphalie dans les années 80 et de nombreuses complications en ont découlé, laissant de graves séquelles.

Mon handicap ne me permet pas de travailler, j’ai une reconnaissance d’invalidité à plus de 80%, et pourtant je ne touche qu’une partie de mon allocation. En effet, j’ai rencontré ma compagne il y a  maintenant 13 ans, nous vivons ensemble, elle est soignante, aide médico-psychologique plus exactement, dans une maison d’accueil spécialisée. Elle accompagne des adultes polyhandicapés dans tous les actes de la vie quotidienne, etc. Pourtant elle ne gagne pas énormément : elle a un salaire net de 1500 euros environ, en travaillant deux week-ends par mois… Par conséquent, je ne peux prétendre au 900 euros d’AAH par mois, je touche actuellement 530 euros car le revenu de ma conjointe est pris en compte.

> De ce fait, je ne peux quasiment pas participer à nos besoins, je me retrouve donc sans pouvoir travailler et dépendant financièrement de ma femme qui se tue au travail…

Elle ne peut prétendre à la prime d’activité car mon AAH rentre en compte dans le calcul de cette prime… Le serpent qui se mord la queue…

> Je ne me sens pas très bien par rapport à cette situation, j’aimerais tant soulager ma compagne.