---
title: "«Mon témoignage a pour seul but de souligner que ce problème n’est pas d’aujourd’hui»"
author: "Christian"
date: "2021-03-23"
categories: [fierté, renoncement]
---

En 1975, alors que j’étais étudiant, j’ai perçu une allocation mensuelle qui à l’époque ne s’appelait pas encore AAH mais qui a pris cet acronyme quelques années plus tard.

En 1982, j’ai rencontré celle qui allait devenir mon épouse et nous nous sommes rapidement mis en ménage. Ne souhaitant pas rester dans cette situation toute ma vie, j’ai stoppé mes études et entrepris de me mettre à la recherche d’un travail. Après plus de 150 rendez-vous j’ai fini par croiser un employeur qui m’a donné une chance unique : non seulement il a décidé de m’embaucher mais, ayant compris mon souhait de ne plus avoir l’étiquette de handicapé (à l’époque, cela n’était pas un gros mot…), il l’a fait dans des conditions tout à fait ordinaires sans que je sois travailleur protégé. La contrepartie de cette main tendue était l’acceptation d’un salaire extrêmement bas par rapport à mon niveau d’études, c’était en fait le SMIC de l’époque.

Ma rémunération mensuelle était inférieure à l’allocation que je percevais auparavant. Cependant, j’étais extrêmement fier de subvenir moi-même à mes besoins et je me suis empressé de le signaler à l’organisme payeur (CAF) lors de la déclaration annuelle de ressources. La réponse ne s’est pas faite attendre. J’ai rapidement reçu une notification m’indiquant que je devais rembourser le trop-perçu sur les quelques mois pendant lesquels j’avais également touché mon salaire. Je m’attendais bien évidemment à cela et je l’acceptais, sans doute avec encore une fois un peu de fierté.

> En revanche, quelle ne fut pas ma surprise de découvrir que le salaire de ma compagne pour l’année n-1 était pris en compte et que l’on me demandait donc le remboursement de l’allocation à compter du jour où nous avions décidé de prendre un appartement en commun. Dans sa grande bonté, la CAF a accepté d’étaler sur 12 mois ce remboursement…

Ma vie de couple n’a pas été affectée par des problèmes liés à l’AAH puisque j’ai cessé de la percevoir et que je ne souhaitais plus que ce soit le cas. À l’époque, ma compagne avait un salaire bien supérieur au mien, de l’ordre du double… De ce fait, si j’avais souhaité continuer à la percevoir, cela aurait été refusé. Mon témoignage a pour seul but de souligner que ce problème n’est pas d’aujourd’hui.

Aujourd’hui, pour moi, tout va bien. Après une carrière bien remplie, je suis à la retraite.

> Je n’en reste pas moins sensibilisé à ce problème qui reste pour moi une injustice qui aurait dû disparaître depuis bien longtemps.

