---
title: "«J’étais prête à lui rendre sa liberté»"
author: "Nathalie"
date: "2021-03-29"
categories: [dépendance financière, privation, souffrance]
---

J’ai 54 ans,  en accès à la propriété d’une petite maison de plein pied (adaptée à mes difficultés) que l’on a fait construire loin de la ville. Je souffre de plusieurs pathologies évolutives auto-immunes, qui me mèneront au fauteuil roulant. J’ai aussi été victime d’errance de diagnostic… Je souffre horriblement chaque jour et chaque nuit, et cela sans presque aucun répit, et ce toute l’année. Il me faut du calme, éviter le stress, la contrariété et l’angoisse; comme toutes les personnes atteintes de pathologies similaires. Le pire dans tout cela, est de devoir affronter la déchéance d’un corps qui se transforme radicalement et rapidement. Mon corps sur qui je ne peux plus compter, qui me lâche un peu plus chaque jour.

À cause des pathologies dont je souffre, je ne peux plus exercer le métier de soignante spécialisée auprès des personnes âgées. S’entendre dire qu’il fallait oublier mon travail que j’aimais beaucoup, et surtout l’idée de travailler.

> Qu’il me fallait avoir le courage d’annoncer à mon mari qu’il sera obligé de renoncer à tous les projets que l’on avait fait ensemble. Que la femme qu’il avait épousée ne serait plus jamais la même. Que l’avenir à mes côtés serait dorénavant très difficile à vivre et que j’étais prête à lui rendre sa liberté même si mon amour pour lui était IMMENSE . 

Après plus de 8 mois d’attente entre le moment de l’envoi de la demande d’AAH et la réception de la réponse, quelle ne fut pas ma surprise de constater que le comble de l’absurdité était atteint ! La CAF prenait en compte le salaire de mon conjoint pour calculer le montant de mon allocation !  Malheureusement pour nous, afin de m’aider à toutes les tâches du quotidien, mon mari a du prendre sa retraite anticipée. C’est pour lui perte de 600,00€ ! De ce fait, je perçois actuellement un peu plus de 400,00€ !

Il nous faut sans cesse calculer au plus juste :         

- Plus de coiffeur, de maquillage, de parfum ni de vêtements neufs!
- Fini les 5 fruits et légumes frais par jour.
- Oublié le traitement non remboursé par la Sécurité Sociale pour limiter mes douleurs d’arthrose. 
- Plus de cadeaux pour nos petits enfants pour leurs anniversaires, Noël et Pâques.
- Une vie sociale limitée au maximum : plus de sorties, loisirs et vacances.
- Plus de dépenses liées à l’entretien de la maison.

> Moi qui était une femme indépendante, aujourd’hui, non seulement je dépends physiquement mais surtout financièrement de mon époux !

Quel ressenti croyez-vous que j’ai de devoir quémander à mon mari l’autorisation de m’acheter des culottes car les miennes sont usées ?  Pensez-vous que je vive sereinement ? Que se passera-t-il si mon époux m’abandonne ? Comment voulez vous que mon corps ne me fasse pas souffrir, puisque je vis en permanence avec l’angoisse qu’il ne nous arrive pas un imprévu qui nous mette dans le rouge à la banque ? Comment voulez vous que je ne passe pas mes nuits de souffrances à culpabiliser ? Qu’à cause de mon état de santé, mon époux se retrouve affublé d’une personne qui vit à ses crochets? 

J’ai la chance d’avoir un mari compréhensif et aimant, une famille aimante et de merveilleux petits enfants plein de vie qui sont mon moteur ! Car sinon en étant réaliste, actuellement qu’est-ce qui pourrait me pousser à continuer de poursuivre une vie faite de souffrances et de privations ? Je vous laisse la réflexion de juger de ma logique, encore faut-il avoir envie de se mettre à ma place ! Ce que je ne souhaite pas même à mon pire ennemi !