---
title: "«Avec mon compagnon nous nous disputons sans arrêt pour ça, on est au bord de la rupture…»"
author: "Karine"
date: "2021-03-23"
categories: [dépendance financière, séparation, stress, suicide]
---

Bonjour, je m’appelle Karine, j’ai 53 ans. Je suis en vie maritale (concubinage) depuis le 1 janvier 1988. Mon concubin a une activité non salariée il est agent immobilier indépendant dans une petite ville depuis le 28 août 2005. Nous avons 2 enfants rattachés à mon dossier CAF, ils sont nés en 02/2000 pour mon fils et en 01/2003 pour ma fille.

J’ai été déclarée inapte au travail et licenciée. J’étais serveuse en restauration traditionnelle. Au bout de 2 ans d’arrêt de travail j’ai été mise en invalidité (cat. 2) depuis le 1 avril 2014, je perçois donc une petite pension de 340.52 € . Je suis reconnue handicapée par la MDPH pour un taux supérieur à 50 % et inférieur à 80 %, depuis 2014 on m’a donc accordé l’AAH. Je n’ai pas droit à la PCH vu que mon taux et inférieur à 80 %. Mon AAH s’élève actuellement à 559.12 € pour cette année vu que les revenus de mon conjoint ont baissés pour l’année 2019 par rapport à 2018 où ils étaient supérieurs au plafond, ce qui à donc entrainé la suppression de mon AAH pour l’année 2020. Aujourd’hui je la re-perçois pour 2021 car les revenus de mon compagnon ont largement baissés et que notre 2ème enfant compte pour le quotient familial vu qu’elle n’a pas encore 20 ans. 

Mme Cluzel a dit que les couples ont 1/2 part supplémentaire pour le calcul de l’impôt sur le revenu mais c’est faux pour ceux qui ne sont pas liés fiscalement ! Même en concubinage on prend en compte les revenus du conjoint alors qu’il n’y a pas les mêmes avantages fiscaux. De plus, comme mon concubin est seul propriétaire de notre habitation il n’a droit à aucune exonération sur les taxes d’habitation et foncières puisque son revenu fiscal de référence est supérieur aux limites. C’est comme si on perdait des deux côtés.

Aujourd’hui je dois demander à mon compagnon si j’ai le droit de dépenser pour acheter telle ou telle chose, il assume pas mal de frais mais il n’a pas un salaire fixe chaque mois vu qu’il est indépendant et on doit faire attention à nos dépenses, nos enfants vivent à la maison et génèrent aussi des dépenses, mais comme ils sont majeurs nous n’avons plus droit à aucune aide de la CAF.

> J’en ai marre de devoir demander de l’argent pour mes vêtements, mes loisirs, ou les soins qui me font du bien comme mes séances d’équithérapie ou d’ostéo, qui ne sont pas prises en charge par la sécu.

J’ai pensé fortement à me séparer, mais je ne peux pas vivre autrement que dans une maison individuelle à cause de ma dépression chronique. Je ne supporte pas de vivre en habitation collective, cela me déclenche de vives crises d’angoisse et de panique, et je ne me sens pas en sécurité dans ce genre d’habitat. De plus mes revenus ne me permettraient pas d’acheter une petite maison individuelle et je ne pourrais pas prétendre à un prêt de la banque de toute manière. Je souligne qu’en 2017 la maison de mon compagnon a pris feu, nous avons été relogés en maison jumelée et même là j’étais très mal mentalement. Heureusement nous avons eu la chance de trouver une nouvelle habitation individuelle adaptée aux personnes handicapées, car en plus d’être dépressive, je souffre de douleurs chroniques et de différentes pathologies dégénératives des articulations.

> Avec mon compagnon nous nous disputons sans arrêt pour ça, on est au bord de la rupture et si je devais le faire ce serait définitivement. Ma vie ne vaux rien à ce jour et parfois j’ai envie d’en finir une bonne fois pour toute.

Je demande à ce que la loi sur la désolidarisation des revenus des conjoints passe à l’assemblé pour la raison suivante : je veux mon indépendance financière et retrouver de la sérénité.