---
title: "«J’ai été une jeune femme indépendante à l’âme féministe durant des années, celle-ci ne me reconnaîtrait pas»"
author: "Maud"
date: "2021-03-17"
categories: [conflits, culpabilité, découvert, dévalorisation, féminisme, humiliations, invisibilité, privation, souffrance, tensions]
---

J’accepte, avec joie j’allais dire, de livrer mon témoignage, tant j’ai besoin d’être reconnue et comprise. J’ai quelques scrupules à parler de ma vie, parce que cela ne dévoile pas seulement un peu de la mienne, mais j’essaie par cette démarche que mes mots incarnent le plus justement possible la vie qui est la mienne, parce que je devine qu’elle doit ressembler un peu à celles d’autres personnes qui sont dans cette situation de dépendance financière.

Je me permets de vous en dire un peu plus sur moi en espérant que vous pourrez l’utiliser comme un matériau, l’invisibilité étant pour moi devenue multiple (parler et entendre m’épuise, difficile de s’exprimer dans ce cas…). Une maladie auto-immune de la jonction neuromusculaire et une surdité bilatérale devenue sévère interagissent et m’épuisent facilement, elles conditionnent ma vie de tous les jours et me font culpabiliser. Je cache cela dans mes colères, dans ma tristesse, et je me perds souvent dans des tâches domestiques qui prennent mon énergie, alors que j’aime lire par dessus tout, chose que je ne fais plus dans la journée sans une dose de culpabilité.

> J’ai fini par me rendre compte que j’essayais de me rendre utile chez moi le même nombre d’heures que mon mari devait passer devant ses collégiens, parce que les 240 euros par mois d’AAH que l’on m’attribue ont fini par abîmer la femme que je suis devenue. Pourtant j’ai été une jeune femme indépendante à l’âme féministe durant des années, celle-ci ne me reconnaîtrait pas. 

Mon mari a découvert quand j’ai eu droit à l’AAH, qu’il avait aussi droit à 40€ de prime à l’activité, ce qui nous a permis d’apprendre à des personnes que cette prime n’était pas réservée aux salaires inférieurs et proches du Smic. Ainsi ont-elles compris qu’un prof de collège marié à une femme handicapée, tous deux parents d’une presque lycéenne, ne sont pas bien nantis et doivent compter davantage que leurs collègues. Tout ça ne nous a pas fait du bien avec le temps et les raisons pour faire naître les conflits ne manquent pas. 

> Cette prise en compte des salaires de mon mari est devenue un véritable opprobre au quotidien, elle agit comme un poison dans nos relations, elle me met en position de faiblesse et renforce le sentiment de dévalorisation qui est le mien.

Chaque fois qu’une chose augmente, qu’il faut faire face à des dépenses imprévues, je me sens coupable. Alors je gère avec une main de fer, me prive au maximum – je suis restée des mois et des mois sans appareillage auditif – je fais les comptes de près, je dépense toujours au mieux, alors quand j’entends mon mari s’étonner qu’on soit à découvert avant le 20 du mois, je souffre terriblement, on se dispute et j’entends souvent des phrases telles que « mais je ne dépense rien moi ? ». Ce qui me rappelle que je ne gagne quasiment rien, et que le fait de gérer et décider des dépenses, afin d’y arriver le mieux possible, me fait devenir celle qui dépense.

Cette souffrance psychologique n’est pas moins délétère que de vivre avec une maladie rare et un handicap sensoriel, deux choses qui sont en moi et que j’affronte malgré tout, plus facilement que le fait de voir dans quelle impasse tout ça m’a amenée. Car je suis, malgré les humiliations, obligée de reconnaître que ma qualité de vie a augmenté, je mange de meilleurs produits, je vis dans une maison mieux chauffée, que lorsque que j’ai dû subvenir à mes besoins seule, la précarité alors était partout dans ma vie. Je vivais des situations très anxiogènes, mais j’avais une meilleure estime de moi. Aujourd’hui je suis un peu plus à « l’abri », même si nous sommes restés locataires par prudence. J’ai repris des forces physiques, mais la dépression me guette et je ne sais pas si je pourrais continuer à vivre en couple, j’en doute de plus en plus.

Je m’arrête là car vous n’êtes pas mon psy, même si votre appel m’a fait un bien fou. J’espère que les arguments et témoignages d’autres personnes finiront par faire prendre conscience aux décideurs que le couple est soumis à de rudes épreuves, l’amour et l’empathie ne font pas toujours barrage à ce que la société renvoie et propose aux personnes handicapées. Je pense que mon mari a souffert de certaines questions, remarques, incompréhensions récurrentes, et après 19 ans de vie commune et un handicap qui s’est s’ajouté à la maladie, après un véritable combat pour obtenir l’AAH fin 2019, le mode de calcul et son injustice nous ont paru invraisemblables.

Ce mode a encouragé des tensions : s’il fait des heures supplémentaires, je le prends contre moi, puisque si lui gagne plus, moi je « gagne » – ou plutôt je reçois – moins ! Celui qui travaille et fait vivre sa famille quand l’autre ne travaille pas voit toujours sa fatigue être valorisée. Ma propre fille parfois me rappelle que je ne peux pas subvenir à nos besoins, ou si peu, alors je perds en crédibilité quand je demande de l’aide… Je sais au fond que cette situation injuste la révolte en tant que future femme, nous arrivons à en parler dans le calme et sans pathos, mais quelle énergie gâchée et vies abîmées. 

Merci pour tout ce que vous faites et l’espoir que vous m’avez donné aujourd’hui. Quand j’aurai retrouvé des forces mentales, et si je peux aider dignement ma famille, je m’autoriserai à prendre le temps de faire ce qu’on appelle des choses pour soi. Je m’en voudrai moins d’imposer une vie ralentie à ceux que j’aime, j’aurai moins peur de l’avenir, je serai moins démunie et davantage dans la vie, nous pourrons vivre mieux tous les trois, matériellement comme affectivement. C’est ça aussi un mode de calcul qui respecte l’homme ou la femme dont on dit vouloir rendre la vie plus simple.

Maud