---
title: "«Je me bats à vos côtés pour ma fille qui vit le même cauchemar que j’ai vécu toute ma vie»"
author: "Martine"
date: "2021-03-23"
categories: [impossibilité de travailler, pauvreté, refus d'augmentation, trop-perçu]
---

Bonjour, je m’appelle Martine et je vais avoir 65 ans. Je suis atteinte de la maladie de Marfan, maladie génétique rare qui touche les yeux, le cœur, les poumons et le squelette. Je me souviens que mes parents avaient demandé ma carte d’invalidité sans connaître la maladie dont je souffrais. A 12 ans, j’ai perdu la vue pendant 2 ans. J’ai perdu ma maman à l’âge de 54 ans et 3 frères : un petit, un de 18 ans et, il y a quelques années, un de 66 ans tous atteints du Marfan.

Je me suis mariée à 18 ans et j’ai eu 3 filles. A la naissance de ma fille aînée Sonia, les médecins ont mis un nom sur la maladie car elle aussi était atteinte. A ce jour, j’ai subi 18 opérations, dont 7 des yeux. Un anévrisme de l’aorte avec ré-implantation de toutes les coronaires, hernie discale avec prothèse dans le dos et j’en passe…

J’étais secrétaire en assurances de 1981 à 1994 où là, j’ai été reconnue invalide à 90% avec impossibilité de travailler. J’ai donc dû cesser mon activité et comme mon mari à cette époque gagnait dans les 1200 euros, mon AAH était distillée donc double peine.

> Comme beaucoup je me contentais de ce que j’avais en vêtements et autres car, avec le peu que j’avais, il fallait contribuer à faire vivre la famille.

Je dois dire que mon mari ne m’a jamais fait de réflexions à ce sujet, ce qui était à lui était à moi. Ce qui m’a fait le plus de peine, c’est que mon mari, qui travaillait pour la commune, a toujours refusé de monter des échelons ou de percevoir des primes car on me réduisait mon AAH d’autant.

> Une anecdote marquante : en fin de carrière, la mairie s’est rendue compte que la secrétaire avait oublié de lui compter une augmentation de salaire pendant 2 ans. Pour ce faire, il a reçu un rattrapage de 3000 euros et de l’autre côté, j’ai dû les reverser pour une AAH trop perçue, donc c’était chou blanc…

Depuis mes 60 ans, je suis à la retraite et je dois dire que je n’ai jamais été aussi heureuse car je touche une petite retraite pour ce que j’ai travaillé et le reste est complété par l’ AAH au maximum. Normalement on m’avait attribué le complément de ressources (capacité de travail inférieure à 5%) de 2016 à 2026 et que je n’ai jamais touché. J’ai appris qu’à la retraite, la CAF devrait me le verser mais elle ne veut rien entendre.

Si pour moi aujourd’hui il est trop tard, je me battrai à vos côtés pour ma fille Sonia qui vit le même cauchemar que j’ai vécu toute ma vie.