---
title: "«Nous avons décidé de vivre ensemble sans tomber dans la dépendance»"
author: "Marie"
date: "2021-04-14"
categories: [confiance en soi, indépendance, peur, se cacher]
---

J’ai la vingtaine. Je ne souhaite pas parler de mon handicap, mais sachez que je suis reconnue à 80%, je touche l’AAH. Je suis accompagnée dans ma vie de tous les jours par un chien d’assistance et je ne peux pas conduire. Comme beaucoup de jeunes filles de mon âge, j’ai eu quelques aventures, qui se sont terminées plus ou moins bien. Le handicap y est pour beaucoup. Ce n’est pas évident pour le partenaire (et pour son entourage !) de faire ménage à trois avec cet invité pas vraiment désirable.

Fin 2019, j’ai rencontré quelqu’un avec qui tout se passait bien, quelqu’un qui était prêt à se mettre en couple avec moi malgré ma différence. Nous sommes tombés amoureux et nous nous voyions tous les soirs. Nous faisions garde alternée : une nuit chez lui, une nuit chez moi !

Puis, le Covid est arrivé. Nous ne nous sommes pas vus pendant plus de deux mois, comme beaucoup de couples. Le confinement a précipité nos projets et nous avons décidé d’habiter ensemble. En ajoutant le loyer que nous payions chacun de notre côté, nous pouvions avoir une petite maison avec jardin en centre-ville. L’idéal pour nous et pour mon chien. Qui ne l’aurait pas fait à notre place ?
Mais tous les contes de fées ne se passent pas comme prévu. À ce moment-là, je me rends compte que si on habite ensemble, sans être ni pacsé ni marié, je perds plus des trois quarts de mon AAH.

> Mon tort ? Être tombée amoureuse d’un ingénieur, qui travaille et qui gagne sa vie.

Cela a été très difficile à admettre pour moi qui ait toujours mis un point d’honneur à être le plus indépendante possible. Avec mon AAH et mes APL, soit un peu plus de 1100€ par mois, certains mois étaient difficiles mais je m’en sortais. J’arrivais même à mettre un peu d’argent de côté. Mais avec le petit pécule que cette loi absurde m’autorise à avoir, soit environ 200€, comment vivre décemment ?

> Là où mon témoignage diffère, c’est que, malgré tout, nous avons décidé de vivre ensemble sans tomber dans la dépendance.

Nous nous faisons passer pour de très bons amis en colocation. Nous avons donc déménagé depuis quelques mois dans une petite maison, avec jardin et surtout avec deux chambres, deux lits faits, deux penderies, deux gobelets à dents, deux gels douches différents, et absolument rien d’autre en commun que notre contrat de colocation.

> J’ai gardé mon AAH complète. Mais nous nions notre couple. Et nous vivons dans la peur. La peur du contrôle de la CAF qui ferait voler en éclat ce frêle bonheur.

Je pensais que tout se passerait bien. Mais non. Ça va mal. Je vais mal. **J’ai l’impression de vivre comme une délinquante, d’être en cavale**. Seulement nos familles et nos amis proches sont au courant que nous sommes en couple. Pour les autres, c’est « Je vous présente mon colocataire ». Nous passons notre temps à nous cacher. On ne se tient pas la main dans la rue. Nous n’avons aucune photo ensemble sur les réseaux sociaux, ni même dans nos téléphones. Pas de mots doux par messages, ça pourrait jouer contre nous. Le volet de notre fenêtre donnant sur la rue est quasiment toujours fermé, et je tremble de peur dès que quelqu’un qui n’est pas attendu sonne à la porte.

Cette situation ronge peu à peu notre couple. Des fois, nous avons réellement l’impression d’être davantage de très bons amis en colocation qu’un couple.

> Ça grignote notre intimité. Ça grignote aussi ma confiance en moi. Je me sens nulle, moins que rien, inutile.

Mon cerveau me persuade que je suis une mauvaise personne. Je ne suis pas heureuse, alors que je n’étais pas comme ça avant. J’étais le genre de fille qui a une joie de vivre communicative, et de très nombreux projets. **Je ne suis plus rien maintenant. Je ne me sens pas libre.**

Je sais que mon témoignage est relativement long mais j’avais besoin de m’exprimer. J’espère que la loi va enfin passer. **Il n’est pas normal, de nos jours, de ne pas être l’égal de son conjoint simplement parce qu’on a un handicap**. Il n’est pas normal qu’on nous laisse volontairement dans cette situation de dépendance. Depuis les années 1960 en France, les femmes ne dépendent plus de leurs maris pour travailler, ouvrir un compte en banque, passer le permis.

> Moi aussi, je rêve d’indépendance et de liberté. Je rêve d’avoir le droit de choisir si je souhaite me marier ou ne pas me marier, sans que l’argent ni le handicap soient des conditions.