---
title: "«Nous souhaitons nous marier ou nous pacser mais nous reportons cette idée...»"
author: "Albert"
date: "2021-05-14"
categories: [projets]
---

Nous sommes deux personnes handicapées en couple depuis 1 an et demi. Nous vivons ensemble depuis presque 2 ans (je l’ai d’abord hébergée). 

Elle bénéficie de l’AAH depuis plusieurs années et était en attente du renouvellement quand elle est venue vivre chez moi. Elle avait déjà réalisé son dossier et se désignait comme célibataire. Six mois après son arrivée, l’AAH a été enfin versée. Nous nous sommes posé la question de la déclaration de notre couple auprès de la CAF. Malheureusement, cela nous mettrait dans de grosses difficultés financières, vu que j’ai un travail salarié. Nous souhaitons nous marier ou nous pacser mais nous reportons cette idée, car la déclaration serait alors inévitable.

> Nous attendons et espérons que la loi passe car nous avons un projet de grossesse et nous devons être mariées ou pacsées pour pouvoir être toutes les deux reconnues comme mères de notre enfant.