---
title: "«Mon droit à l’AAH n’existe que sur le papier»"
author: "Irma"
date: "2021-03-26"
categories: [choix de vie, dépendance, humiliations, injustice, rêves]
---

La dépendance heureuse.  Ah, mais tu es heureuse, alors, tout va bien, c’est l’essentiel …
À 51 ans, atteinte de Polyarthrite Rhumatoïde depuis l’âge de 14 ans, je ne me souviens plus du tout de ce que c’est de passer 24h sans douleur. Je ne vais pas dire que cette maladie m’a tout pris, car ce serait mentir, mais c’est certain, elle m’a volé mes rêves de jeunesse : rêve d’études, rêve de travail, rêve de maternité et surtout rêve d’indépendance.

> Malgré la maladie, je rencontre l’amour. Nous nous marions et sommes heureux depuis plus de 30 ans. 

À 22 ans, je suis reconnue handicapée à 55% et droit à l’AAH, à 26 ans, je passe à 80%. Mais le revenu de mon mari fait que depuis de nombreux années, mon droit à l’AAH n’existe que sur le papier. Pas une seule fois, mon mari m’a fait me sentir comme un poids.

> Néanmoins, à l’achat de notre appartement, il était seul à pouvoir emprunter, c’était pour moi la première humiliation.

À deux, nous aurions pu voir plus grand. L’envie de fonder une famille était là, mais entre la maladie et la situation financière, ce choix a été repoussé jusqu’à … son abandon.À 45 ans, ne pouvant plus marcher plus de 100 m,  je dois passer le permis conduire. J’en ai toujours rêvé, mais financièrement c’était pas dans le budget, car il n’y a aucune aide, si ce n’est pas pour le besoin du travail.  La PCH* m’a été refusée pour le changement du véhicule (automatique) ainsi que pour l’installation de l’ascenseur. Des frais lourds mais essentiels à mon autonomie. Là encore, c’est mon mari qui a payé. 

> Le pire, c’est d’être tiraillé entre l’injustice de cette dépendance et l’impression de chance d’avoir un toit sur la tête et un frigo rempli.  

Aujourd’hui, je suis triste de me dire que nous aurions pu faire des choix de vie différents si j’avais touché l’AAH durant toutes ces années. Mais ne pouvant changer le passé, j’aime espérer qu’enfin le calcul change et que

> la loi de désolidarisation des revenus du couple voit enfin le jour, que je puisse un jour alléger le quotidien de mon mari, comme lui le fait depuis le début pour moi. 