---
title: "«Je n’arrive pas à me projeter dans la vie avec quelqu’un, car je sais que si je suis en couple mon AAH saute»"
author: "Sabine"
date: "2021-04-09"
categories: [dépendance financière, dignité, justification, renoncement au couple]
---

Bonjour, je m’appelle Sabrine. J’ai l’AAH depuis 25 ans suite à un accident de la circulation en moto où j’étais passagère. J’ai eu pas mal de séquelles et c’est pour cela que je suis handicapée et que je touche l’AAH. Je n’arrive pas à me projeter dans la vie avec quelqu’un, car je sais que si je suis en couple mon AAH saute.

> J’ai déjà assez de difficultés à me reconstruire, je ne veux pas entraîner un éventuel ami dans mes problèmes financier et lui demander de financer mes dépenses quotidiennes tout en ayant à me justifier.

J’estime qu’il n’y serait pour rien dans mes problèmes. J’estime avoir le droit d’avoir un minimum pour vivre sans devoir me justifier, alors oui je reste et vis toute seule car je ne vois pas l’avenir à deux. Je verrais autrement si on pouvait garder l’AAH. Voilà mon histoire… 