---
title: "«Tout en continuant à assurer quotidiennement mon rôle d’aidante...»"
author: "Catia"
date: "2021-05-02"
categories: [aidant, épuisement, impossibilité de travailler, injustice, précarité, privation]
---

Mon conjoint est reconnu handicapé à 80 %, il a récemment perdu 700 euros d’AAH et 100 euros de Majoration pour la Vie Autonome (le versement de la MVA étant conditionné au fait que l’adulte handicapé perçoive l’AAH à taux plein) car notre foyer est depuis cette année au-dessus du plafond de revenus pour un couple sans enfant, ce plafond est actuellement fixé à 1630 euros de revenus par mois pour deux personnes. A noter que ce plafond a été baissé par le gouvernement actuel au même moment où l’AAH était revalorisée.
Aux yeux de la loi mon salaire de 1660 euros nets est trop élevé pour que mon conjoint ait le droit de continuer à percevoir à taux plein son unique revenu de subsistance qu’était l’AAH, soit 902 euros euros par mois.

> C’est une grande injustice car de ce fait nous basculons tous les deux dans la précarité financière :

nous devons désormais vivre à deux presque uniquement sur mon seul salaire mon mari ne touchant plus que 200 euros d’AAH (ce qui est moins que le montant mensuel du RSA).

> Nous nous aimons et nous ne voulons pas nous séparer car nous sommes ensemble depuis très longtemps, avant même le diagnostic du handicap.


Mais cette situation est très difficile à vivre pour nous deux : mon conjoint était déjà dépendant physiquement de moi du fait de son handicap et il l’est maintenant aussi financièrement. **De mon côté le fait de devoir assumer seule financièrement pratiquement l’ensemble des dépenses de notre foyer tout en continuant à assurer quotidiennement mon rôle d’aidante est très éprouvant.**

Dans l’absolu, je ne serais pas contre le fait d’assumer seule les membres de mon foyer si mon salaire me le permettait mais ce n’est malheureusement pas du tout le cas car les plafonds en vigueur fixés par la loi sont si bas que nous devons vivre à 2 avec 1800 euros en étant locataires. Pour me permettre d’assumer seule les dépenses mensuelles de mon foyer il faudrait que les plafonds pris en compte pour un couple soient relevés à au moins 2 fois le SMIC net (hors AAH).

> Malheureusement la réalité c’est que nous avons beaucoup de mal à « joindre les deux bouts » et qu’avec 1800 euros par mois nous bataillons pour surnager au dessus du découvert

(notre seul loyer mensuel s’élève à 800 euros car mon travail se situe dans une grande ville et ne me permet pas d’habiter à la campagne où les loyers sont moins chers). Ce qui est encore plus difficile à supporter c’est de ne pas voir le bout du tunnel, de ne pas avoir de prise sur cette situation que nous n’avons choisie ni l’un ni l’autre, de se dire que notre situation financière précaire n’évoluera favorablement que si la loi change grâce aux députés :

> mon salaire n’augmentera pas et mon conjoint demeurera handicapé et donc empêché d’accéder à un emploi rémunéré comme les personnes valides.


Aussi nous sommes mobilisés (signature de la pétition sur le site du Sénat puis des 3 pétitions en ligne sur le site de l’Assemblée Nationale, sollicitation des députés et des grands médias) pour que cette injustice cesse car le vote des députés en faveur d’un changement de la loi le 17 juin prochain est notre seul espoir pour avoir une vie digne et un futur plus serein. Parce que ce n’est pas juste d’imposer aux adultes handicapés et à leurs conjoints souvent aidants de vivre en mode « survie financière », **sans aucun pouvoir d’achat, dans la crainte du découvert au moindre achat de médicament, acte médical non remboursé, cadeau d’anniversaire, place de cinéma ou paire de chaussures neuve.**