---
title: "«Je m’interdirai de vivre sous le même toit !»"
author: "Alexis"
date: "2021-05-14"
categories: [renoncement, renoncement au couple]
---

J’ai vécu  beaucoup galères de vie et de travail depuis mon plus jeune âge. J’ai vécu en couple dix ans, avec une femme paraplégique. Bien entendu, on m’a supprimé les aides que j’avais. Bien que reconnu travailleur handicapé sans que cela ne se voit.

Pendant quelques années, j’ai conduit et accompagné des personnes handicapées pour des associations et entreprises privées. Tout cet ensemble de rencontres et de vies m’a ouvert ma vision sur les différents handicaps et âges existants dans notre société actuelle.

Depuis quelques années, j’effectue les démarches nécessaires pour obtenir l’AAH, et à côté, j’ai un petit job à responsabilités. Aujourd’hui je suis célibataire, mais le jour où j’aurai de nouveau une amoureuse, je m’interdirai de vivre sous le même toit !

> Je n’ai pas le choix, pour maintenir mon équilibre personnel et financier de travailleur précaire.Voilà à quoi je suis condamné, solitude à perpète : jusqu’à la fin de ma vie.

Peut être que c’est ça la France, bien compliquée et prise de tête, malgré un beau pays et des personnes formidables.