---
title: "«Deux articles et un décret qui font que je passe à travers les mailles du filet généraliste»"
author: "Alain"
date: "2021-05-05"
categories: [aidant, amour]
---

Tout a commencé il y a un peu plus de trois ans. Ce serait un peu fastidieux pour moi de vous raconter cette histoire dans toutes ses longueurs et pour vous de la digérer facilement, aussi je vais tenter de faire court et simple. Pour ceux, pressés, qui voudraient un résumé en un mot, ils se contenteront de celui-ci :

**CAFKAIEN**

Que les autres veuillent bien me suivre. Soyez attentifs et gaffe à la marche en sortant de l’escalier !

Vous le savez, l’obtention de l’AAH (Allocation Adulte Handicapé) est liée aux ressources du foyer. Nous avons d’ailleurs été plus de 100 000 à signer la pétition sur le site du Sénat pour espérer que les choses changent et que le salaire du conjoint ne réduise ou ne supprime, n’invalide en somme, les 903,60 € de cette aide qui, malgré sa revalorisation tous les mois d’avril  (0,90 €/mois cette année), reste toujours, « quoiqu’il en coûte ! », en deçà du seuil de pauvreté ! Une petite vidéo de Kevin Polisano illustre bien Le prix de l’amour pour  une partie de ces citoyens.

Pour moi les choses sont différentes, et c’est l’AFM (Association Française contre les Myopathies) qui m’a parlé de deux articles et un décret qui font que je passe à travers les mailles du filet généraliste  :  j’ai la chance que mon « état nécessite à la fois une aide totale pour la plupart des actes essentiels et une présence constante ou quasi constante », et que, dans ce cas, je peux, j’ai le droit de salarier mon épouse en tant qu’Auxiliaire de vie et par conséquence la CAF  (Caisse d’Allocations Familiales) ne doit pas tenir compte de son salaire. C’est aussi simple que cela !

Alors quand celle des Bouches-du-Rhône a réduit mon AAH en janvier 2018, un an plus tard elle la supprimera, je conteste cette décision auprès de leur Commission de Recours Amiable en leur donnant tous les arguments juridiques. À signaler tout de même que ces textes se trouvent dans le Code de l’Action Sociale et des Familles et dans le Code de la Sécurité Sociale qui devraient, pensais-je benoîtement, être les livres de chevet de cet organisme. Malgré cela, quelques huit mois plus tard, je reçois une notification de refus qui se réfère à l’Article R-821-3 alors que moi je parlais de l’Article R-821-4. C’est tout de même ballot de ne pas avoir lu un peu plus loin ou alors n’est-ce pas plutôt

**CAFKAIEN !**

Je formule alors une demande de recours contentieux au Tribunal de Grand Instance de Marseille. L’audience a lieu 20 mois après cette requête, le 2 octobre 2020. Je n’ai pas pris d’avocat et préparé deux petites pages de texte où j’ai commencé comme ceci :

En fait, je ne comprends pas bien pourquoi je suis ici ! Pour un simple citoyen, « nul n’est censé ignorer la loi ». Alors pourquoi la CAF des Bouches-du-Rhône n’applique pas les articles et décrets… 

Je n’ai pas pu aller plus loin car le défenseur de la CAF m’a coupé en reconnaissant leur erreur, que j’étais un cas particulier, qu’ils allaient me contacter, calculer puis me verser ce qu’ils me devaient. La présidente ne m’a pas laissé finir en fixant une deuxième audience quelques mois plus tard.

J’étais content d’avoir eu gain de cause mais en même temps frustré de ne pas avoir pu débattre davantage, sortir quelques vérités même si elles sortaient du cadre strictement juridique.

Entre les deux rendez-vous, suite au paiement rétroactif et le rétablissement de mon AAH, je constate, en me connectant sur mon espace CAF, que je n’ai plus de droit pour le mois de décembre. J’écris, on me demande notre déclaration d’impôt, à la suite de quoi on me réplique qu’en fonction de nos ressources conjointes, supérieures au barème fixé, je n’ai pas droit à l’AAH ! Retour à la case départ !

Bizarre et incompréhensible me direz-vous ?! Je dirais plutôt 

**CAFKAIEN !**

D’autant plus que finalement ils me verseront le subside mensuel mais à chaque fois avec un retard à l’allumage, avec un effet pochette surprise assez perturbant. 

Le jour de la deuxième audience, je retrouve le même défenseur de la CAF mais une autre présidente. Celle-ci veut savoir en premier lieu si j’ai bien reçu la somme due et si le compte est bon. Je réponds « oui » mais qu’il y a eu plusieurs ratés par rapport au paiement mensuel et que je ne souhaite pas refaire le même parcours.

> La partie adverse dit qu’elle ne comprend pas bien ce qui s’est passé et que leur système informatique ne prend pas en compte le cas particulier que je suis ; un sur 10 000 ! Cette fois, c’est moi qui l’interromps en demandant d’où il peut bien sortir ces chiffres, ces statistiques ! Il bafouille un peu et répond que c’était pour dire que j’étais vraiment un cas rare.

Devant l’insistance de la présidente, il me conseille alors, si cela se reproduit, de téléphoner directement à la direction de la CAF pour régler le problème.

Évidemment, je ne peux m’empêcher de bondir, tout en ne bougeant quasiment pas d’un millimètre. Cet exercice myopathique, à force d’entraînement, m’est devenu naturel et produit souvent son petit effet ; en tout cas aujourd’hui, il est largement remarqué par une assistance médusée autant qu’interloquée. J’interromps donc une nouvelle fois le quidam en faisant remarquer à la présidente, qui le sait pertinemment au vu des yeux ronds qu’elle lui tance, que ce genre de numéro téléphonique ne se trouve pas sous le sabot d’un cheval et que de toute façon je ne suis pas adepte d’équitation. Je ne garantis pas la transcription exacte des échanges mais la teneur y est. 

Depuis, je regrette amèrement de n’avoir eu la présence d’esprit, à ce moment-là, de souligner le caractère CAFKAIEN du conseil donné par le représentant de la KAF !

Joueur d’échecs devant l’éternel, je sais que j’ai les blancs : c’est moi qui ai saisi cette juridiction et mon rôle est de prendre l’initiative, d’attaquer, d’acculer l’adversaire dans ses derniers retranchements pour avoir toutes les chances de mater ! Quel plaisir de voir le représentant de la défense de plus en plus mal, manquant d’air, d’espace, bredouillant les mêmes choses pour tenter de justifier, d’expliquer leur erreur.

> Je rappelle par la même occasion que je ne suis pas un cas si isolé que cela, d’ailleurs Renaud de l’AFM qui m’accompagne parle d’affaires analogues en 2013 et 2018,  et que beaucoup d’autres allocataires n’ont pas l’information, l’énergie, le temps et les compétences pour mener ce genre de combat de longue haleine. Il faut aussi que les choses changent pour eux !

A la fin, la présidente qui avait lu mes «conclusions » veut savoir si j’estime que la CAF a commis une faute. Je clame « Oui bien sûr ! » et réclame des dommages et intérêts : 1.650 € que je verserai à l’AFM-Téléthon et qui correspondent à 50 € pour chacun des 33 mois pendant lesquels j’ai dû faire face à cette situation précaire.

J’expose également trois demandes plus généralistes concernant les services informatiques de la CAF qui doivent évoluer, tout comme leurs commissions de recours afin qu’elles étudient avec soin et rapidité les contestations exposées et aussi l’information qu’elle pourrait communiquer sur ces droits particuliers trop souvent méconnus de bon nombre d’allocataires.

Le tribunal a rendu son jugement le 30 mars en se déclarant «incompétent pour statuer sur l’injonction de la caisse à adopter un service informatique adapté» mais en condamnant la CAF à payer l’intégralité de la somme demandée en réparation du préjudice !

Pour conclure, dire, rappeler qu’il faut se battre encore et toujours lorsqu’on est victime d’une injustice, ne pas flancher, ne pas se résigner, être patient, pugnace, que cela en vaut souvent la peine pour soi mais aussi pour les autres et que cela participe de toute façon à sa propre évolution et à celle par ricochet de notre société. Et puis quelle satisfaction, quelle récompense lorsque David terrasse Goliath !

Alain Comoli
