---
title: "«Ce calcul de l’AAH retentit même sur les enfants»"
date: "2021-04-07"
categories: [dépendance financière, disputes, divorce, enfants]
---

Le handicap est déjà difficile pour la personne mais il impacte toute la famille. Le conjoint qui doit assumer seul les dépenses financières du logement, de l’éducation et de l’achat de vêtements des enfants, et du coup c’est source de disputes, de crises conjugales où les enfants se retrouvent mêlés sans le vouloir.

> Pour les enfants c’est déjà compliqué de voir leur mère galérer pour faire la moindre activités avec eux, de devoir renoncer à certaines sorties car impossible à suivre pour maman, mais quand en plus maman se fait engueuler par papa car elle a acheté 2 jogging à 5€ pour qu’ils n’aillent pas à l’école avec des pantalons troués… ça n’est pas simple

Le fait de prendre en compte les revenus du conjoint dans un le calcul de l’AAH, fait qu’à 37 ans je n’ai aucun revenu car AAH à 0. Mon mari me le fait payer ! Je fais toutes les tâches ménagères, m’occupe des enfants de 6 et 9,5 ans 24h/24 et 7j/7. C’est moi qui les amène à l’école, aux activités, aux anniversaire, à la piscine… Bien que je me déplace en fauteuil à l’extérieur.

> Et maintenant il m’a donné 6 mois pour trouver un travail au péril de ma santé, car même à mi temps il me faut un poste qui respecte mes énormes contraintes, ce que je n’ai pas trouvé en 4 ans, malgré une reconversion professionnelle.

Ma maladie m’a rendue handicapée et avec ce mode de calcul m’a enlevé toute autonomie financière, provoque des crises conjugales, difficile à vivre pour tous le monde mais sans mon mari je serais à la rue avec mes 2 enfants.