---
title: "«698,52€. C’est le prix de notre amour»"
author: "Stéphanie"
date: "2021-03-26"
categories: [décence, dépendance financière, fardeau, fatigue, injustice]
---

5 février 2021, le couperet tombe. 698,52€. C’est le prix de notre amour. Aussi grand puisse-t-il être, il ne pèse pas bien lourd …encore 50€ de moins, cette année, sur mon allocation d’adulte handicapée.

> 50€? Ce n’est pas grand-chose, et beaucoup à la fois me direz-vous. C’est un plein d’essence ou une quinzaine de repas à la cantine pour Gabin.

Pourtant, le système allocataire familial décide que, parce que l’on s’aime et que l’on vit sous le même toit, les revenus de ton conjoint, qui avoisinent les 1600€ par mois, sont trop « élevés » et peuvent nous faire « vivre décemment ».

> Ce qu’on me donne bien gentiment pour « palier de façon compensatoire à ma situation de handicap » dépend directement de ce que mon mari reçoit en salaire…

Donc, je ne suis pas encore assez dépendante physiquement de lui ? Il faut encore que je le sois financièrement ? En deux années, j’ai perdu presque 400€ juste parce que c’est le système qui le décide. Comment ne pas être en colère ?

> Comment puis-je me sentir bien, vis à vis de mon mari ? Ne pas se sentir comme un fardeau, dans une situation pareille, est quasi impossible.

Quand comprendra-t-on que les personnes atteintes de handicap ont leur propre individualité humaine ? Elles ont aussi des capacités, certes à adapter, mais tout aussi valables que les personnes valides, à proposer à la société pour être rémunérées, ou bien, lorsque le handicap les prive de cette possibilité, qu’elles ne l’ont pas choisi, faut-il rappeler **que leur handicap ne dépend pas de leur conjoint ?  Je suis fatiguée de me débattre dans ce piège insensé**. Je suis épuisée par cette injustice… Une injustice discriminatoire envers les allocataires de l’AAH ?