---
title: "«J’ai eu envie de mourir, oui mourir ! M’effacer pour les miens. Je n’avais plus rien à offrir»"
author: "Soraya"
date: "2021-04-07"
categories: [dépendance financière, dépression, indignité, souffrance, suicide, tutelle]
---

Malgré le diagnostic de ma maladie orpheline en 2006, j’ai lutté des années pour continuer à travailler, jusqu’à empirer mon état… Je suis depuis reconnue handicapée et on m’a expliqué que je ne travaillerai plus. S’en est suivie une dépression car je ne pouvais accepter cette nouvelle vie. J’ai découvert le monde du handicap et c’est effrayant… Des démarches interminables et lourdes s’en suivirent. 

Je suis aujourd’hui dépendante physiquement de mon compagnon, car parfois il doit me laver. Il fait la cuisine avec nos deux filles, les courses, le ménage. Les revenus ayant baissé… J’ai donc fait la demande d’AAH contrainte et forcée. J’ai eu envie de mourir, oui mourir ! M’effacer pour les miens. Je n’avais plus rien à offrir, sauf la « charge d’une handicapée ». Plus de vacances, plus de cinéma, de restaurant. Cette allocation était tout de même la bienvenue pour mon foyer car nous sommes 4.

Ma cadette a eu 20 ans et là… deuxième claque ! Mon AAH était pour ainsi dire supprimée ! Je ne touche plus que 21€90 par mois car ma fille a eu 20 ans. Quel est le rapport ?!

> Résultat, je me retrouve complètement dépendante de mon conjoint et de son salaire. Je me sens humiliée, inutile. Naïve, je pensais que c’était une allocation pour moi, pour compenser mon handicap, ma souffrance physique et psychologique, mais surtout pour le fait que je ne pourrai plus jamais travailler.

Et là, je découvre que ce n’est absolument pas ça ! La CAF considère que c’est un revenu ! Hallucinant ! La loi m’enlève tout ce qui me restait : ma dignité, et c’est insupportable ! La loi m’enlève mon indépendance.

> À 52 ans, j’ai le sentiment d’être mise sous tutelle, et c’est insupportable.

Jamais je n’aurais imaginé qu’on puisse nous traiter aussi mal. Récemment, j’ai reçu un courrier envoyé par le département, pour me signaler à la mairie de ma commune comme personne vulnérable… J’ai jeté ce papier par colère ! Et par honte… Il faut absolument nous rendre notre droit à l’autonomie, à l’individualité. Je ne veux plus être une charge pour mon compagnon, il en fait déjà tant ! 

**J’espère que mon témoignage permettra de vous faire comprendre ce qu’est pour nous l’AAH.**