---
title: "«Sa maladie est évolutive alors la situation est urgente : rendez-lui son rôle de père, de mari, un certain pouvoir de décision !»"
author: "Anabelle"
date: "2021-03-29"
categories: [dépendance financière, dignité]
---

Mon mari est malade depuis au moins cinq ans mais nous n’avons diagnostiqué la maladie qu’en 2019. Il s’agit d’Alzheimer à 51 ans… Reconnu invalide à plus de 80% par la MDPH en mai 2019, il a l’AAH à vie… Sauf qu’il ne touche rien, si… une vingtaine d’euros. Je suis évidemment au dessus du plafond et dois donc assumer seule la maison, les voitures, une étudiante, les travaux qu’il ne sait plus faire depuis bien longtemps etc,… Pas de pension d’invalidité car il ne travaillait plus depuis plus de deux ans.

> J’ai pensé à le quitter, oui, pour qu’il puisse encore avoir le sentiment d’exister et être un minimum autonome financièrement pour le peu de conscience qu’il lui reste encore. Nous en avons discuté longuement, mais c’est vraiment trop nous demander.

Je l’ai effectivement épousé pour le meilleur et pour le pire, je ne l’ abandonnerai pas. Cette dignité, il l’a perdue en grande partie déjà, lui qui était si fier. Toucher une AAH convenable lui permettrait de retrouver une partie de cette dignité et participer à la vie de sa famille.

> La maladie va tout lui voler bientôt, laissons le laisser encore une trace, se sentir avoir encore de l’importance.


Merci à ceux qui se battent.