---
title: "«La situation actuelle organise la dépendance conjugale des personnes handicapées»"
author: "Sylvie"
date: "2021-03-27"
categories: [bilan, dépendance financière]
---

Lorsque nous nous sommes mis en couple dans l’appartement de mon conjoint, nous tenions à partager les frais domestiques à égalité. Je suis en invalidité, je n’ai pas la possibilité de travailler pour améliorer mes revenus. Tant que je touchais l’AAH, j’atteignais des revenus de l’ordre de 850€ par mois, ce qui me permettait d’être indépendante financièrement de mon conjoint. Aujourd’hui, après un an seulement sans cette aide, voilà le bilan :

- Je ne peux plus participer aux frais domestiques courants,
- Je n’ai plus les moyens de financer des cours de sport, qui sont absolument nécessaires au traitement de ma pathologie,
- J’ai du demander des aides familiales pour payer les frais liés à mes rendez-vous médicaux hors de ma ville,
- Je n’ai plus les moyens de financer aucun loisir,
- Je ne peux pas prévoir de thermalisme ou autre soin peu remboursé.
- Précisons que mon conjoint et moi ne sommes ni mariés, ni pascés, nous ne possédons pas de compte joint : nous ne partageons en aucun cas nos finances, et n’avons aucune existence administrative officielle en tant que concubins, si ce n’est auprès de la CAF.

> La situation économique dans laquelle je me trouve actuellement m’oblige à prier mon conjoint de bien vouloir m’aider financièrement, lui qui m’aide déjà à m’habiller, me laver, faire à manger, faire le ménage, les courses…

Le droit à l’AAH est évalué en fonction de nos situations individuelles, à partir de questionnaires médicaux et de descriptifs de la qualité de vie personnels très pointus, avec pour objectif le maintien de l’autonomie :

> en rendant nos allocations tributaires des revenus de nos partenaires, la situation actuelle organise la dépendance conjugale des personnes handicapées.