---
title: "«Les conséquences sur ma santé ne valent vraiment pas 613€ par mois»"
author: "Mégane"
date: "2021-04-19"
categories: [ambition professionnelle, choix de vie, culpabilité, souffrance, utopie
]
---

J’ai 38 ans et j’ai droit à l’AAH. Après calcul de la CAF, mon allocation est de 0€. En effet, je suis mariée. Je travaille à mi-temps par obligation. Clairement, je travaille uniquement à cause de ce manque d’AAH, je n’ai pas le choix ! Et quoiqu’il en soit, je n’ai aucune indépendance, ni latitude financière.

Je suis dans un état tel qu’il m’est impossible d’avoir un semblant de vie « normale ». Je travaille en 2 jours non consécutifs évidement. Je ne me remets jamais entre les deux.

> Je repousse continuellement mes limites.

Je souffre beaucoup et tout le temps. Mes heures de travail ne font qu’accentuer mes douleurs, donc ma fatigue. Je prends énormément sur moi pour supporter tout ça.

> Je trouve cela injuste et révoltant d’être dans ma situation. Les conséquences sur ma santé ne valent vraiment pas 613€ par mois. Je gagne donc ce petit salaire au prix d’une fatigue extrême et de douleurs intolérables.

Si je prenais des antalgiques puissants en conséquence, je ne pourrais pas travailler bien évidement. Je n’ai pas de vie. Mes actions se résument à travailler et accomplir tant bien que mal le minimum de tâches ménagères. J’aimerais pouvoir me projeter, avoir des activités ! Mais mon état ne le permet pas. Je n’ai pas de vie familiale, je culpabilise beaucoup vis-à-vis de mes enfants (16 et 13ans). J’ai fait une croix sur quelconque ambition professionnelle par lucidité. J’aurais aimé ne pas passer à côté de ma vie.

Si j’avais l’opportunité d’avoir le luxe de ne pas travailler, je pourrais retrouver un semblant de santé. Mais ce n’est pas possible.

> Depuis des années je subis, et l’idée d’individualiser l’AAH me paraît utopique. Peut-être cela deviendra réalité.
