---
title: "«Pouvoir, au moins, maitriser l’aspect financier à défaut du physique et du mental»"
author: "Fernando et Claire"
date: "2021-03-26"
categories: [choix de vie, dépendance financière, dignité, divorce, fardeau, grève de la faim, indépendance, liberté, SOS]
---

## Fernando

Mon épouse et moi sommes amoureux depuis 30 ans, mariés depuis  17 ans. 3 enfants. Tous à charge puisque les grands sont en études et le plus petit a 4 ans. Mon épouse est handicapée à 80 % depuis plusieurs années et touche actuellement l’allocation pour adultes handicapés.

> Faut-il que nous divorcions afin qu’elle ne perde pas son autonomie financière ?

Elle angoisse à l’idée de perdre son AAH, son autonomie, lorsque les grands ne seront plus comptés à charge et si mon salaire venait à évoluer. Nous avons déjà du mal à boucler les fins de mois, nous ne partons jamais en vacances et ne faisons aucune sortie. Elle se sent déjà comme un poids à cause de ses difficultés. Je dois presque la forcer à s’acheter ce dont elle a besoin.

> Comment peut on retirer sa dignité à un être humain qui n’a pas demandé son handicap ? Qui ne réclame pas la charité mais simplement le droit de vivre en autonomie et non au crochet de quelqu’un ?

Même si je l’aime et que jamais elle ne sera un poids pour moi, elle le ressentira ainsi. C’est certain. Elle est fragile physiquement et moralement, mais **elle a décidé qu’elle ferait la grève de la faim si l’AAH lui est retirée. Je suis horrifié.**

S’il vous plait, ne lui retirez pas sa dignité.

## Claire

Je m’appelle Claire, 44 ans, mariée depuis 17 ans mais en couple avec mon mari depuis 1991. Nous avons 3 enfants de 20, 18 et 4 ans. Je suis handicapée à 80 % et actuellement je touche l’AAH. Je suis pour le moment à peu près autonome financièrement.

Mais, lorsque mes deux grands ne seront plus à charge ? Que mon mari aura un salaire augmenté ? Devrais-je redevenir un boulet ? N’avoir plus aucun revenu ?

> J’aimerais pouvoir travailler, avoir des loisirs et des plaisirs, mais je ne peux pas.

**Je suis reconnaissante de pouvoir toucher cette allocation sans laquelle nous ne pourrions pas faire face aux dépenses liées à mon handicap, au manque de salaire également.** Si je ne l’ai plus , je perdrai ma dignité, mon indépendance, la possibilité de faire des choix, des achats personnels. Comment peut t-on refuser  de nous laisser notre dignité ? Je souffre physiquement et moralement déjà. Pourquoi ne pas désolidariser l’AAH ? Vous voulez des raisons ? 

> La liberté, le choix et l’indépendance. Pouvoir, au moins, maitriser l’aspect financier à défaut de physique et du mental. Ne pas être soumis.  Pouvoir vivre avec dignité.

