---
title: "«Nous avons même pensé à divorcer pour retrouver mon AAH et ma dignité»"
author: "Yvonne"
date: "2021-03-25"
categories: [dépendance financière, dépression, dignité, divorce]
---

Je m’appelle Yvonne, j’ai 58 ans, et je suis en situation de handicap invisible depuis 1997. Mon taux de handicap est de 80%, et je suis dans l’impossibilité de travailler. Je suis mariée, sans enfant, et mon mari travaille. Depuis 1 an, il dépasse le barème d’état et la CAF a supprimé mon AAH. Je me retrouve donc sans ressource et à la charge totale de mon mari ! 

> Je suis en dépression car je dois toujours demander de l’argent à mon mari si je veux quelque chose pour moi. Nous avons même pensé à divorcer pour retrouver mon AAH et ma dignité…

Je ne peux plus rien acheter pour moi, je ne peux plus me faire plaisir. Comment peut-on nous abaisser à ce niveau ? Nous nous battons tous les jours et tous les mois pour survivre, on ne peut pas vivre avec un  seul salaire.

> Mon mari a été obligé de refuser de faire des heures supplémentaires pour abaisser son salaire. 

De plus, nous n’avons droit à aucune aide alimentaire, Restos du Cœur, CCAS , Croix-Rouge… Même pour avoir une aide des service sociaux pour nous aider à payer une facture d’eau ou EDF, cela nous est refusé car le seul revenu de notre foyer est trop haut ! On ne finit pas les mois, on se nourrit comme on peut.

> Comment voulez-vous que l’on vive dignement ?! Cette situation est moralement très difficile et est responsable de ma dépression.