---
title: "«Mon homme est obligé d’acheter mes petites culottes, mes garnitures périodiques etc.»"
author: "Elodie"
date: "2021-03-28"
categories: [dépendance financière, honte]
---

Je suis handicapée à plus de 80 % et en incapacité totale et permanente à la conduite et à une reprise d’emploi. J’étais déjà auparavant en RQTH et suite à deux AVC, dont le premier a eu lieu sur mon lieu de travail et qui m’a valu d’être licenciée à ma sortie des soins intensifs… j’ai dû digérer qu’en plus de mon handicap j’étais désormais dépendante physiquement…

Suite à la naissance de notre enfant, mon conjoint a été rattaché et j’ai perdu mon AAH. Je n’ai désormais plus que 500 € de pension d’invalidité par mois et mon compte est en situation financière fragile. 

> Je suis devenue dépendante financièrement de mon conjoint et à sa charge… Nous avons une bouche de plus à nourrir, et moins de ressources qu’avant. 

Je dois demander à mon conjoint pour toute dépense, vu mes faibles finances… mon homme est obligé d’acheter mes petites culottes, mes garnitures périodiques, etc… même en aimant et en se sachant respectée… On se sent honteux de devoir demander et ramené au statut d’un enfant…

J’ai l’impression d’être sous tutelle.
Voilà pour mon témoignage. 