---
title: "«Moi, femme, je me retrouve sans choix, sans espoir»"
author: "Patricia"
date: "2021-05-08"
categories: [dépendance financière, dépression, impossibilité de travailler, infantilisation, mendier]
---

Je suis une maman de 46 ans, et depuis 3 ans je souffre de cancers, fibromyalgie et neuropathie. D’une vie active, je suis passée à une vie de maman solo avec 3 filles, sans pension alimentaire, et dépendante de mon nouveau compagnon.

Oui, comme une enfant, je dois demander, quémander mon petit argent de poche !

Lui fait de son mieux, il travaille et a mes filles et moi à charge. Il n’a aucune reconnaissance, ni même pour ses impôts, mais par contre toutes les obligations ! Il paye chaque mois deux pensions alimentaires d’une autre union. Il a un salaire correct, et pourtant on vit en dessous du minimum de pauvreté.
Si j’étais valide, je pourrais espérer changer la situation en trouvant un emploi. Mais non, ce n’est pas le cas ! Je suis devenue dépressive, dépendante financièrement et ce pas par choix, oh non !!!
Comment peut t-on nous laisser ainsi, en situation de mendicité ?!

Psychologiquement j’ai déjà pensé au pire, j’ai essayé le pire, vu que je suis un boulet qui pompe et ne sert à rien… Heureusement je suis aidée psychologiquement maintenant.

Acheter même une culotte à ma fille passe par mon compagnon, c’est violent, vraiment très violent !

Il n’est pas leur père. Il faut qu’on nous entende ! Si je demandais le RSA qui serait refusé à cause des revenus du conjoint je trouverais ça normal. Pourquoi ? Car  je pourrais me débrouiller pour travailler, quand on veut, on peut, puisqu’on est valide ! 

> Mais en invalidité, le « quand on veut, on peut » n’est pas possible ! J’en pleure et encore je cache mon ressenti aux gens. Moi, femme, je me retrouve sans choix, sans espoir.

C’est bête mais même pour dire merci à mon compagnon qui est aussi mon infirmier, mon homme de ménage, mon taxi… Je ne peux lui acheter un cadeau qu’avec ses sous. J’essaie de me débrouiller, mais c’est très dur. Ma peau porte les stigmates de mon mal être, et mes filles souffrent avec moi.

> Une vie où les jours passent un à un, où on se bat pour essayer de moins souffrir. Nous sommes les oubliés, nous vivons dans la honte, on perd notre honneur, nous n’avons plus aucune indépendance .