---
title: "«Je veux que mon conjoint me regarde comme sa compagne, pas comme une lourde facture»"
author: "Sonia"
date: "2021-05-08"
categories: [20 ans enfant, dépendance financière, humiliations]
---

Je suis une femme, j’ai 51 ans et je touche l’AAH depuis quelques années. Ma première demande avait été refusée car je travaillais avec un tout petit salaire, en plus de celui de mon conjoint. Suite à la naissance de mes deux autres enfants et l’évolution de mon handicap, je dépendais de plus en plus de mon conjoint. Et là, notre relation a complètement changé (en pire). Cela a duré quelques temps. Suite à ça, j’ai fait une autre demande, avec les conseils de mon médecin et elle a été acceptée. J’ai pu toucher l’allocation complète.

> Ainsi, j’ai pu participer aux dépenses du foyer, faire les soins complémentaires qu’il me fallait (séances de kiné, quelques soins dentaires).

J’avais même pu faire quelques sorties cinéma avec mes enfants et leur offrir des cadeaux à leur anniversaire. Malheureusement, ça n’a pas duré. Mon conjoint a été augmenté de 200€, et là, mon AAH a baissé à 447€ ! Puis ma fille a fêté ses 20 ans, et là aussi, encore une autre chute.  Je ne touche plus que 217€  qui me servent à payer mes factures.  

> Ma vie, depuis, a changé, je ne peux plus participer aux dépenses de foyer, plus de cadeaux pour les enfants, plus de soins.

J’ai annulé beaucoup d’examens car trop coûteux. A cela se rajoutent les réprimandes et les conflits avec mon conjoint. L’humiliation devant mes enfants, comme si je ne servais à rien. A plusieurs reprises, j’ai pensé à la séparation, mais je suis coincée ! Car comment faire pour élever mes enfants avec 217 €  ? Je ne veux plus être une charge pour ma famille, ni physiquement, ni financièrement. Je ne veux plus demander de l’argent à mon conjoint ou encore pire, à ma fille étudiante, pour offrir un cadeau d’anniversaire à l’un ou à l’autre.

**Je veux que mon conjoint me regarde comme sa compagne, pas comme une lourde facture. La déconjugalisation des revenus doit se faire, cette loi doit passer.**