---
title: "«Je suis devenue facile à dénigrer !»"
author: "Nadia"
date: "2021-05-08"
categories: [dépendance financière, double peine, impossibilité de travailler, isolement, violences conjugales]
---

Je suis maman de 3 enfants, je vis en couple depuis 10 ans. J’ai toujours travaillé, mais voilà  en 2018 j’ai commencé à avoir des symptômes handicapants et invalidants parfois. Je suis atteinte d’une maladie neurologique mais complexe et en cours de diagnostic encore en 2021. Je bénéficie d’un suivi en centre anti douleur. Je dois arrêter de travailler en 2019, par la force des choses, à cause de douleurs intenses chroniques, des pertes de mobilité et chutes… le début de l’enfer ! On reconnait mon handicap en 2018, on m’ouvre les droits à l’AAH à taux plein, puisque mon conjoint venait de perdre son travail. 

Pour moi qui était très active et entourée, j’ai subi l’isolement. En 2021 je ne touche plus l’AAH, pourquoi ? Parce que mon conjoint est chef d’entreprise ! Mais moi ? Moi je suis toujours avec cette maladie, ces douleurs, chutes, cette fatigue intense, l’isolement. Un couple qui est détruit car je suis devenu dépendante financièrement, bien malgré moi ! 

> Car plus rien ne va, je ne suis plus « celle qui ramenait de l’argent », qui gagnait sa vie, qui travaillait ! Je suis devenue facile à dénigrer ! « Je ne sers à rien » et « j’ose répondre, moi qui ne ramène rien à la maison », le manque de respect parce que « je n’ai plus rien à dire », je subis la double peine, pourquoi ?! Car je suis malade et n’ai aucun soutien. 

Je voudrais partir, mais financièrement, je dois choisir entre rester malheureuse dans un couple pour vivre dignement, accepter d’être démolie moralement en plus de la maladie ou partir, et survivre avec 904 euros d’AAH, tout en sachant que je dois subvenir aux besoins de mes 3 fils ! Lequel dois-je sacrifier financièrement ? Celui qui est en sport études et qui coûte plus cher, celui qui veut faire des activités sportives ou celui qui doit passer son permis et avoir une voiture ?
Et comme mes deux aînés ne vivent plus avec moi pour leurs études, je n’ai pas d’aide ou d’allocation !  Et bien je vais devoir me sacrifier encore, car je ne suis qu’une maman malade qui subit des lois de l’État… 

> L'État ne saura jamais ce qu’est la vraie vie de personnes malades ou handicapées !

Au-delà du fait que nous ayons l’AAH calculée sur les bases du revenu du couple, il y a aussi le fait que notre maladie nous empêche de travailler pour avoir un bon niveau de vie ! Notre maladie creuse un fossé, mais on nous jette dedans en faisant de nous des « cas sociaux », avec une rentrée d’argent totalement dérisoire et à peine suffisante pour boucler des fin de mois !

**Me voilà à 39 ans officiellement dépendante financièrement et obligée de subir les violences conjugales qui ne m’aident pas à aller mieux !**