---
title: "«J’ai l’impression d’entraîner de force toute ma famille dans une déchéance sociale»"
author: "Sylvain"
date: "2021-04-26"
categories: [culpabilité, déchéance, dépersonnalisation sociale, humiliation, impossibilité de travailler, peur]
---

J’ai 44 ans. Je suis marié et j’ai trois enfants. J’ai appris récemment que toutes les difficultés que j’avais rencontrées jusqu’à présent étaient liées à un handicap dit invisible diagnostiqué il y a peu. Ce diagnostic, c’est l’autisme de type Asperger et j’ai transmis ceci à mes enfants.


Je travaillais comme aide-soignant titulaire de fonction publique hospitalière depuis 18 ans. Suite à un burn-out sévère, tout s’est écroulé et malgré plusieurs tentatives de reclassement  !  Je sais aujourd’hui que je n’ai plus d’avenir dans ce domaine.

Mon dossier à la MDPH est en cours de traitement et rien ne me dit que l’on acceptera de m’accorder quoique ce soit.
Mon épouse travaille à temps partiel. Je sais que l’AAH que j’ai demandée sera calculée en fonction de ses ressources à elle.

> J’ai travaillé dur en cherchant à m’adapter toute ma vie et à travailler. Si je demande ces aides,  ce n’est ni la charité, ni une volonté de profit sur la société. C’est juste que j’ai atteint mes limites d’adaptation.

Nous avons enfin trouvé la maison qui pourra recevoir mes enfants également neuro-atypiques et nous avons peur de tout perdre.
Je suis pour que l’on ne calcule plus l’AAH en fonction du salaire du conjoint. C’est très humiliant.

> Et j’ai la sensation que les personnes handicapées n’ont ni le droit à l’amour, ni le droit de s’épanouir, ni le droit à vivre dignement.

Comme si être handicapé, alors que l’on n’a jamais demandé à être ainsi, ne suffisait pas. C’est comme si l’on nous punissait d’être ce que nous sommes et que nous ne méritions que la pauvreté et une vie sans liberté d’être aimé et d’aimer.
J’ai très peur de ce qui pourra nous arriver. Personne, même pas les assistantes sociales, ne peut nous dire ce qu’il adviendra de moi, de nous. J’ai l’impression d’entraîner de force toute ma famille dans une déchéance sociale.
**Je vis une dépersonnalisation sociale. Je n’existe plus, je n’ai plus aucune utilité. Et c’est comme si on n’accordait plus la moindre importance à toute personne en situation de handicap.**