---
title: "«Notre vie est faite de précarité, de bouts de ficelles et de découverts»"
author: "Abidin"
date: "2021-03-28"
categories: [dignité, fardeau, précarité, renoncement]
---

MComme beaucoup, lorsque j’ai rencontré celle qui allait devenir ma femme, je ne savais rien du calcul de l’AAH pour les personnes vivant en couple. On était en 2012, je bénéficiais de l’AAH depuis 2007 pour un handicap qui était là depuis ma naissance et pour lequel je n’avais pas souhaité jusqu’à là demander d’aide financière.

> En 2013, on décide d’habiter ensemble et tout se passe bien les premières années.

En 2017, tombe la première réduction de quelques euros, je ne m’inquiète pas trop. En 2020, c’est un coup de massue, je perds 200 € ; cette années 130 euros de plus, c’est la débâcle.
Dès 2018, je me documente, comprends le mode de calcul inique, et écris à Sophie Cluzel, Édouard Philippe et à quelques autres hommes politiques. Mon handicap, lui, est toujours là, toujours plus sévère (ma vue se dégrade continuellement, aujourd’hui mon acuité visuelle est à peine de 1/10ème). Je ne peux plus faire les courses, faire un trajet inconnu, voyager, je ne reconnais presque plus les visages… Je pèse de plus en plus sur mon épouse. En 2016 j’ai combattu un cancer, les effets des traitements demeurent et me handicapent encore davantage. Il y a quelques mois on achète une maison, et là ce sont les APL qui fichent le camp (99 € mensuels de moins) !

> Ma moitié vient de refuser une promotion, car elle n’est plus motivée à travailler davantage pour voir notre pouvoir d’achat stagner et son mari devenir de plus en plus dépendant.

Nous venons de passer l’hiver dans une maison à 14-15° degrés pour tenir le budget dans le vert et j’ai, malgré mon handicap, dû résilier la mutuelle. À 33 et 34 ans, notre vie est faite de précarité, de bouts de ficelles et de découverts alors que mon épouse travaille 28-40 heures par semaine et que moi, je m’efforce de gagner quelques sous en écrivant et en traduisant des textes littéraires.

> Notre couple est solide, mais cette question crée, inévitablement, de plus en plus de tensions.

L’individualisation de l’AAH est une question de logique (le handicap est personnel, le revenu qui en compense les conséquences financières doit l’être aussi), une question de dignité pour tous ceux qui dépendent déjà tant de leur conjoint, une question de justice sociale et d’émancipation des personnes atteintes de handicap.

**Mesdames et Messieurs les députés, le 17 juin prochain, faites preuve d’humanisme et de sagesse, permettez à des dizaines de milliers de personnes de retrouver leur dignité !**