---
title: "«Pourquoi cette « solidarité familiale » nous entraine vers la pauvreté ?»"
author: "Valérie"
date: "2021-04-13"
categories: [20 ans enfant, colère, endettement, parentalité, précariré, solidarité familiale]
---

Depuis 2010, je suis reconnue handicapée à 80 % . Je suis mariée depuis 2001. Mon AAH a donc été réduite dès le début. Ma fille qui est aussi porteuse de handicap a eu 20 ans cette année, et aujourd’hui je perds encore 700 € de mon AAH !  Ma fille étant handicapée, elle vit donc bien encore à notre charge, contrairement au mode de calcul de la CAF ! Elle ne touche pas d’AAH.

> Les temps sont vraiment difficiles, nous sommes 4 à vivre sur le seul salaire de mon mari qui est aussi mon aide au quotidien, comme un auxiliaire de vie. Il prend soin de nos deux enfants aussi.

Aujourd’hui nous avons du mal à joindre les deux bouts, notre loyer est de 750 € .

> Nous allons devoir nous endetter pour pouvoir vivre ! C’est trop dur, les pleurs sont là, je ne le cache pas. Pourquoi cette « solidarité familiale » nous entraine vers la pauvreté ?

Je n’ai pas demandé à ne pas pouvoir travailler, mon état de santé est indépendant de ma volonté, de celle de ma famille. J’espère que le gouvernement va sérieusement se pencher sur notre cas, le cas de milliers de foyers devenus précaires.

**Je suis en colère contre cette injustice !**