---
title: "«Le bel oiseau s’envole au son du chant de l’AAH !»"
author: "Marianne"
date: "2021-03-27"
categories: [choix de vie, dépendance financière, dignité, rêves, solitude]
---

Comme toutes les personnes reconnues handicapées je viens à mon tour témoigner de ma vie de solo forcée ! Reconnue invalide complétée par l’AAH, à 59 ans, la solitude fait partie du quotidien car

> la dépendance financière fait fuir le futur « compagnon  » et le bel oiseau s’envole au son du chant de l’AAH ! 

Qui n’a jamais rêvé troquer sa vie de solo pour une vie de couple ? Et pourtant ce rêve nous est refusé ! C’est inadmissible et inacceptable au 21ème siècle ! Choisir entre l’Amour et la dépendance financière c’est exclure les personnes handicapés de la société alors qu’elles en font partie !

> Seuls les parents ont la charge financière de leurs enfants handicapés ce n’est pas le rôle du (futur) conjoint / compagnon !

Rendez nous notre dignité et autorisez nous à vivre heureux, à sortir de cette solitude imposée !