---
title: "« Faire ceci ou cela avec mon autorisation»"
author: "Anthony"
date: "2021-06-14"
categories: [indépendance, projets]
---

J’ai 30 ans, asperger, en couple avec Andréa, 24 ans, également asperger. 

Nous percevons tous les deux l’AAH. J’ai eu la chance de trouver un emploi que je commence au premier septembre. Nous vivons tous les deux chez nos parents, et

> une de nos premières priorités est de vivre le cordon ombilical coupé, comme un couple que nous sommes dans un appartement loué. 

Débutant en vacataire catégorie B dans la fonction publique, mon salaire net ne sera pas mirobolant. 
Ma copine risque de perdre son AAH alors que, elle, est encore en recherche d’emploi. 
Nous avons chacun de notre côté bien entendu des factures, des coûts fixes (comme une voiture chacun à entretenir, des rendez vous medicosociaux, assurances, téléphone, ou encore bientôt des dépenses alimentaires) .
Ce probable « trou » nous place en situation d’inconfort, mais pire, empêcherait ma copine d’avoir son propre porte-monnaie et l’amènerait dans la situation inconfortable de me demander de l’argent pour vivre, autrement dit, faire ceci ou cela « avec mon autorisation ».

> Les femmes se sont battues et ont eu le droit de vote et celui d’ouvrir un compte en banque sans l’aval du mari, au XXe siècle. En sommes-nous vraiment là en 2021?