---
title: "«Je renonce même à une vie sentimentale»"
author: "Jakie"
date: "2021-03-31"
categories: [dignité, renoncement, solitude]
---

Je suis handicapée et reconnue. J’ai eu un accident de travail en 2001 et depuis c’est la descente aux enfers. J’ai été opérée 26 fois donc je ne peux travailler. Je vis avec des douleurs 24/24, tout au long de l’année. J’en subis les conséquences physiques et psychologiques. Tout ça pour entendre me dire qu’avec les années, ça ne va pas aller mieux. Je suis donc condamnée à des traitements lourds à vie. Chaque jour, je suis dans un état différent. Donc j’étais obligée de dépendre des revenus de mes compagnons.

> Je renonce même à une vie sentimentale car suivant les revenus que la personne perçoit, je perdrais aussi ma dignité.

Cette solitude, c’est un cauchemar ! C’est très dur à vivre, car il y a des moments où j’aimerais partager un peu d’amour avec une personne de mon choix. Dans des moments très douloureux , savoir que j’ai une personne avec moi en cas de soucis.

> Au lieu de tous ces petits rien qui peuvent faire beaucoup, je reste seule dans ma prison de souffrances, juste pour ne pas perdre l’unique revenu dont j’ai droit avec le minimum pour vivre qui est l’AAH.