---
title: "«Mon handicap est bien là, et ne partira qu’au moment où je partirai aussi»"
author: "Nathalie"
date: "2021-05-08"
categories: [dépendance financière, dépression, enfants]
---

J’ai 47 ans et je suis reconnue handicapée à plus de 80% . Je percevais mon AAH jusqu’à ce que ma fille, qui est en apprentissage, perçoive un peu plus de 55% du SMIC.  Ce qui m’a fait baisser mon allocation de plus de moitié !

> La CAF m’a dit que je risque de tout perdre par rapport au fait que je n’ai plus d’enfant à charge. Pourtant, ils vivent chez nous !

La CAF prendra en compte que le salaire de mon mari, qui n’est pas suffisant pour 4 à la maison. De plus, je ne veux pas demander à mes enfants une participation, car ce n’est pas dans notre façon de vivre et de les éduquer. Je me sens dépendante de mon mari physiquement et financièrement. J’ai besoin de lui pour la toilette, le ménage et tout le reste… En plus financièrement, ça me met le moral au plus bas. C’est pas juste que l’on coupe mon AAH car mon handicap est bien là, et ne partira qu’au moment où je partirai aussi.

> S’il vous plaît, votez pour la désolidarisation des revenus du conjoint. Par pitié, aidez-moi à me sentir mieux, au moins au niveau financier ! Aidez les personnes handicapées comme moi…