---
title: "«En aucun cas, je ne veux vivre aux crochets de mon ami !»"
author: "Pascale"
date: "2021-05-02"
categories: [choix de vie, indépendance, renoncement]
---

J’ai 54 ans, je touche l’AAH depuis juin 2020. Mon ami et moi sommes ensemble depuis 7 ans.

> Nous avions le projet de vivre sous le même toit. Cependant, étant donné que son salaire dépasse le plafond, mon AAH serait supprimée. Nous avons donc renoncé à ce projet.

J’insiste sur le fait que cette aide est conçue pour ceux qui ne peuvent pas ou plus travailler et pour pouvoir améliorer notre état de santé qui engendre des coup très élevés : soins non remboursés, matériel médical partiellement ou peu remboursé, etc.

> En aucun cas, je ne veux vivre aux crochets de mon ami ! 

Je voudrais insister sur le fait que l’AAH est considérée comme un revenu social, sauf, surprise : pour obtenir un petit prêt, c’est considéré comme une « aide sociale ». Donc refus !

A ce jour, le statut de l’AAH n’est pas clair ! Je vis donc dans un appartement assez précaire (234€ sur lequel se déduit une APL de 227€). 

> Pas besoin d’APL si nous pouvions vivre ensemble !

Je ne comprends absolument pas et j’espère que cette nouvelle loi de déconjugalisation va passer.