---
title: "«La solidarité dans un couple est déjà tellement présente à longueur de journée...»"
author: "Gwen"
date: "2021-04-13"
categories: [20 ans enfant, dignité, épuisement, solidarité familiale]
---

Actuellement, mon mari a une invalidité à + 80%. Il a une inaptitude à vie pour le travail. Nous avons deux enfants de moins de 20 ans, nous touchons l’intégralité de son AAH soit 902 euros. Dans quelques années, si la loi ne change pas, nous n’aurons plus que mon salaire d’aide soignante pour survivre, et le mot est pesé.

> Comment peut-on comparer l’AAH avec le RSA ? Pour l’un des deux, le retour à l’emploi n’est plus possible. La solidarité familiale est primordiale mais sur le plan financier, comment accepter de dépendre de quelqu’un ? Quelle dignité reste-t-il à ses personnes que la vie a déjà cabossé ? 

Je voulais aussi ajouter que mon métier d’aide soignante me permet de voir dans mon service beaucoup d’aidants qui sont hospitalisés car usés moralement et physiquement. Il n’est pas rare de voir que les aidants décèdent avant leur conjoint.s.es atteint.s.es de handicap car ils.elles sont à bout. C’est malheureusement la triste réalité.

> La solidarité dans un couple est déjà tellement présente à longueur de journée, je viens combler tout ce que mon mari ne peut pas faire seul ou pour les enfants.

Il fait tout son possible pour m’aider mais sa maladie le submerge vite et le fait craquer face au premier obstacle. Mon mari a une maladie invisible qui est encore plus compliqué à faire admettre, je dois gérer la maison, les enfants, l’école après ou avant mon travail.

> En étant mariés, l’État fait des économies puisque seul, mon mari serait dans l’obligation d’avoir des aides, alors en plus nous supprimer l’AAH… Quelle injustice !