---
title: "«Ce que nous espérons c’est juste la possibilité de nous aimer librement»"
author: "Philippe"
date: "2021-03-27"
categories: [décohabitation, liberté]
---

Je suis atteint de SLA avec + 80% d’invalidité, je touche l’intégralité de l’AAH soit 902€ par mois.

> Ce montant largement insuffisant me maintient en dessous du seuil de pauvreté.

Malgré ma maladie, j’ai eu la chance de rencontrer l’amour avec une auxiliaire de vie qui gagne 1300€ par mois environ. Dans la mesure où son temps de travail la maintient souvent à l’extérieur, je bénéficie d’une aide de vie dans le cadre de la PCH pour m’aider dans mon quotidien. Si celle-ci venait à disparaître, cela obligerait ma compagne à être plus présente à mes cotés et cela poserait des problèmes dans la gestion de son propre emploi du temps et très certainement que cela entraînerait une baisse de salaire pour elle.

> Si cette loi sur la déconjugalisasion des revenus passe, nous pourrions vivre ensemble et poursuivre notre histoire sans une perte financière pour moi, ce que je n’accepte pas.

Nous, ce que nous espérons c’est juste la possibilité de nous aimer librement, sans une perte financière ou une perte des prestations d’aide à mon égard.