---
title: "«Je demande la déconjugalisation de l’AAH afin de vivre décemment»"
author: "Émilie"
date: "2021-03-29"
categories: [décence, précarité]
---

J’ai 43 ans (bipolaire diagnostiquée depuis 20 ans environ) et en couple depuis 10 ans. Avant, je travaillais donc pas de problème. Mais depuis août 2018 je suis au chômage : je percevais un reliquat de chômage, l’AAH et une pension d’invalidité. Mais mes droits de chômage se sont terminés en septembre 2020. Janvier 2021, on apprend que je ne percevrai plus que 15 euros d’AAH parce que les revenus du couple (nous sommes déclarés en concubinage auprès de la CAF) de 2019 dépassent le plafond ! Or, mon compagnon est intermittent du spectacle. On ne sait pas s’il va y avoir une deuxième année blanche (impossible de travailler à cause de la Covid 19), et dans son cas, le RSA se transformera en RSA de couple (d’une valeur inférieure). Heureusement, j’ai une pension d’invalidité de 750 euros par mois.

> C’est donc moi, qui avec ma pension d’invalidité, vais devoir assumer le couple et sans l’AAH ! On marche sur la tête !

Déjà que je me sentais dépendante financièrement mais maintenant nous sommes trop riches pour percevoir l’AAH…

> Je demande la déconjugalisation de l’AAH afin de vivre décemment, de façon autonome et de ne plus dépendre des revenus de notre conjoint. À croire qu’il serait plus facile de rester seul-e ou de ne pas se déclarer en concubinage.

**C’est la fin de l’amour… pourtant celui qui nous donne des ailes et qui nous permet de nous sentir soutenus moralement et financièrement.**

