---
title: "«Je vis avec mon homme mais pas officiellement»"
author: "Christelle"
date: "2021-05-08"
categories: [dépression, impossibilité de travailler, incompréhension, se cacher]
---

J’ai 40 ans. Il y a plus de dix ans ma vie a basculé. Je souffre d’une cyphose thoraco lombaire, entre autres problèmes de santé… Cette pathologie est irrémédiable, irréversible. Ce sont des douleurs intenses, je n’ai pas pu garder mon emploi, j’ai subi des discriminations… J’ai tout perdu, boulot, vie sociale et vie amoureuse. J’ai vécu sous morphine pendant longtemps à haute dose.

Je déprime trop, je me suis faite hospitalisée car j’ai eu envie de mourir. Je sors de l’hôpital psy faute d’argent, et je m’oriente vers un centre anti-douleur. On stoppe la morphine, et on me blinde d’anti-dépresseurs, qui doivent agir sur la douleur. Je prends dix fois plus de médocs, plein de trucs, trop de trucs. Puis retour à la morphine, j’ai essayé de travailler de nouveau mais j’ai encore perdu mon travail. Je m’adapte mal à la morphine, je craque et ça casse. Je retourne vivre chez mes parents. Pôle emploi ne sait pas quoi faire de moi et m’envoie vers Cap emploi. On me propose une super formation d’infographiste, mais je me paralyse pendant la formation à Paris, je dois rembourser toute la formation, car ce serait comme un abandon ! On ne sait pas non plus quoi faire de moi. Je n’y vais plus, je suis dégoûtée. Malgré toutes mes galères, je rencontre quelqu’un sur internet. Je subis des opérations, je porte un corset, en continu. J’ai droit à l’AAH, je suis soulagée, je peux rembourser mes dettes.

> Je me mets en appartement avec mon homme. Enfin je vois le bout du tunnel… Mais tout s’effondre…

Après trois mois d’immobilité totale, à réapprendre à marcher, se baisser, conduire… La douleur revient tous les jours un peu plus. C’est pire qu’avant. On me propose d’autres opérations, très compliquées et très lourdes. Le choc… Fini les rêves… Je m’effondre. Dépression. Le couple tient même si c’est dur. On s’aime. Je reprend le dessus, je prépare une demande de renouvellement pour l’AAH.

> J’atterris, je suis handicapée. Fini les rêves et la vie normale. Je dois préparer le futur de ma situation qui va empirer, maintenant je le sais. L’AAH avec mon homme, ce n’est pas possible avec son salaire, même si il est blindé de dettes.

Je ne peux plus travailler. Donc ? Je dois me débrouiller avec mon AAH pour le restant de ma vie. Je n’ai pas le choix, je dois prendre un appartement à mon nom. Mon homme ne peut pas payer pour moi, je ne veux pas dépendre de lui non plus. Je ne suis déjà plus bonne à rien, je ne peux plus rien faire, je ne veux pas en plus n’avoir plus d’argent à moi… On ne peut pas vivre ensemble. On ne peut pas acheter une maison. On ne peut pas se marier. On vit cachés… J’ai un appart’ qui ne sert à rien. Il y a un frigo avec un peu de nourriture en date longue, je le chauffe en hiver. Mes affaires et mes vêtements sont presque tous là bas, ainsi que mes papiers. Je vis avec mon homme mais pas officiellement. Nos amis savent.

> On m’empêche de vivre. On m’empêche de pouvoir dire que je vis avec l’homme que j’aime.

On ne pourra jamais construire un foyer, on n’aura jamais notre maison, on n’aura jamais notre vie. Je déteste mon handicap, je déteste cette vie. Ce n’est pas juste. Ce qu’il y a de pire dans tout ça, c’est que l’État perd de l’argent, en encourageant la fraude !

AAH 900€ On m’aide pour EDF 175 € On m’aide pour la mutuelle 200 € J’ai l’APL 275 € =\> Total dépensé par l’Etat : 1550 € Je donne pour mon appartement qui ne sert à rien : 200 €. Donc je me débrouille bien avec 900 € d’AAH, il me reste 700€. Je coûte 1550 € à l’Etat.

> Si je pouvais être en couple et toucher mon AAH, je pourrais me payer ce dont j’ai besoin. Vivre à deux, toucher deux revenus, c’est partager les frais quotidiens et du foyer.

Je n’aurai pas besoin de toutes ces aides ! Je ne comprends pas. J’espère que les sénateurs et les députés nous écouterons.
