---
title: "«Je prendrai ma décision sur le divorce selon le vote du gouvernement»"
author: "Sylvie"
date: "2021-05-14"
categories: [dépendance financière, divorce, fardeau]
---

Je suis mariée depuis 2008, je suis tombée malade en 2007 (tumeur cérébrale à évolution lente). Mon mari a changé de travail en 2016 et tout a basculé pour le calcul de mon AAH. Aujourd’hui je dépends financièrement de mon mari qui travaille beaucoup.

> Je ne supporte plus cette situation. Je suis devenue un boulet.

Mon fils a eu des problèmes santé qui persistent aujourd’hui encore. Je ne peux pas m’occuper de lui et de ma santé. J’ai besoin de l’aide de mon mari, il s’occupe de beaucoup de tâches à la maison. La perte de mon AAH a compliqué les perspectives d’avenir de notre couple et a aussi changé notre vie amoureuse.

Je pense que si la loi ne passe pas le 17 juin, je divorcerai et me retrouverai seule avec mon fils, lui aussi en situation de handicap. Il faudra aussi mettre en place une aide humaine pour mon fils et moi, pour les taches quotidiennes.

> Rendez-vous donc le 17 juin, je prendrai ma décision sur le divorce selon le vote du gouvernement.
